### ISSUE TITLE
OSX Mojave fresh install doesn't install tokend - 0.20.0 

### ISSUE THREAD

**Issue by jreeder** [OpenSC/OpenSC#1986] opened 2020-03-21 00:39 UTC
### Problem Description

On a recent fresh install the tokend pkg would not install. Using the latest pkg installer for 0.20 downloaded on 3/20/2020. I repeated the uninstall / restart / install cycle 3 times. 

I tried all of the installers back to 0.19. 

0.19 , 0.20 rc1, and 0.20 rc2 all install and up update tokend correctly. 

0.20 rc3, 0.20 rc4, and 0.20 do not install or update tokend. 

If you install them in sequence tokend stays and remains the version from Oct 3, 2019. So it wouldn't be obvious that it isn't updating. 

The pkcs11 and opensctoken pkgs install and work fine. 

### Steps to reproduce

1. Install 0.20 on clean OSX Mojave 10.14.6
2. check for tokend install. 

Alternative: 
1. Install 0.19 - 0.20 including rc releases. 
2. check status of tokend after each install. 
3. tokend stops updating after rc2 and shows Oct 3, 2019 as modified date.

**Comment by frankmorgner** [comment] 2020-03-22 10:12
From the release notes:
```
macOS installer

    Add installer option to deselect tokend (#1607)
    Make OpenSCToken available on 10.12+ and the default on 10.15+ (2017626)
```

You need to "change the configuration" during the installation.

**Comment by bra1ncramp** [comment] 2020-04-28 17:20
@frankmorgner , this does not actually seem to be closed. You say to change the configuration during installation. By default, TokenD-based smart card driver is marked to install - but there are Zero bytes associated with it (see screenshot).
![image](https://user-images.githubusercontent.com/52966515/80517442-153f9200-8953-11ea-8a26-d7658632ae45.png)

**Comment by jreeder** [comment] 2020-04-28 21:14
Sorry to have left this without a response. I am aware that the installer changed, my issue is that even when you check the box it is not installed. I went through every installer back through the betas, from a clean slate installation, and non of the newer ones installed the tokend driver even when the box was checked. It's as the screen shot above says.

**Comment by frankmorgner** [comment] 2020-04-28 23:17
This could be due to the missing notarization, see also https://github.com/OpenSC/OpenSC/issues/1934

**Comment by brodjieski** [comment] 2020-04-29 00:39
I don't believe that notarization comes into play at this point.  Notarization will prevent the execution of an application, but not necessarily the installation.

Looking at the files within the OpenSC 0.20.0.pkg from that DMG, there is a OpenSC-tokend.pkg referenced that should be an option to install, but looking inside the installer, that package has an empty payload, and you can see when you extract it, there is nothing to deliver.  So whoever created the .dmg and installer files didn’t include the tokend pieces.
```
➜  open.pkg cd OpenSC-tokend.pkg 
➜  OpenSC-tokend.pkg ls
Bom         PackageInfo Payload
➜  OpenSC-tokend.pkg lsbom Bom
.	40755	0/0
➜  OpenSC-tokend.pkg ls -l
total 88
-rw-r--r--  1 root  wheel  35177 Dec 29 07:55 Bom
-rw-r--r--  1 root  wheel    473 Apr 28 20:26 PackageInfo
-rw-r--r--  1 root  wheel     80 Dec 29 07:55 Payload
➜  OpenSC-tokend.pkg tar -xzvf Payload 
x .
```

**Comment by brodjieski** [comment] 2020-04-29 13:52
Looking a bit further into the build-package.in script, there is a requirement that in order to build the OpenSC.tokend you must be using a version of XCode less than v10.. so perhaps when 0.20.0 was built, it was using a newer version of XCode, and therefore just skipped the inclusion of the OpenSC.tokend package?

**Comment by frankmorgner** [comment] 2020-05-02 09:59
I have integrated Tokend and CTK into the dmg from the CI environment https://github.com/OpenSC/OpenSC/pull/2004. Could you check if https://github.com/OpenSC/Nightly/raw/2020-05-02_63cd4ebf/OpenSC-0.20.0.dmg contains a working tokend?

**Comment by bra1ncramp** [comment] 2020-05-04 19:01
![image](https://user-images.githubusercontent.com/52966515/81002976-1de30d00-8e18-11ea-9d27-28e38bed12d5.png)

**Comment by brodjieski** [comment] 2020-05-04 20:02
@frankmorgner I can confirm that the tokend package is included in the installer... however, like @bra1ncramp shows, there is an error generated during installation.  The ./postinstall script has an unexpected error around line 45, the closing of the IF statement.  The installer doesn't go beyond that point, and the subsequent packages don't get delivered, so I can't completely verify installation of the tokend.

**Comment by frankmorgner** [comment] 2020-05-04 20:55
This time it should be due to notarization; an app was blocked from installation and can therefor not be loaded by launchctl. I've added a workaround in the PR.

**Comment by frankmorgner** [comment] 2020-05-07 01:50
could you try https://github.com/OpenSC/Nightly/raw/2020-05-04_e267dcda/OpenSC-0.20.0.dmg?

**Comment by bra1ncramp** [comment] 2020-05-19 14:12
@frankmorgner , I apologize for the delay in getting back. I still receive the same Installation Failed as above.

This from the install.log may be helpful:
```
./postinstall: /tmp/PKInstallSandbox.fUxEgr/Scripts/org.opensc-project.mac.2EJRYM/postinstall: line 45: `fi'
```

`Cleared permissions on Installer.app
`

```
PackageKit: Install Failed: Error Domain=PKInstallErrorDomain Code=112 "An error occurred while running scripts from the package “OpenSC 0.20.0.pkg”." UserInfo={NSFilePath=./postinstall, NSURL=file:///Volumes/OpenSC/OpenSC%200.20.0.pkg#OpenSC.pkg, PKInstallPackageIdentifier=org.opensc-project.mac, NSLocalizedDescription=An error occurred while running scripts from the package “OpenSC 0.20.0.pkg”.} {
	    NSFilePath = "./postinstall";
	    NSLocalizedDescription = "An error occurred while running scripts from the package \U201cOpenSC 0.20.0.pkg\U201d.";
	    NSURL = "file:///Volumes/OpenSC/OpenSC%200.20.0.pkg#OpenSC.pkg";
	    PKInstallPackageIdentifier = "org.opensc-project.mac";
	}

```

**Comment by frankmorgner** [comment] 2020-06-02 10:54
I took some time to analyze this in detail. The problem is complex and most likely caused by the security changes made since High Sierra, which can't easily be ignored anymore.

The App runs fine when locally build, but inside the pkg it doesn't even install to /Applications properly. The Logs in konsole or when running

```
sudo installer -pkg OpenSCToken.pkg  -target / -verbose
```

aren't really helpful. (OpenSCToken.pkg is included as part of OpenSC 0.20.0.pkg) My last guess would be that the installation is prevented by Gatekeeper because the signing on the installer isn't correct (there currently is none). There's a good summary (https://wiki.freepascal.org/Code_Signing_for_macOS) which points out, that the App needs to be code signed (☑️), the pkg needs to be installer signed (I can't) and the dmg needs to be codesigned and submitted for notarization (never got to this step).

So, I don't have any ideas and you are my last resort! If you run#

```
git clone https://github.com/OpenSC/OpenSC
cd OpenSC
git clone https://github.com/frankmorgner/OpenSCToken
export OTHER_CODE_SIGN_FLAGS='--timestamp --options=runtime' CODE_SIGN_INJECT_BASE_ENTITLEMENTS=NO CODE_SIGN_STYLE=Manual
export CODE_SIGN_IDENTITY="your identity string"
MacOSX/build
```

Then everything gets built including the OpenSCTokenApp. (The same is done in CI with the code signing credentials).

I have also tried packaging the plain app into an dmg, but Gatekeeper prevents running this app (from the image) when downloaded from the web.

The missing bits seem to be the installer signing and the notarization (and stapling). We're looking for someone with an macOs installer certificate (99$ a year) who can help debugging this and maybe create a working bundle again...

**Comment by frankmorgner** [comment] 2020-06-02 12:03
Sorry for the noise, I looked at OpenSCToken, not the tokend module.

**Comment by frankmorgner** [comment] 2020-06-02 16:14
Next try: I'm not sure what exactly went wrong with the release binaries, but the [current nightly build](https://github.com/OpenSC/Nightly/raw/2020-06-02_e98f6733/OpenSC-0.20.0.dmg) successfully installs the TokenD, so it's fixed by now. However, there's still an unrelated problem with the CTK token (see #1934).

**Comment by bra1ncramp** [comment] 2020-06-03 12:51
It did install. But after reboot, I do not see my PIV card in the Keychain any longer.

**Comment by bra1ncramp** [comment] 2020-06-03 13:22
```
$ piv-tool --help
dyld: Library not loaded: /Library/OpenSC/lib/libcrypto.1.1.dylib
  Referenced from: /usr/local/bin/piv-tool
  Reason: image not found
Abort trap: 6
```

**Comment by bra1ncramp** [comment] 2020-06-03 13:34
```
$ pkcs11-tool --type cert -O
dyld: Library not loaded: /Library/OpenSC/lib/libcrypto.1.1.dylib
  Referenced from: /usr/local/bin/pkcs11-tool
  Reason: image not found
Abort trap: 6
```

**Comment by frankmorgner** [comment] 2020-06-03 13:36
Sigh, I'll check again. Sorry for the inconvenience.

**Closed** 2020-06-03 19:52 UTC

**Comment by frankmorgner** [comment] 2020-06-04 04:18
The loader's error is fixed. I can't test the TokenD, however.

**Comment by bra1ncramp** [comment] 2020-06-04 12:37
Thank you, Frank. It looks like TokenD is working, now!
