### ISSUE TITLE
CKR_BUFFER_TOO_SMALL from C_Sign with Feitian ePass2003

### ISSUE THREAD

**Issue by johughes99** [OpenSC/OpenSC#2154] opened 2020-11-17 19:23 UTC
I am trying to sign some data using ECDSA and NIST P-256 on a Feitian ePass2003.  But no matter what I do i keep getting a CKR_BUFFER_TOO_SMALL error return from C_Sign

I have tried all sorts of combinations of values for the buffer size and length.  But still keep getting CKR_BUFFER_TOO_SMALL

NitroKey HSM is fine with this code - as well as other OpenSC devices.  Also other non-OpenSC devices

One example of the code is below

`CK_BYTE signature[4096];
	CK_ULONG ulSignatureLen = 160;

	rv = (*theFunctionList->C_SignInit)(hSession, &mechanism, hPrivateKey);
	errorCheck(hSession, rv, "C_SignInit");
	if (rv != CKR_OK) {
		free(data);
		return 1;
	}

	rv = (*theFunctionList->C_Sign)(hSession, data, dataSize, signature, &ulSignatureLen);
	errorCheck(hSession, rv, "C_Sign");`

I have tried all sorting of combination for ulSignatureLen - but nothing works.  Just keep getting CKR_BUFFER_TOO_SMALL

**Comment by dengert** [comment] 2020-11-17 21:23
You say you are doing ECDSA. Is that CKM_ECDSA or CKM_ECDSA_SHA1? (or one of the other hashes like SHA256.)

PKCS\#11-curr-v2.40 Section 2.3 says:
"The ECDSA without hashing mechanism, denoted CKM_ECDSA, is a mechanism for single-part
signatures and verification for ECDSA. (This mechanism corresponds only to the part of ECDSA that
processes the hash value, which should not be longer than 1024 bits; it does not compute the hash
value.)"

What is the value of dataSize? Table Table 32, ECDSA: Key and Data Length says it can be any length,
but  footnote 3: "Input the entire raw digest. Internally, this will be truncated to the appropriate number of bits." 

It could be datalength is too long, and the driver is not truncating as in footnote 3. 

2.3.7 ECDSA with SHA-1 (or other hashes) allows any length, as the hash is computed internal to PKCS\#11 or on the card. 

An OpenSC debug log or PKCS11_SPY output would be helpful.

**Comment by johughes99** [comment] 2020-11-17 22:28
It is CKM_ECDSA and I am trying to sign a data block of a size larger than 1024 - so it could be its not truncating the input correctly.  I have seen this as an issue for a few other devices.  However, it was the error return of CKR_BUFFER_TOO_SMALL that was confusing me.

I will get a OpenSC debug log for you tomorrow.

**Comment by johughes99** [comment] 2020-11-18 09:58
[opensc_debug.log](https://github.com/OpenSC/OpenSC/files/5559208/opensc_debug.log)

Attached is the debug output from the key pair generation to calling C_Sign.  I cant see anything in the log that indicates exactly what is going on.

**Comment by Jakuje** [comment] 2020-11-18 10:37
Can you try with the current 0.21.0-rc2 pre-release? there were some fixes in the epass driver, which might fix this issue.

**Comment by dengert** [comment] 2020-11-18 13:20
Looks like you are generating the EC keypair then using it to sign in the same program.

try 0.21.0-rc2 which may not resolve the issue but will help us in debugging. 

PKCS11-curr-v2.40-cs1 in section 2.3.4 Elliptic curve private key objects says: 
"Note that when generating an EC private key, the EC domain parameters are not specified in the key’s
template. This is because EC private keys are only generated as part of an EC key pair, and the EC
domain parameters for the pair are specified in the template for the EC public key.
The following is a sample template for creating an EC (ECDSA) private key object:"

Then in the template for the private key in has `{CKA_EC_PARAMS, ecParams, sizeof(ecParams)},`  and both then goes on to say: "The mechanism generates EC public/private key pairs with particular EC domain parameters, as specified in the CKA_EC_PARAMS or CKA_ECDSA_PARAMS attribute of the template for the public key."

The code appears to be failing in pkcs11/mechanism.c: 
```
 506                         case CKK_EC:
 507                                 /* TODO: -DEE we should use something other then CKA_MODULUS_BITS... */
 508                                 rv = key->ops->get_attribute(operation->session, key, &attr);
 509                                 *pLength = ((*pLength + 7)/8) * 2 ; /* 2*nLen in bytes */
```
because pLength i.e. CKA_MODULUS_BITS is 0.

The key may have been created correctly, but the in memory data may not have been updated so it could be used later in the same application, but would be updated if used in a different application. 

**So can you try adding CKA_EC_PARAMS to the private key template?** 

Problem may be in framework-pkcs11.c:
```
2150                 case CKK_EC:
2151                         args.key.algorithm = SC_ALGORITHM_EC;
2152                         /* TODO: -DEE Do not have PKCS15 card with EC to test this */
2153                         /* fall through */
2154                 default:
2155                         return CKR_ATTRIBUTE_VALUE_INVALID;
```
Also related to framework-pkcs11.c: from lines 3698-3749 that to great lengths to find the key size.
and 
```
3838                         case SC_PKCS15_TYPE_PRKEY_EC:
3839                                 if (key) {
3840                                         if (key->u.ec.params.field_length > 0)
3841                                                 *(CK_ULONG *) attr->pValue = key->u.ec.params.field_length;
3842                                         else
3843                                                 *(CK_ULONG *) attr->pValue = (key->u.ec.ecpointQ.len - 1) / 2 *8;
3844                                 }
3845                                 return CKR_OK;
```

**Comment by johughes99** [comment] 2020-11-18 13:29
I will download  0.21.0-rc2 and try later today - doing some other tests right now which I cant interrupt  

I will also try the  CKA_EC_PARAMS suggestion as well  - but note this code does work fine with Nitrokey HSM - and any other device I  have tested that supports ECDSA (plus SoftHSM and opencryptoki)

**Comment by dengert** [comment] 2020-11-18 14:05
Ok. Can you try doing the generate key in one process, then try the c_sign in a second process? 
I am looking to see if we are missing something when the key is created and used immediately.

**Comment by dengert** [comment] 2020-11-18 14:17
You say you code works with Nitrokey HSM - and any other device. Is this using their PKCS11 modules or OpenSC pkcs11 for all?

I have an old Feitian ePass2003, not sure if it does EC or not. Could you send me your program, (or key parts) so I could try and reproduce the problem?

**Comment by johughes99** [comment] 2020-11-18 14:36
This is a combination of openSC devices and using the vendor's .so library.  In terms of OpenSC devices my tool works fine with:

- NitroKey HSM
- Yubikey FIPS
- Taglio PIVKey T840

So I believe the core of OpenSC is fine.

Im afraid the code for this is all part of this large test harness I have and its not easy to extract out I'm afraid.  But I will email you the key parts

**Comment by johughes99** [comment] 2020-11-18 16:01
[config_errors.log](https://github.com/OpenSC/OpenSC/files/5561205/config_errors.log)
I'm in the process of tying to build OpenSC-0.21.rc2 on Ubuntu 18.04 - but getting some errors

Obviously some stuff is missing - include a MS header??

What do I need to do to fix?

**Comment by Jakuje** [comment] 2020-11-18 16:47
> [config_errors.log](https://github.com/OpenSC/OpenSC/files/5561205/config_errors.log)
> I'm in the process of tying to build OpenSC-0.21.rc2 on Ubuntu 18.04 - but getting some errors
> 
> Obviously some stuff is missing - include a MS header??
> 
> What do I need to do to fix?

Install  libpcsclite-dev

https://packages.ubuntu.com/xenial/amd64/libpcsclite-dev/filelist

**Comment by johughes99** [comment] 2020-11-18 19:21
rc2 built successful.  However, still getting the same error.  Have sent a small test program to @dengert so he can try out.

Let me know if you want me to run it with openSC debug logging again with rc2

**Comment by dengert** [comment] 2020-11-19 00:51
Tried your test program with my old epass2003 from 2014. It does not support EC keys.

What looks strange in your original opensc-debug.log are lines 596-600:
```
P:4077; T:0x140030865818816 09:45:38.084 [opensc-pkcs11] card-epass2003.c:2449:epass2003_gen_key: returning with: 0 (Success)
P:4077; T:0x140030865818816 09:45:38.084 [opensc-pkcs11] card.c:1024:sc_card_ctl: returning with: 0 (Success)
P:4077; T:0x140030865818816 09:45:38.084 [opensc-pkcs11] pkcs15-epass2003.c:671:epass2003_pkcs15_generate_key: returning with: 0 (Success)
P:4077; T:0x140030865818816 09:45:38.084 [opensc-pkcs11] pkcs15-pubkey.c:617:sc_pkcs15_encode_pubkey_rsa: called
P:4077; T:0x140030865818816 09:45:38.084 [opensc-pkcs11] asn1.c:1721:asn1_encode_entry: encoding 'publicKeyCoefficients'
```

This looks like the key is created on the card, and pkcs15 data on the card may be correct, but it looks like `sc_pkcs15_encode_pubkey` is calling `sc_pkcs15_encode_pubkey_rsa` rather then `sc_pkcs15_encode_pubkey_ec`. This may be a problem in `pkcs15init/pkcs15-epass2003.c` 

If 0.21.0-rc2 does not fix your problem, can you send another opensc-debug.log but with `debug = 9;`

Or you can compile opensc with CFLAGS=-g and LDFLAGS -g  and then run `gdb` 
set `break sc_pkcs15_encode_pubkey_rsa` then `run` and when it stops get a backtrace `where` then `up` to get to `sc_pkcs15_encode_pubkey` then `p *key` to print the `sc_pkcs15_pubkey` to see why  it thinks it is RSA rather the EC.

**Comment by johughes99** [comment] 2020-11-19 11:34
Slightly confused but now working with rc2.

This morning I downloaded rc2 onto my main dev machine - and rebuilt  And it worked fine.  See attached debug log file

Then I went  back to my native Ubuntu test machine - and that worked fine with rc2 as well (but had errors last night - even after rc2 was installed)

The only thing I can thing is that I did a reboot of the test machine this morning - and perhaps it wasn't until the reboot that it picked up some of the new rc2?

[opensc-debug-worked.log](https://github.com/OpenSC/OpenSC/files/5566446/opensc-debug-worked.log)

**Comment by johughes99** [comment] 2020-11-19 11:44
OK - now slightly confused.

Downloaded this morning rc2 onto my main dev machine.  And it worked fine.  See attached working log.

Then went back to my dev machine - and as last night still fails.  See attached log.

Both are running Ubuntu 18.04. The dev machine is a VM on VirtualBox - but the host is a i7. The test machine is a native Ubuntu on a i5 laptop,

one thing I did notice is that the dev machine built OpenSC with gcc 8.4.0 and the test machine with gcc 7.5.0

[opensc-debug-failed.log](https://github.com/OpenSC/OpenSC/files/5566503/opensc-debug-failed.log)

[opensc-debug-worked.log](https://github.com/OpenSC/OpenSC/files/5566504/opensc-debug-worked.log)

**Comment by johughes99** [comment] 2020-11-19 12:22
rebuilt opensc rc2 with gcc 8.4.0 - but still fails.  So not an issue with gcc

**Comment by dengert** [comment] 2020-11-19 12:49
opensc-debug-failed.log line 5682 calls  pkcs15-pubkey.c:617:sc_pkcs15_encode_pubkey_rsa: called
which is the problem. 

opensc-debug-worked.log line 5882 calls pkcs15-pubkey.c:762:sc_pkcs15_encode_pubkey_ec: called
which is correct.

line 2 shows the version of OpenSC:

failed  is opensc version: 0.20.0
worked is opensc version: 0.21.0-rc2 


Somewhere you are picking up the old version of OpenSC 

Run `ldd opensc-pkcs11.so` on the version you are loading.
Look for  libopensc.so and see if it is the old or new version.

For testing  you can  set env LD_LIBRARY_PATH=<path to your test libs> so it will look there.

or add or pass to configure  LDFLAGS="-g -Wl,-rpath,/opt/ossl-1.1/lib"
I build multiple versions, so /opt/ossl-1.1/lib is with for testing openssl-1.1 in my case and includes OpenSC and libp11 versions. 
Also add to configure --prefix=/opt/ossl-1.1 

I used to use Ubuntu 18.04, now 20.04 under VirtualBox with Windows 10 host.

**Comment by dengert** [comment] 2020-11-19 13:16
This is fixed in 0.21.00 by #1859  f334f3eabe79fa0dff660c113e5b2a96825a3063 in pkcs15-epass2003.c

**Comment by johughes99** [comment] 2020-11-19 13:49
I can see that..

On the working dev machine I have two instances of opensc-pkcs11.so:

- /usr/lib/x86_64-linux-gnu/opensc-pkcs11.so

- /usr/lib//opensc-pkcs11.so

The first one reports libopensc.so.5 and the second one as libopensc.so.6.  I am pointing at the second one on my dev machine - and hence it works.

So that make sense. Although when the install of openSC occurred - why didn't it overwrite the /usr/lib/x86_64-linux-gnu/opensc-pkcs11.so old version

On the test machine I also have both instances of the so.  And they both report libopensc.so.6

In different attempts I then pointed the test program at both those instances of the .so - and both failed

As you suggest I then set the env variable LD_LIBRARY_PATH=/usr/lib

This then worked

So indeed rc2 fixes the fault.  However, just intrigued about how this came about - having a mixture of 2 x openSC on the same machine

**Comment by dengert** [comment] 2020-11-19 23:13
I have 8 test versions of OpenSC and friends that use OpenSSL and the system installed version.  As I said above running configure with   --prefix= can keep the straight, except for dynamically loaded modules, which search at run time for shared libraries linking a module with  LDFLAGS="-Wl,-rpath,<path-to-libs>"

Google for: rpath dynamic linking 

man ld.so

Normally /usr/local/lib is before the system libs, so rather then change the system version of a program or lib, one can install into /usr/local

**Closed** 2020-11-20 09:18 UTC
