### ISSUE TITLE
firefox does not remove the certificates even when token gets disconnected

### ISSUE THREAD

**Issue by ashwaniksoni** [OpenSC/OpenSC#1908] opened 2020-01-20 11:03 UTC
If Oseid token, which is loaded with certificate connected with windows/linux PC and accessed in firefox using opensc, it display loaded certificate in firefox. but if I remove the token, firefox still maintain the certificate and does not remove untill I restart the firefox.

**Comment by frankmorgner** [comment] 2020-01-20 12:31
The slot description should change to *empty*. With 0.20.0 there should also have been some improvement when removing and re-inserting a token... Please give more input about your setup.

**Comment by ashwaniksoni** [comment] 2020-01-20 13:50
Setup details:
Oseid Token
RHEL7.1/Windows 7
Mozilla firefox 72.01(64-bit)/Adobe Reader 9
OpenSC 0.19 (64-bit)

**Comment by frankmorgner** [comment] 2020-01-20 13:57
Maybe you want try 0.20.0?

**Comment by frankmorgner** [comment] 2020-02-20 21:26
may be related to https://github.com/OpenSC/OpenSC/issues/1935

**Comment by dengert** [comment] 2020-02-20 22:43
There is some confusion about what is a token. OpenSC and PCSC treat a USB reader as a slot that can have a card.  PKCS11 talks about slots and tokens.  Your Oseid Token looks like it has the builtin USB reader. 

Firefox can handle the removal of a card from a reader which should clean up the certificates, but does not handle the removal of a  USB token which is a card with a builtin reader. PKCS11 defines slots and tokens. 

Maybe OpenSC should present the removal as two separate events.  if it sees a reader removed which had a card,  First return that card was removed and then  after the next C_GetSlotList, remove the reader. Firefox does not handle removal of slots (i.e. readers) .

This can be simulated if one has a card in a reader and removes the reader with the card attached vs removing just the card and then the reader.

**Comment by popovec** [comment] 2020-02-21 06:51
Just for clarity, OsEID token = simulated Gemalto reader with inserted OsEID card (card is always present). 

tests, firefox 68.5.0esr (from debian)

1. no security device = no certificates in "Your Certificates"
2. loaded opensc-pkcs11.so, no card, no reader = no certificates in "Your Certificates"
3. attached USB reader, no card  = no certificates in "Your Certificates"
4. OsEID card in reader, (View Certificates, pin dialog cancelled) = two certificates on card in "Your certificates"
5. Reader with card removed from USB ((View Certificates, **Pin dialog** - why ? ) = I can see one certificate ??? (1st certificate on card)
6. reattached reader with card,  (View Certificates, pin dialog cancelled) = two certificates on card in "Your certificates"
7. card removed from reader (no pin dialog) = no certificates in "Your Certificates"

Result: firefox behaves strangely when the card reader (with card) is disconnected.

**Comment by dengert** [comment] 2020-02-21 12:59
Yes this is related to #1935. The problem is not with OpenSC to PCSC, but with interpretation of  PKCS11  Firefox and OpenSC for handling removed slots. Firefox assumes slots can only be added. OpenSC can convert a slot it wants to remove to a HotPlug slot, or removes it and the slot IDs get renumbered. Firefox continues to use old slot IDs even after a C_GetSlotList. Firefox also caches certificates it has read, thus your point 5. But if card is removed but not slot, Firefox cleans up cached certificates.

**Comment by Jakuje** [comment] 2022-09-29 12:23
This looks like it was fixed with #1970 so closing. If it is not the case, please reopen or start a new issue.

**Closed by Jakuje** 2022-09-29 12:23 UTC
Labels: Input needed
