### ISSUE TITLE
OpenSC 0.25.1 dmg not notarized correctly

### ISSUE THREAD

**Issue by mmoraga** [OpenSC/OpenSC#3113] opened 2024-04-15 08:06 UTC
### Problem Description
The macOS release of OpenSC 0.25.1 is not correctly notarized

<img width="372" alt="image" src="https://github.com/OpenSC/OpenSC/assets/1709645/2a7f8e4f-99fd-4d5a-857a-ec4b0f360286">

### Proposed Resolution
It should be properly notarized, like earlier releases.

### Steps to reproduce
Download dmg from github releases page and try to install.
https://github.com/OpenSC/OpenSC/releases/download/0.25.1/OpenSC-0.25.1.dmg

**Comment by frankmorgner** [comment] 2024-04-15 08:15
duplicate of #2683

**Closed by frankmorgner** 2024-04-15 08:15 UTC

**Comment by mmoraga** [comment] 2024-04-15 09:00
Sure, but 0.25.0, 0.24.0 etc are correctly notarized while 0.25.1 is not. Isn't having automation for this a separate issue?
