### ISSUE TITLE
Events

### ISSUE THREAD

**Issue by faezeh-R** [OpenSC/OpenSC#629] opened 2015-12-08 11:34 UTC
Hi;
The function of waitForSlotEvent with detaching the reader doesn't get the correct event.
It returns the NO_Event. I tested it with pkcs11-tools.exe
Also in using the pkcs#11.dll in Firefox , when the reader has been attached, the list of slots changes but when the reader has been detached the list doesn't change. 
The driver of reader is pcsc.
thanks

**Comment by frankmorgner** [comment] 2015-12-08 11:36
How can we reproduce this error?

**Comment by faezeh-R** [comment] 2015-12-08 11:47
If you use the Firefox, You see that after detaching the reader, the list of slot doesn't change.
If you want to test it with pkcs11-tools.exe, with running the "--test-hotplug"  options for testing the waitForSlotEvent ,you can see this error.
It shows that the event of detaching reader doesn't get the correct event.

**Comment by faezeh-R** [comment] 2015-12-08 11:49
I correct it.

**Comment by dengert** [comment] 2015-12-08 17:01
Can you run FireFox with SPY, to see what FireFox is actualing
    doing? 
    
    C_WaitForSlotEvent returns that aan event has happened. The
    application has to then test what happened. 
    
    I suspect that FireFox is either getting CKR_FUNCTION_NOT_SUPPORTED
    and will then use  a loop  calling  C_GetSlotInfo  to see shat
    happened. 
    
    https://github.com/OpenSC/OpenSC/pull/624 addresses the issue that 
    C_GetSlotInfo  does not returning the true state. 
    
    
    
    On 12/8/2015 5:47 AM, Faezeh wrote:
    
    
      If you use the Firefox, You see that after detaching the
        reader, the list of slot doesn't change.
        If you want to test it with pkcs11-tools.exe, with running the
        "--test-hotplug" options for testing the waitForSlotEvent ,you
        can see this error.
        It shows that the event of detaching reader doesn't get the
        correct event.
      —
        Reply to this email directly or view
          it on GitHub.
      
        
          
          
        
        
      
    
    
    -- 

 Douglas E. Engert  <DEEngert@gmail.com>

**Comment by dengert** [comment] 2015-12-08 17:38
#624 addresses C_GetSessionInfo, not C_GetTokenInfo, but a similar issue may exist.

**Comment by frankmorgner** [comment] 2015-12-08 19:56
I think the real problem is that PKCS#11 defines the list of slots to be static until `C_GetSlotList` is called the next time with `pSlotList == NULL`. Quoted from PKCS#11 v2.30:
> If an application calls C_GetSlotList with a non-NULL pSlotList, and then the user adds or removes a hardware device, the changed slot list will only be visible and effective if C_GetSlotList is called again with NULL

But instead, OpenSC deletes the slot in `card_detect_all` if the reader is removed. This desynchronizes the state that within OpenSC (*without* slots of this reader) and the state within Firefox (*with* slots of this reader).

@faezeh-R could you check how to solve this problem with static slots until `C_GetSlotList` is called again?

**Comment by dengert** [comment] 2015-12-08 21:58
FireFox tries to use C_WaitForSlotEvent On Ubuntu at least, but OpenSC  returns 
CKR_FUNCTION_NOT_SUPPORTED
This should also be looked at. 
./pkcs11-global.c
662         sc_log(context, "C_WaitForSlotEvent(block=%d)", !(flags & CKF_DONT_BLOCK));
663         /* Not all pcsc-lite versions implement consistently used functions as they are */
664         /* FIXME: add proper checking into build to check correct pcsc-lite version for SCardStatusChange/SCardCancel */
665         if (!(flags & CKF_DONT_BLOCK))
666                 return CKR_FUNCTION_NOT_SUPPORTED;

**Comment by frankmorgner** [comment] 2016-03-11 00:16
@faezeh-R could you check whether the problem is fixed with https://github.com/OpenSC/OpenSC/commit/1fb741338a010515b35f28cd9c769561f3e574a2?

**Comment by frankmorgner** [comment] 2016-09-01 22:49
`pkcs11-tool --test-hotplug` shows the behavior which you are expecting:
```
Testing card detection using C_GetSlotList()
Please press return to continue, x to exit: 
Available slots:
Slot 0 (0x0): Virtual PCD 00 00
  (empty)
Slot 1 (0x4): Virtual PCD 00 01
  (empty)
Please press return to continue, x to exit:
```
attach reader:
```
Slot 0 (0x0): Virtual PCD 00 00
  (empty)
Slot 1 (0x4): Virtual PCD 00 01
  (empty)
Slot 2 (0x8): Identive Identive CLOUD 4500 F Dual Interface Reader [uTrust 470
  (empty)
Slot 3 (0xc): Identive Identive CLOUD 4500 F Dual Interface Reader [uTrust 470
  (empty)
Please press return to continue, x to exit:
```
remove reader:
```
Slot 0 (0x0): Virtual PCD 00 00
  (empty)
Slot 1 (0x4): Virtual PCD 00 01
  (empty)
```
However, the [above analysis](https://github.com/OpenSC/OpenSC/issues/629#issuecomment-162996685) explains the strange behaviour in Firefox. Firefox (or to be exact, NSS) doesn't expect a slot to be removed from the list because it violates PKCS#11, see [NSS source comment](https://github.com/servo/nss/blob/master/lib/pk11wrap/pk11util.c#L894-L901).

**Comment by viktorTarasov** [comment] 2016-12-04 09:31
@frankmorgner 
> doesn't expect a slot to be removed from the list because it violates PKCS#11, see NSS source comment

For my curiosity,
can you indicate where in _PKCS-11-v2.20_ the removing of the slots violates the standard ?

**Comment by frankmorgner** [comment] 2016-12-04 09:40
Here is the exact quote from pkcs11 v 2.3:
> All slots which C_GetSlotList reports must be able to be queried as valid slots by C_GetSlotInfo. Furthermore, the set of slots accessible through a Cryptoki library is checked at the time that C_GetSlotList, for list length prediction (NULL pSlotList argument) is called. If an application calls C_GetSlotList with a non-NULL pSlotList, and then the user adds or removes a hardware device, the changed slot list will only be visible and effective if C_GetSlotList is called again with NULL. Even if C_ GetSlotList is successfully called this way, it may or may not be the case that the changed slot list will be successfully recognized depending on the library implementation. On some platforms, or earlier PKCS11 compliant libraries, it may be necessary to successfully call C_Initialize or to restart the entire system.

As referenced above, NSS doesn't re-initialize the slot list. Internally, we used to remove a slot once we detect a removal of a card/reader. However, PKCS#11 is saying that we should have waited until `C_GetSlotList` is called with `NULL` again.

**Comment by dengert** [comment] 2016-12-04 20:01
That same text is also in pkcs-11v2-20.pdf

**Closed** 2017-01-09 07:35 UTC
