### ISSUE TITLE
Client-certificate authentication in Firefox 53.0 x32/Windows 10 x64 using an Oberthur ID-One Cosmo v7 smart card

### ISSUE THREAD

**Issue by lmiguelmh** [OpenSC/OpenSC#1031] opened 2017-04-19 17:16 UTC
### Expected behaviour

I am trying to use an Oberthur smart card for client-certificate authentication (two way ssl/tls authentication) in Firefox 53.0 x32/Windows 10 x64: 
Model: ID-One Cosmo v7.0
Firmware: Applet JavaCard AuthentIC v3.22 

### Actual behaviour

After entering the PINs and selecting the certificate Firefox fails with error: SEC_ERROR_INVALID_ALGORITHM

### Steps to reproduce

This are the steps I used:
1. I downloaded and installed the OpenSC-0.16.0-win32_vs12-Release.msi. I chose the win32 version because the version of Firefox that I am using has this architecture (x32).
2. I configured the opensc pkcs#11 library as a security device for Firefox. 
3. When accessing the https webpage Firefox is prompting me for my PIN (which is correct) but both the Signature PIN and the User PIN (I think only the User PIN should be prompted).  Then, I select my User certificate to present as identification to the server.
4. Next, I got this error message in the browser:

Secure Connection Failed
An error occurred during a connection to java.webapp.org. security library: invalid algorithm. Error code: SEC_ERROR_INVALID_ALGORITHM
- The page you are trying to view cannot be shown because the authenticity of the received data could not be verified.
- Please contact the website owners to inform them of this problem.

Does OpenSC make some kind of verification to the certificate? If true, from where does opensc retrieve the certificate authorities?

### Logs

As stated in the guidelines I have used opensc-tool and pkcs15-tool (I dont past some results for brevity):

> opensc-tool.exe -l -a -n
Detected readers (pcsc)
Nr.  Card  Features  Name
0    Yes             Gemplus USB SmartCard Reader 0
Using reader with a card: Gemplus USB SmartCard Reader 0
3b:dd:18:00:81:31:fe:45:80:f9:a0:00:00:00:77:01:00:70:0a:90:00:8b
Oberthur AuthentIC 3.2.2

> opensc-tool.exe --info
OpenSC 0.16.0 [Microsoft 1800]
Enabled features:pcsc openssl zlib

> pkcs15-tool.exe -D
_output showing pin, keys and X509 certificates_

> pkcs11-tool.exe  -I
Cryptoki version 2.20
Manufacturer     OpenSC Project
Library          OpenSC smartcard framework (ver 0.15)
Using slot 0 with a present token (0x0)

> pkcs11-tool.exe -L
Available slots:
Slot 0 (0x0): Gemplus USB SmartCard Reader 0
  token label        : OT AWP (User PIN)
  token manufacturer : Oberthur Technologies
  token model        : PKCS#15
  token flags        : rng, login required, PIN initialized, token initialized
  hardware version   : 0.0
  firmware version   : 0.0
  serial num         : 147CCE95
Slot 1 (0x1): Gemplus USB SmartCard Reader 0
  token label        : OT AWP (Signature PIN)
  token manufacturer : Oberthur Technologies
  token model        : PKCS#15
  token flags        : rng, login required, PIN initialized, token initialized
  hardware version   : 0.0
  firmware version   : 0.0
  serial num         : 147CCE95

> pkcs11-tool.exe -O
Using slot 0 with a present token (0x0)
Certificate Object, type = X.509 cert
_more output_

I almost forgot this is a Peruvian National Identity Card (DNIe).

opensc-debug.log located in https://gist.github.com/lmiguelmh/1845c59b145db3e7d8bf0c5f977acf11#file-gistfile1-txt

**Comment by frankmorgner** [comment] 2017-04-19 22:06
Your card never reports an error (i.e only `90 00`). I think this error is also reported when the certificate on your card was issued by an unknown CA.

To isolate the problem, please use `pkcs11-tool --test --login`.

**Comment by lmiguelmh** [comment] 2017-04-20 15:30
Thanks for your reply. 
The root CA and intermediate CA are installed in Windows certificate manager. 
This is the output I am obtaining after executing the `pkcs11-tool` command:

> pkcs11-tool.exe --test --login
Using slot 0 with a present token (0x0)
Logging in to "OT AWP (User PIN)".
Please enter User PIN: C_SeedRandom() and C_GenerateRandom():
  seeding (C_SeedRandom) not supported
  seems to be OK
Digests:
  all 4 digest functions seem to work
  MD5: OK
  SHA-1: OK
  RIPEMD160: OK
Signatures (currently only RSA signatures)
  testing key 0 (Clave Privada de Autenticacion)
Verify (currently only for RSA):
  testing key 0 (Clave Privada de Autenticacion)
Unwrap: not implemented
Decryption (RSA)
  testing key 0 (Clave Privada de Autenticacion)
    RSA-PKCS: Mechanism not supported
No errors

The command returns 0.

**Comment by dengert** [comment] 2017-04-20 22:03
As far as I know, Firefox does not use the Microsoft certificate store. It has its own built in certificate store. Tools->Options->Advanced->View Certificates  leads to the certificate manager. You can import your CA and intermediate certificates here

At one time there was a Security Device called nsscapi, but as far as I know it never made it into the production Mozilla NSS. It was designed to use the Microsoft Certificate Store. 
Security Devices are PKCS#11 modules, so you can also use the OpenSC SPY as a security device if you have the OpenSC pkcs11 module  in the PKCS11_SPY environment variable.

**Comment by lmiguelmh** [comment] 2017-04-21 00:30
It is weird because I do have both the root and the intermediate authorities configured in Firefox's certificate manager. I tried using `pkcs11-spy.dll` as a security device. I tried the `x64` version too. I changed the TLS version for the server to 1.0, 1.1, and 1.2. In every case the error was the same: `SEC_ERROR_INVALID_ALGORITHM`. I copy here the _https server logs_ for [opensc with firefox](https://gist.github.com/lmiguelmh/9bec456b26eb8034319896f4066a12d8) and [minidriver with iexplore](https://gist.github.com/lmiguelmh/28bb32962fa32df049bcef563650f675) (_works!_).

**Comment by dengert** [comment] 2017-04-21 10:08
We need some logs from the client side. The spy logs to start with. 
https://github.com/OpenSC/OpenSC/wiki/Using-OpenSC

Do you have client's CA  in server?

Do you have client's CA and intermediate certificates in the FireFox store? 

Google for: SEC_ERROR_INVALID_ALGORITHM
See if any of the responses are your problem, and if any have a solution.

**Comment by dengert** [comment] 2017-04-21 12:49
Instead of OpenSC SPY  Mozilla NSS PKCS#11 has its own PKCS\#11 trace
by setting environment variable  `NSS_DEBUG_PKCS11_MODULE` See:
https://developer.mozilla.org/en-US/docs/Mozilla/Projects/NSS/Reference/NSS_environment_variables

OpenSC developers might find this interesting too, especially the "PKCS #11 information" section:
https://developer.mozilla.org/en-US/docs/Mozilla/Projects/NSS

**Comment by dengert** [comment] 2017-04-21 20:31
Using the OpenSC SPY should be as easy as setting in the security device manager
module name: OpenSC-SPY
Module filename:  (Browse to:) C:\Program Files (x86)\OpenSC Project\PKCS11-Spy\pkcs11-spy.dll

If you already have an opensc-pkcs11 module, delete it first, because they will both compete for the card.)

The log will default to this location C:\Users\<current user>\AppData\Local\Temp\pkcs11-spy.log

NSS does polling of the PKCS\#11 module, so it can fill up the log with a lot of calls, so do your tests quickly to keep the log short. 

I don't have a server that will accept any of my smart card certificates, but I can see that the 
log is created, and the card was accessed, and I can login. 

Tested on 
Windows 10 pro 64 bit
Firefox 53.0 (32-bit)
OpenSC 32 and 64 bit loaded from the https://github.com/OpenSC/OpenSC/wiki  Nighly builds from Appveyor https://ci.appveyor.com/project/LudovicRousseau/opensc/branch/master
0.16.0.1226. 
Then for the 32 and 64 bit versions click on each of these:

Environment: VSVER=14 Configuration: Debug; Platform x86
 Artifacts:  then download: OpenSC-win32_vs14-Debug.msi
Environment: SVER=14 Configuration: Debug; Platform x64
   Artifacts:   then download: OpenSC-win64_vs14-Debug.msi

**Comment by lmiguelmh** [comment] 2017-04-22 01:05
Thanks _a lot_ for your answers.

I uninstalled all previous versions of OpenSC and installed the one from https://ci.appveyor.com/project/LudovicRousseau/opensc/branch/master/: OpenSC-win32_vs14-Debug.msi (I performed a complete install). 

I configured a new security device on Firefox:
Module Name: OpenSC-SPY
Module Filename: c:\Program Files (x86)\OpenSC Project\PKCS11-Spy\pkcs11-spy.dll

I have three security modules: 
NSS Internal PKCS#11 Module
Builtin Root Module, and 
OpenSC-SPY.

I connected my smartcard reader and reopened Firefox. In Firefox's security devices manager I saw my card's certificates are recognized and I can do "Log In" with any of them: 
OpenSC-SPY
-User PIN (OT AWP)
-Signature PIN (OT AWP)
I "Log Out" from both and delete the logs for the next steps .

I navigated to the webapp and as usual Firefox asks me for my Signature PIN and my User PIN. After that Firefox let me choose what certificate I will present as identification to the server (for the https handshake). Firefox fails with SEC_ERROR_INVALID_ALGORITHM. I closed the browser to keep the log short.

Here are the contents from [%userprofile%\AppData\Local\Temp\pkcs11-spy.log](https://gist.github.com/lmiguelmh/0c9335eb156ead2786ca63a3a01741a8#file-pkcs11-spy-log). From the 263 calls there are 30  that don't end with `Returned:  0 CKR_OK`. I made a summary from the contents with only the functions that "fail: [pkcs11-spy.log.failed](https://gist.github.com/lmiguelmh/805f2585e2da1ec19fbc777378d40d09#file-pkcs11-spy-log-failed).

Tested on
Windows 10 pro 64bit
Firefox 53.0 32bit
OpenSC 32bit (debug) loaded from the nighly builds from Appveyor 

Here you can find a project with basic x509 authentication in Java with spring boot  https://github.com/przodownikR1/basicAuth509 the https authentication

**Comment by lmiguelmh** [comment] 2017-04-22 01:34
It is weird but the [https server logs](https://gist.github.com/lmiguelmh/9bec456b26eb8034319896f4066a12d8) show the server hello finalizing correctly:

```
*** ServerHelloDone
https-jsse-nio-8081-exec-4, WRITE: TLSv1.2 Handshake, length = 2169
```
What fails is the ClientHello, I assume because of some unsupported algorithm...

**Comment by dengert** [comment] 2017-04-22 11:34
What we really need to see a lot more of the trace. What is the key usage from the certificate, what mechanisms (algorithms) does the card and software say they support. (They may not actually support all of them and that could be the problem.) And what mechanism is FireFox requesting and for which key. 

If you don't what to expose to much info, to the trace you send , XXXXX out the pins in the C_Login  but tell us which pin is which . You  may want to blank out the certificates, but tell us which one is which and the keyUsage for each. (You can get that from the View Certificates.) 

What  type of card, are you using, is it a government or employer issued card? Did you provision it yourself? OPenSC supports many different types of cards and each has its only sent of issues.

Usually for a web client authentication, only one certificate is used, so it is not clear why you had to provide two pins. This could also cause the problem, as internally maybe only one can be active at a time.

There is also a onepin-opensc.pkcs11.dll that might address you having to enter 2 pins. (I have never used it but other developers have.)

**Comment by frankmorgner** [comment] 2017-04-22 13:41
There are two generic fixes pending, that may be related: https://github.com/OpenSC/OpenSC/pull/1034 and https://github.com/OpenSC/OpenSC/pull/1033

**Comment by frankmorgner** [comment] 2017-04-22 13:43
I meant https://github.com/OpenSC/OpenSC/pull/1034 and https://github.com/OpenSC/OpenSC/pull/1032

**Comment by dengert** [comment] 2017-04-22 14:11
Good point. https://github.com/OpenSC/OpenSC/pull/1034 could explain the need for two PINS.  We still don't know which mechanisum or which OpenSC driver is being used. We only now it is an Oberthur ID-One Cosmo v7 and that C_SignInit Returned CKR_MECHANISM_INVALID. We do know it works with the minidriver, so it may be an issue in the PKCS\#11 code or the algorithms the card says it supports.

The full spy trace would help.

**Comment by lmiguelmh** [comment] 2017-04-24 16:49
Thanks again for all your answers. This is what I got:

1. What type of card, are you using, is it a government or employer issued card? Did you provision it yourself? OPenSC supports many different types of cards and each has its only sent of issues.
- This is a government issued card (National Identity Card or DNIe) so I didn't provisioned it myself. This card has 2 certificates: one should be used for digital signatures ("FIR") and one for authentication ("AUT"). 

2. What is the key usage from the certificate:
- For the signing certificate (FIR): Firefox said: "this certificate has been verified for the following uses: Email Signer Certificate". In the certificate viewer: 
  - "Certificate Key Usage" : "Critical" and "Non-repudiation"
  - "Extended Key Usage" : "Not Critical" and "E-mail protection (1.3.6.1.5.5.7.3.4)"

- For the authentication certificate (AUT): Firefox said: "SSL Client Certificate". In the certificate viewer: 
  - "Certificate Key Usage" : "Critical" and "Signing"
  - "Extended Key Usage" : "Not Critical" and "TLS Web Client Authentication (1.3.6.1.5.5.7.3.2)"

3. What we really need to see a lot more of the trace. 
- See below in step 6.

4. What mechanisms (algorithms) does the card and software say they support. (They may not actually support all of them and that could be the problem.) And what mechanism is FireFox requesting and for which key.
- How do I do this?

5. Usually for a web client authentication, only one certificate is used, so it is not clear why you had to provide two pins. This could also cause the problem, as internally maybe only one can be active at a time.
- Exactly! Only one PIN (the authentication pin) should be asked. At least this is what happens when using the minidriver (only the authentication pin is asked).

6. There is also a onepin-opensc.pkcs11.dll that might address you having to enter 2 pins. (I have never 
 used it but other developers have.)
- Reading about this I found martinpaljak comment in some old [issue](https://github.com/OpenSC/OpenSC/issues/356) stating that:

> Firefox can't handle PKCS#11 modules with more than one slot [...] Firefox even did not know how to select the "right" certificate for web authentication, considering nonrepudiation certificates as "stronger and thus better" certificates for web authentication.

- Using `create_slots_for_pins = "user"` in _opensc.conf_ solve the 2-pin problem. Now only the User PIN is prompted but the SEC_ERROR_INVALID_ALGORITHM continues. Here are the full logs with only one PIN prompted: [pkcs11-spy.full.log](https://gist.github.com/lmiguelmh/3cbabb25e6dbe90c8114411a1ded900d#file-pkcs11-spy-full-log). As this is the full log without edits I may delete it later.

7. We still don't know which mechanism or which OpenSC driver is being used.

- I am using OpenSC-win32_vs14-Debug.msi from https://ci.appveyor.com/project/LudovicRousseau/opensc/branch/master/

**Comment by dengert** [comment] 2017-04-24 18:48
OpenSC developers: in https://gist.github.com/lmiguelmh/3cbabb25e6dbe90c8114411a1ded900d#file-pkcs11-spy-full-log
In event 162, FireFox calls C_OpenSession to open a new session. 
in event 162, FireFox calls C_SignInit  which returns CKR_MECHANISM_INVALID. 

Forefox already opened a session in event 9, and did a C_Login in event 60. 
Why would it open another session? 

Why would OpenSC return  CKR_MECHANISM_INVALID for C_SignInit? 

Since the session was a public session, I would suspect C_SignInit should have returned CKR_USER_NOT_LOGGED_IN 

Any Ideas?

**Comment by dengert** [comment] 2017-04-27 13:32
@rickyepoderi, @frankmorgner, 
@lmiguelmh said his card is a  Peruvian National Identity Card (DNIe). Could this be related DNIe issues?

I was able to get Firefox 53.0 (32-bit) on Windows 10 64bit Pro with a test PIV card with an AUTH certificate to authenticate to  OpenSSL-1.1 s_server on Ubuntu.   The spy trace shows the same calls to get a new session and C_SignInit returns CKR_OK and completes as expected. 

In regard to my question of CKR_USER_NOT_LOGGED_IN.
PKCS\#11 says the C_Login applies to all sessions, so disregard my question. 

@lmiguelmh  if you want to did deeper, you may want to to modify the opensc.conf file to turn on opensc debugging.   https://github.com/OpenSC/OpenSC/wiki/Using-OpenSC

**Comment by rickyepoderi** [comment] 2017-04-27 14:37
:smile: I don't think is the DNIe driver. DNIe is the Spanish acronym for "Documento Nacional de Identidad electrónico" which means something like "Electronic National Identity Document" or eID in general. I suppose is the equivalent of the Spanish DNIe but in Peru. They have tested the driver before doing a "opensc-tool --name" and it seems to be an "Oberthur AuthentIC 3.2.2".

**Comment by frankmorgner** [comment] 2017-05-04 12:36
The generic fixes mentioned above are merged now. You could try again, with an up to date version, @lmiguelmh.

**Comment by lmiguelmh** [comment] 2017-05-10 19:07
Thank you and Sorry for the late answer...
@frankmorgner Do you know if the nightly builds from Appveyor (https://ci.appveyor.com/project/LudovicRousseau/opensc/branch/master) include the changes you speak about? Anyway I am now installing `OpenSC-win32_vs14-Debug.msi`.

**Comment by lmiguelmh** [comment] 2017-05-10 21:29
OK, I've installed the latest version from https://ci.appveyor.com/project/LudovicRousseau/opensc/build/0.16.0.1247 but the problem continues :( (`186: C_SignInit ... Returned:  112 CKR_MECHANISM_INVALID`)

Here are the full logs: 
- opensc-debug.log https://gist.github.com/lmiguelmh/e8867017eaac31dc808a85f3ea633f71
- pkcs11-spy.log https://gist.github.com/lmiguelmh/3a9a73668cc15b3c936170072702a3d7

Using OpenSC SPY module with `debug = 9;` and `create_slots_for_pins = "user"`. 

```
opensc-tool.exe --version
OpenSC-0.16.0-252-gb41e446, rev: b41e446, commit-time: 2017-05-09 18:50:15 +0000
```

**Comment by dengert** [comment] 2017-05-11 20:23
This could be caused by  pkcs11/framework-pkcs15.c: pkcs15_prkey_can_do
in line 3817                 `return CKR_MECHANISM_INVALID;`
because libopensc/types.h has:
`#define SC_MAX_SUPPORTED_ALGORITHMS	8`

The SPY trace lists 11 mechanism. 

It is not clear from the dump if this is the case.  You could try setting it to 16 and recompile.

Any developer want to comment on why this is so low?
Do any others fail like this?

**Comment by frankmorgner** [comment] 2017-07-31 21:46
`CKR_MECHANISM_INVALID` can be caused if `sc_pkcs11_find_mechanism` doesn't find the requested signature scheme (). That shouldn't be bad per se, since usually there are other alternatives. However, it could be that the server is configured to accept only a scheme that either OpenSC or the card doesn't support.

@lmiguelmh please verify if you server's configuration should work with that card. Do you have a different (working!) PKCS#11 provider that you could use the SPY module with?

**Closed** 2017-09-12 20:45 UTC
Labels: Bug, Input needed

**Comment by lmiguelmh** [comment] 2019-03-26 21:58
Only to confirm that the problem is fixed.
Thank you Frank for your help!
