### ISSUE TITLE
npa-tool.exe fails to perform pace authentication with can value

### ISSUE THREAD

**Issue by codyax1** [OpenSC/OpenSC#2354] opened 2021-06-17 02:36 UTC
### Problem Description
I have a german eID test card that i am working on, and a and a compatible PCSC reader on windows 10.
I am trying to read ICCSN value of the card.
First step is to establish secure PACE channel. Test Card has a CAN value.
Doesn't Work. I followed the command prompt syntax as written for npa-tool.exe

### Steps to reproduce
Install latest OpenSC on windows 10
Connect PCSC compatible reader with the german eiD card
Perform this command on command prompt 
C:\Program Files\OpenSC Project\OpenSC\tools>npa-tool.exe -r 0 -v -v -v -c 123123

**Comment by frankmorgner** [comment] 2021-06-17 10:51
can you post the output?

**Comment by codyax1** [comment] 2021-06-17 14:55
I enabled the -verbose flag and it seems it fails at MSE: Set AT
The application is not sending OID params and Domain Parameter in MSE: CRT AT command
Do i have to send EF.CardAccess command to get PACEinfo before sending command npa-tool.exe -r 0 -v -v -v -c 123123 ?
If so how ??
[npa-tool log.txt](https://github.com/OpenSC/OpenSC/files/6671120/npa-tool.log.txt)

**Comment by frankmorgner** [comment] 2021-06-21 12:16
Could you try this patch?
```diff
diff --git a/src/sm/sm-eac.c b/src/sm/sm-eac.c
index 8c12119a..b4cb48a7 100644
--- a/src/sm/sm-eac.c
+++ b/src/sm/sm-eac.c
@@ -1149,6 +1149,7 @@ int perform_pace(sc_card_t *card,
 
                eac_ctx->tr_version = tr_version;
 
+               sc_select_file(card, sc_get_mf_path(), NULL);
                r = eac_mse_set_at_pace(card, eac_ctx->pace_ctx->protocol,
                                pace_input.pin_id, chat, &pace_output->mse_set_at_sw1,
                                &pace_output->mse_set_at_sw2);
```

**Comment by frankmorgner** [comment] 2021-06-21 12:29
Having a second look, I think you're right that the OID is missing in the MSE command.

I think this problem is caused by [an issue in OpenPACE](https://github.com/frankmorgner/openpace/commit/637ae79de394baf56376f5858efa435afee8b86f). This should be fixed in OpenSC's currently available [RC for the new release](https://github.com/OpenSC/OpenSC/releases/tag/0.22.0-rc1). Could you try this instead, please?

**Comment by codyax1** [comment] 2021-06-21 17:16
I tried to install the RC (typical installation). But the installation failed. Attaching the report.[](url)
![OpenSC installation failure](https://user-images.githubusercontent.com/50919056/122801989-72e71a00-d28a-11eb-826a-e8196197239d.PNG)

**Comment by codyax1** [comment] 2021-06-21 17:18
This is the one i used :
![image](https://user-images.githubusercontent.com/50919056/122802247-c3f70e00-d28a-11eb-97cc-6eb7ae2ca59d.png)

**Comment by codyax1** [comment] 2021-06-21 18:03
Ok, the installation works, if i select complete installation (and not for typical installation)
Still, pace authentication doesn't work ! Same problem. 
OID (id_PACE_ECDH_GM_AES_CBC_CMAC_128) is not included in MSE: Set AT command. 
Domain parameter (OD, brainpool256r1) is also not included in MSE: Set AT command.
CHAT is not required to be included for this card in MSE: Set AT command
See logs and screenshot attached !!
(Looks like in your patch, you included only for using PIN. I am using CAN to establish PACE).
"I have german eGK and HBA test cards"

![image](https://user-images.githubusercontent.com/50919056/122806067-7fba3c80-d28f-11eb-8acf-52b100d63f78.png)
[npa tool (RC) log.txt](https://github.com/OpenSC/OpenSC/files/6688590/npa.tool.RC.log.txt)

**Comment by frankmorgner** [comment] 2021-07-07 14:27
For me, the binary installs fine.

However, I can confirm the problem with running PACE in Windows. I'm not sure what causes this problem. Running with  similar configuration on Linux works as expected (OpenPACE 1.1.1 and OpenSSL 1.1.1). Maybe there's some problem with the CI environment...

**Comment by kansasdev** [comment] 2021-12-18 11:51
I confirm this error still exists on Windows (December 2021), even with other ID cards than German (Incorrect parameters in APDU).
I have been trying to buid it from source with above fix (05057e6), after days of struggling I have finally made it (using openssl 1.1.0 win32) and openpace 1.1.2 and visual studio.
Unfortunately, when I am performing npa-tool command I am seeing error: Failed to establish context: Unable to load external module. I have put all new dlls (including opensc.dll) to same directory and I am out of ideas, probably haven't build something. When I am using Dependency walker, no dlls are missing, but this error came rather from inside of a program.
Any hints? If no, when do you plan to put release with openpace 1.1.2?

**Comment by frankmorgner** [comment] 2021-12-22 17:02
https://github.com/OpenSC/OpenSC/pull/2472 fixes this issue. You can test it with the following installers:
- https://ci.appveyor.com/api/buildjobs/3n1ockvih3rj8ntw/artifacts/OpenSC-0.22.0_win32.msi
- https://ci.appveyor.com/api/buildjobs/qvmhanw8a6xiotgf/artifacts/OpenSC-0.22.0_win64.msi

**Comment by kansasdev** [comment] 2021-12-26 11:16
> #2472 fixes this issue. You can test it with the following installers:
> 
> * https://ci.appveyor.com/api/buildjobs/3n1ockvih3rj8ntw/artifacts/OpenSC-0.22.0_win32.msi
> * https://ci.appveyor.com/api/buildjobs/qvmhanw8a6xiotgf/artifacts/OpenSC-0.22.0_win64.msi

I confirm - it works now. Pace can be established on Windows.
BTW - are there any way to dump dg1 or dg2 from ID card? I am not able --read-dg1 --read-dg2 since I am receiving "File not found"

**Comment by frankmorgner** [comment] 2021-12-28 10:02
Currently, selecting eID application is only doen when full EAC (TA+CA) is done as well. This changes with https://github.com/OpenSC/OpenSC/pull/2257, so that always after authentication some application is selected (either eID or ePassport). Please try this PR on top...

**Closed** 2022-03-01 08:12 UTC
