### ISSUE TITLE
opensc 0.22 and openssl 3.0 seem to be an invalid combination

### ISSUE THREAD

**Issue by henning-schild** [OpenSC/OpenSC#2571] opened 2022-06-29 18:36 UTC
### Problem Description

i wrote some words here in a review comment but now decided to make it an issue
https://github.com/OpenSC/OpenSC/commit/c3dcab8b237d42961c0dc12ab2105f3df9073116

It seems that this commit and maybe earlier ones are needed to combine opensc with openssl 3. But users/distros are not really told or aided in not shipping a potentially broken combination.

### Proposed Resolution

create a point release for 0.22 or a stable branch where needed patches are backported, or create a new release and tell people to use this instead of 0.22 when on openssl 3

### Steps to reproduce

use 0.22 with openssl 3 i.e. with fedora 36 or debian testing

```
pkcs11-tool --login --test -v
...
C_SeedRandom() and C_GenerateRandom():
  seeding (C_SeedRandom) not supported
  seems to be OK
Digests:
  all 4 digest functions seem to work
  MD5: OK
  SHA-1: OK
error: PKCS11 function C_DigestInit failed: rv = CKR_GENERAL_ERROR (0x5)
Aborting.`
```

**Comment by henning-schild** [comment] 2022-06-29 19:31
@Jakuje 

as far as i remember you seem to be involved in Fedora, maybe you can repro that in fed36+

and if you can confirm and find a fedora solution, we could go to debian and make sure they do not combo 0.22+3.0 when they choose their next stable

**Comment by henning-schild** [comment] 2022-06-29 19:39
@Zlogene

not sure you already tried opensc 0.22 together with openssl 3, please make sure to run `pkcs11-tool --login --test -v` before allowing that combination in gentoo, maybe add a `DEPENDS dev-libs/openssl<=3` to the 0.22 ebuild in case the combo does not work

**Comment by fbezdeka** [comment] 2022-06-29 21:11
Given that
- the problem is already fixed on master
- 0.23 is on its way
- Fedora and Debian testing (the two distros where I could reproduce this issue) will normally follow and pull in 0.23 (maybe we have to put some presure on that)
- it seems to be a testing issue only (the card still works for normal use cases)

most of us should be fine.

But yes, I agree that there was no warning for distros regarding openssl 3. But maybe we simply discovered it too late.

**Comment by Jakuje** [comment] 2022-06-30 07:59
The commit you mention is only a code for the `pkcs11-tool --test`. I hope nobody sane is using anything based on RIPEMD140 in real applications. The whole bunch of functions needed to build opensc with openssl 3.0 is in #2438.

But until openssl removes the deprecated API, the OpenSC 0.22.0 works just ok with OpenSSL 3.0. The only thing I needed to do was the following change last year and the most common tests (not the `pkcs11-tool --test`) work just ok:

https://src.fedoraproject.org/rpms/opensc/c/2aebc2fc

**Comment by fbezdeka** [comment] 2022-06-30 08:38
> The commit you mention is only a code for the pkcs11-tool --test

That's why I called it "a testing issue". But until I figured out that only that specific `pkcs11-tool --test` is broken I had no guarantee that I can rely on my card. So in combination with openssl 3 the pkcs11-tool tells me that my card is not working, but it actually works (so far).

That's the output from current master:
```
pkcs11-tool --login --test -v 
Using slot 0 with a present token (0x0)
Logging in to "Siemens Corporate ID Card (V5)".
Please enter User PIN: 
C_SeedRandom() and C_GenerateRandom():
  seeding (C_SeedRandom) not supported
  seems to be OK
Digests:
  all 4 digest functions seem to work
  MD5: OK
  RIPEMD160: OK
  SHA-1: OK
  SHA256: OK
Signatures (currently only for RSA)
  testing key 0 (Auth 2021-01-24 2024-01-24) 
  all 4 signature functions seem to work
  testing signature mechanisms:
    RSA-X-509: OK
    RSA-PKCS: OK
    SHA1-RSA-PKCS: OK
    MD5-RSA-PKCS: OK
    RIPEMD160-RSA-PKCS: OK
    SHA256-RSA-PKCS: OK
  testing key 1 (Encr 2021-01-24 2024-01-24) with 1 mechanism
    RSA-X-509: OK
  testing key 2 (Encr 2017-05-10 2020-05-10) with 1 mechanism
    RSA-X-509: OK
  testing key 3 (Encr 2013-01-09 2014-01-09) with 1 mechanism
    RSA-X-509: OK
  testing key 4 (Encr 2020-04-01 2022-04-01) with 1 mechanism
    RSA-X-509: OK
Verify (currently only for RSA)
  testing key 0 (Auth 2021-01-24 2024-01-24)
    RSA-X-509: OK
    RSA-PKCS: OK
    SHA1-RSA-PKCS: OK
    MD5-RSA-PKCS: OK
    RIPEMD160-RSA-PKCS: OK
  testing key 1 (Encr 2021-01-24 2024-01-24) with 1 mechanism
    RSA-X-509: OK
  testing key 2 (Encr 2017-05-10 2020-05-10) with 1 mechanism
    RSA-X-509: OK
  testing key 3 (Encr 2013-01-09 2014-01-09) with 1 mechanism
    RSA-X-509: OK
  testing key 4 (Encr 2020-04-01 2022-04-01) with 1 mechanism
    RSA-X-509: OK
Decryption (currently only for RSA)
  testing key 0 (Auth 2021-01-24 2024-01-24)
    RSA-X-509: OK
    RSA-PKCS: OK
    RSA-PKCS-OAEP: mgf not set, defaulting to MGF1-SHA256
OAEP parameters: hashAlg=SHA256, mgf=MGF1-SHA256, encoding parameter (Label) present, length 3
OK
    RSA-PKCS-OAEP: mgf not set, defaulting to MGF1-SHA256
OAEP parameters: hashAlg=SHA256, mgf=MGF1-SHA256, encoding parameter (Label) not present
OK
  testing key 1 (Encr 2021-01-24 2024-01-24)
    RSA-X-509: OK
    RSA-PKCS: OK
    RSA-PKCS-OAEP: mgf not set, defaulting to MGF1-SHA256
OAEP parameters: hashAlg=SHA256, mgf=MGF1-SHA256, encoding parameter (Label) present, length 3
OK
    RSA-PKCS-OAEP: mgf not set, defaulting to MGF1-SHA256
OAEP parameters: hashAlg=SHA256, mgf=MGF1-SHA256, encoding parameter (Label) not present
OK
  testing key 2 (Encr 2017-05-10 2020-05-10)
    RSA-X-509: OK
    RSA-PKCS: OK
    RSA-PKCS-OAEP: mgf not set, defaulting to MGF1-SHA256
OAEP parameters: hashAlg=SHA256, mgf=MGF1-SHA256, encoding parameter (Label) present, length 3
OK
    RSA-PKCS-OAEP: mgf not set, defaulting to MGF1-SHA256
OAEP parameters: hashAlg=SHA256, mgf=MGF1-SHA256, encoding parameter (Label) not present
OK
  testing key 3 (Encr 2013-01-09 2014-01-09)
    RSA-X-509: OK
    RSA-PKCS: OK
    RSA-PKCS-OAEP: mgf not set, defaulting to MGF1-SHA256
OAEP parameters: hashAlg=SHA256, mgf=MGF1-SHA256, encoding parameter (Label) present, length 3
OK
    RSA-PKCS-OAEP: mgf not set, defaulting to MGF1-SHA256
OAEP parameters: hashAlg=SHA256, mgf=MGF1-SHA256, encoding parameter (Label) not present
OK
  testing key 4 (Encr 2020-04-01 2022-04-01)
    RSA-X-509: OK
    RSA-PKCS: OK
    RSA-PKCS-OAEP: mgf not set, defaulting to MGF1-SHA256
OAEP parameters: hashAlg=SHA256, mgf=MGF1-SHA256, encoding parameter (Label) present, length 3
OK
    RSA-PKCS-OAEP: mgf not set, defaulting to MGF1-SHA256
OAEP parameters: hashAlg=SHA256, mgf=MGF1-SHA256, encoding parameter (Label) not present
OK
No errors
```

**Comment by henning-schild** [comment] 2022-06-30 14:22
I see thanks for the clarification! For some reason i was under the impression that that test failing would be an indication of a sort of serious problem. But if it is not, it might just mean that in the combo the test functionality is kind of "broken".
Maybe that test could "keep going" and in the end print a summary. When dealing with any sort of smartcard issues that test might be amongst the first things people try to see if things are "as expected".

**Comment by Jakuje** [comment] 2022-06-30 17:14
> Maybe that test could "keep going" and in the end print a summary. When dealing with any sort of smartcard issues that test might be amongst the first things people try to see if things are "as expected".

I think that is a good idea. In most of the cases, it does continue, but for some reason not here. Contributions are always welcomed.

**Comment by henning-schild** [comment] 2022-06-30 19:11
In that particular case it would end up as a patch in distros because there will be no stable branch. Say if anyone wrote a patch would you @Jakuje take it into Fedora?

That said, i will probably not be the one to do that ... being on gentoo. But i can imagine @fbezdeka might go there given there was a chance to it accepted. When gentoo switches to openssl 3.0 and staying on 0.22 i might ... but not sure that is going to happen before 0.23

**Comment by Jakuje** [comment] 2022-06-30 20:07
> In that particular case it would end up as a patch in distros because there will be no stable branch. Say if anyone wrote a patch would you @Jakuje take it into Fedora?

Sure. If it would be distinctive patch that would solve the issue, I dont have a problem to backport it to Fedora right away.

**Comment by cheese1** [comment] 2022-08-13 18:18
i tink i have the same problem, but outside of that "test"-case:

i use openfortivpn with a yubikey and have a new error about:
```
[root@localhost ~]# openfortivpn -c /etc/openfortivpn/yubikey 
ERROR:  PKCS11 ENGINE_load_private_key: error:13000075:engine routines::not initialised
INFO:   Closed connection to gateway.
Enter PKCS#11 token PIN for advt0129:
INFO:   Logged out.

[root@localhost ~]#  pkcs11-tool   --test --login 
Using slot 0 with a present token (0x0)
Logging in to "XXXXXX".
Please enter User PIN: 
C_SeedRandom() and C_GenerateRandom():
  seeding (C_SeedRandom) not supported
  seems to be OK
Digests:
  all 4 digest functions seem to work
  MD5: OK
  SHA-1: OK
error: PKCS11 function C_DigestInit failed: rv = CKR_GENERAL_ERROR (0x5)
Aborting.
```
with your patch (with minor changes to be able to apply the patch), i at least get:

```
[cheese@localhost ~]$ OPENSC_DEBUG=1 pkcs11-tool  --login --test
Using slot 0 with a present token (0x0)
Logging in to "XXXXXX".
Please enter User PIN: 
C_SeedRandom() and C_GenerateRandom():
  seeding (C_SeedRandom) not supported
  seems to be OK
Digests:
  all 4 digest functions seem to work
  MD5: OK
  RIPEMD160: OK
  SHA-1: OK
  SHA256: OK
Signatures (currently only for RSA)
  testing key 0 (PIV AUTH key) 
  all 4 signature functions seem to work
  testing signature mechanisms:
    RSA-X-509: OK
    RSA-PKCS: OK
    SHA1-RSA-PKCS: OK
    MD5-RSA-PKCS: OK
    RIPEMD160-RSA-PKCS: OK
    SHA256-RSA-PKCS: OK
Verify (currently only for RSA)
  testing key 0 (PIV AUTH key)
    RSA-X-509: OK
    RSA-PKCS: OK
    SHA1-RSA-PKCS: OK
    MD5-RSA-PKCS: OK
    RIPEMD160-RSA-PKCS: OK
Decryption (currently only for RSA)
  testing key 0 (PIV AUTH key)
    RSA-X-509: OK
    RSA-PKCS: OK
    RSA-PKCS-OAEP: mgf not set, defaulting to MGF1-SHA256
OAEP parameters: hashAlg=SHA256, mgf=MGF1-SHA256, encoding parameter (Label) present, length 3
OK
    RSA-PKCS-OAEP: mgf not set, defaulting to MGF1-SHA256
OAEP parameters: hashAlg=SHA256, mgf=MGF1-SHA256, encoding parameter (Label) not present
OK
No errors

```
this is on fedora 36

**Closed** 2022-12-14 11:30 UTC
