### ISSUE TITLE
EPASS2003 Factory Drivers not working after pkcs15-init -E

### ISSUE THREAD

**Issue by Djalmar** [OpenSC/OpenSC#1804] opened 2019-09-20 21:59 UTC
### Problem Description

 I have run the commands:
```
pkcs15-init -E
pkcs15-init --create-pkcs15 --profile pkcs15+onepin --use-default-transport-key --pin 12345678 --puk 12345678 --label "label_token"
```

They worked fine but now the software from the manufacturer does not recognize the device, there is any way to make it work again? or revert the token to factory settings or something like that ? Or maybe there is another way to initialize the token without affecting the behavior with it's own software.

Sorry for the bad English and thanks in advance

**Comment by frankmorgner** [comment] 2019-09-23 11:26
@FeitianSmartcardReader ?

**Comment by frankmorgner** [comment] 2019-09-23 11:27
should be related to https://github.com/OpenSC/OpenSC/issues/1803

**Comment by frankmorgner** [comment] 2019-09-24 18:02
@FeitianSmartcardReader seems to be inactive, please try contacting the Feitian support directly.

**Comment by FeitianSmartcardReader** [comment] 2019-09-25 03:18
@frankmorgner @Djalmar The issue looks same as #1803 , I already forward to R&D, and waiting their reply, I should have answers from them today and back to you then, thanks

**Comment by Djalmar** [comment] 2019-09-27 14:40
@FeitianSmartcardReader thanks for answering, I will be waiting for any news

**Comment by frankmorgner** [comment] 2019-10-01 09:47
@FeitianSmartcardReader any updates?

**Comment by FeitianSmartcardReader** [comment] 2019-10-01 16:01
Sorry, no update now. Engineer got national holiday in China, they may back to me 8th October. Thanks for your understanding 

From Ben’s Mobile Phone

**Comment by frankmorgner** [comment] 2019-10-10 19:52
Any update?

Am 1. Oktober 2019 18:01:52 MESZ schrieb Feitian Technologies <notifications@github.com>:
>Sorry, no update now. Engineer got national holiday in China, they may
>back to me 8th October. Thanks for your understanding >
>>
>From Ben’s Mobile Phone>
>>
>> 在 2019年10月1日，下午5:47，Frank Morgner <notifications@github.com> 写道：>
>> >
>> @FeitianSmartcardReader any updates?>
>> >
>> —>
>> You are receiving this because you were mentioned.>
>> Reply to this email directly, view it on GitHub, or mute the thread.>
>>
>>
>-- >
>You are receiving this because you were mentioned.>
>Reply to this email directly or view it on GitHub:>
>https://github.com/OpenSC/OpenSC/issues/1804#issuecomment-537106194

-- 
Frank Morgner

**Comment by FeitianSmartcardReader** [comment] 2019-10-15 09:22
Thanks for reminder, checking with them now.

**Comment by FeitianSmartcardReader** [comment] 2019-10-16 02:01
@Djalmar R&D take a look today and they cannot reproduce the issue, is that possible to have a remote session, allow our tech team to double check? 

We do tested FIPS version and without FIPS eps2003 token, both works.
BTW, does your token is the OEM key?

Looking forward to  your reply, you also can send me mail hongbin@ftsafe.com as well,

**Comment by frankmorgner** [comment] 2019-10-22 08:26
@Djalmar should we close this issue?

**Comment by frankmorgner** [comment] 2019-10-22 08:27
@faceless2?

**Comment by faceless2** [comment] 2019-10-22 09:35
Sorry, I just saw this. As it happens, it's now my turn to be away for a couple of weeks. But I will sort out a RPi with the token plugged in and ssh access when I get back. I'm more happy to liaise with @FeitianSmartcardReader directly by email on this, so it makes no difference to me if you close this issue.

**Comment by FeitianSmartcardReader** [comment] 2019-10-22 11:09
@frankmorgner we already create connection, so after he comes back, will keep in touch, thanks

**Comment by Djalmar** [comment] 2019-12-04 19:20
> @Djalmar should we close this issue?

I think so, but tell me when you find an answer to this issue

**Comment by frankmorgner** [comment] 2019-12-04 20:41
OK, then please contact @FeitianSmartcardReader directly; above [they said they are unable to reproduce the problem...](https://github.com/OpenSC/OpenSC/issues/1804#issuecomment-542477007)

**Closed by frankmorgner** 2019-12-04 20:41 UTC

**Comment by FeitianSmartcardReader** [comment] 2019-12-05 01:46
@Djalmar if you still have issues, send me mail hongbin@ftsafe.com and we arrange a remote session with our engineer to do debug, thanks
