### ISSUE TITLE
OpenSC support for Android

### ISSUE THREAD

**Issue by sachindia86** [OpenSC/OpenSC#3210] opened 2024-07-31 05:34 UTC
Is OpenSC works for Android? 
Is any porting guide available for the same?

I am trying to make it work for Android.

I appreaciate if anyone has put efforts on this and willing to share it.

**Comment by frankmorgner** [comment] 2024-08-19 07:53
It's been a couple of years, but it used to work for me. Basically, you are compiling OpenSC for ARM and you need to provide your (proprietary) implementation of libpcsclite.so, which implements the actual communication to the token.

see also #3214

**Comment by frankmorgner** [comment] 2024-08-19 07:55
duplicate of https://github.com/OpenSC/OpenSC/issues/2480

**Closed by frankmorgner** 2024-08-19 07:55 UTC
