### ISSUE TITLE
C_WaitForSlotEvent(CKF_DONT_BLOCK) no longer works properly

### ISSUE THREAD

**Issue by CendioOssman** [OpenSC/OpenSC#2415] opened 2021-10-01 10:43 UTC
### Problem Description

After upgrading from OpenSC 0.19 to 0.22, we've discovered that `C_WaitForSlotEvent(CKF_DONT_BLOCK)` no longer works properly for reader removal. Card removal works fine though.

I suspect the cause of this regression is #1970, but I have not verified this.

The problem can be reproduced with `pkcs11-tool --test-hotplug` if you apply this patch:

```diff
diff --git a/src/tools/pkcs11-tool.c b/src/tools/pkcs11-tool.c
index 881768f1..9184cde9 100644
--- a/src/tools/pkcs11-tool.c
+++ b/src/tools/pkcs11-tool.c
@@ -6457,7 +6457,19 @@ static int test_card_detection(int wait_for_event)
                if (wait_for_event) {
                        printf("Calling C_WaitForSlotEvent: ");
                        fflush(stdout);
-                       rv = p11->C_WaitForSlotEvent(0, &slot_id, NULL);
+
+#if 1
+                       CK_ULONG num_slots;
+                       rv = p11->C_GetSlotList(CK_FALSE, NULL, &num_slots);
+                       if (rv != CKR_OK)
+                               p11_fatal("C_GetSlotList(NULL)", rv);
+#endif
+
+                       rv = p11->C_WaitForSlotEvent(CKF_DONT_BLOCK, &slot_id, NULL);
+                       if (rv == CKR_NO_EVENT) {
+                               printf("no event.\n");
+                               continue;
+                       }
                        if (rv != CKR_OK) {
                                printf("failed.\n");
                                p11_perror("C_WaitForSlotEvent", rv);
```

The call to `C_GetSlotList()` is required by the spec. in our understanding, and this is also supported in practice. With the `C_GetSlotList()` in place OpenSC will report reader addition but not reader removal. Removing that call reverses the situation, i.e. OpenSC will report reader removal but not reader addition.

### Proposed Resolution

Unknown. I'm not familiar enough with this code.

### Steps to reproduce

1. Apply above patch
2. Run `pkcs11-tool --test-hotplug`
3. Keep stepping through `C_WaitForSlotEvent()`
4. Plug in reader with card
5. Remove reader with card

### Logs

Log from poll when using OpenSC 0.22.0:

https://gist.github.com/CendioOssman/d25873fb09c3958cafca4e254284d682

Log from poll when using OpenSC 0.19.0:

https://gist.github.com/CendioOssman/e4c04f3516fe5bff5c93815b00242a1c

**Comment by CendioOssman** [comment] 2021-10-01 10:44
We're going to see if we can work around this by doing a more complex tango with OpenSC:

 1. `C_WaitForSlotEvent(CKF_DONT_BLOCK)`
 2. `C_GetSlotList(NULL)`
 3. `C_WaitForSlotEvent(CKF_DONT_BLOCK)`

**Comment by Jakuje** [comment] 2022-01-25 11:12
Can you check that the issue is solved with #2418 now merged?

**Comment by CendioOssman** [comment] 2022-01-27 12:09
No, I'm afraid #2418 was just for a macOS specific (or rather old pcsc-lite) problem. The issue mentioned here remains unfixed. Tested with ca01aa7a8edc8280a5ceadebb472c2e3c198d8c2.

The workaround I mentioned does work though.

**Comment by Jakuje** [comment] 2022-09-12 08:33
@CendioOssman can you check if #2600 solves the issue for you?

**Closed** 2022-09-30 12:06 UTC
Labels: bug

**Comment by CendioOssman** [comment] 2023-02-24 10:18
Sorry for the delay.

Yes, things appear to work better now with 01ccd42a6624be0127c090631b8f702a8bb70870. I'm unable to find any combination of card/reader insertion or removal that it misses.

Thanks for the fix!
