### ISSUE TITLE
OpenSC 0.15.0 cannot be installed in Mac OS X 10.11

### ISSUE THREAD

**Issue by minkyn** [OpenSC/OpenSC#588] opened 2015-10-20 18:31 UTC
I was using the installer provided at
https://github.com/OpenSC/OpenSC/releases/download/0.15.0/OpenSC-0.15.0.dmg

During installation, it first prompts with an "incompatible" warning, when I selected to continue, it failed and said "contact the software manufacturer for assistance".

Is this a known issue? I saw some commits on fixing bugs for 10.11, but am not sure whether the latest code would work, or when the next available Mac OS X installer would come out.

**Comment by frankmorgner** [comment] 2015-10-24 21:18
It's solved with https://github.com/OpenSC/OpenSC/pull/577 and https://github.com/OpenSC/OpenSC.tokend/pull/18. You're welcome to review the PRs.

**Comment by mouse07410** [comment] 2015-10-25 03:51
Based on my experience with the current OpenSC.tokend on Yosemite - it probably could install on El Capitan, but it would be rather pointless exercise as this tokend just doesn't work. 

On Yosemite it talked fine to the card, but was unable to communicate properly with OSX apps. In presence of at least three tokend apps that do work (PKard.tokend, PIV.tokend from SmartCardServices, PKCS11.tokend from CACKey) I don't see why one would even bother with OpenSC.tokend. I tried to get it working, failed miserably (no help from tokend expert), and gave up. 

At this point I'm happy to use OpenSC libraries (opensc-pkcs11.so, etc) and utilities (piv-tool, pkcs11-tool, etc) that work very well with Java, Firefox and such; and use PKard.tokend to let Safari and Apple Mail talk to my cards. I'm about to remove OpenSC.tokend from my build, as it isn't (and can't be) used.

**Comment by mouse07410** [comment] 2015-10-25 03:53
See issue #570 for details.

**Comment by minkyn** [comment] 2015-10-25 10:32
Could you please release or post a quick Mac installer here?

**Comment by mouse07410** [comment] 2015-10-25 20:51
Sorry, not at the moment. Plus, probably with the update that @frankmorgner pushed, it would be build-able "auto-magically".

My point was - it would **not** be of any use for you (or anybody else) on Mac OS X above 10.8 because it does not even unlock the cards. I personally tested in on 10.9 and 10.10, with 100% negative results.

**Comment by frankmorgner** [comment] 2015-10-26 10:52
Problems with locking on OSX have been solved with #516 (already merged). If I understood correctly #570 is a problem that's limited to your card driver (PIV).

I successfully tested #577 and OpenSC/OpenSC.tokend#18 with CardOS 4.3. It is compatible with OS X 10.10+.

**Comment by mouse07410** [comment] 2015-10-26 21:35
> Problems with locking on OSX have been solved with #516 (already merged). 

Sorry, **wrong**. I have two cards - DoD CAC and Yubikey NEO. The current (pulled a few minutes ago) from Github OpenSC.tokend **can not** unlock either one of these cards.

Also, #516 seems to be about **re**-locking. My complaint is about OpenSC.tokend inability to **un**lock the card at all.

Now, if you mean that OpenSC **tools** can unlock the cards - I completely agree, and use it a lot.

In #516 you mentioned that you tested tokend on 10.11 - could you please share with me exactly what you tried, with what cards, and what was the evidence that it worked? I'm trying to replicate your success (without luck so far).

> If I understood correctly #570 is a problem that's limited to your card driver (PIV).

That is possible - I have no cards other than either PIV- or CAC-conformant (or both :). So it may be that this tokend really works for cards other than CAC and PIV... I'd be very surprised if that is the case, but what can I say...

**Comment by dengert** [comment] 2015-10-27 00:49
I don't thing the problem is in the driver, as the opensc-debug.log showed the card did the
crypto operations as requested.  But the NEO also has OpenPGP.  You have to modify opensc.conf to only select the openpgp driver. 

I have not tried openpgp on any system, so don't expect any help from me getting openspgp runnig.
I think the problem is in the multiple tokend packages you have on your machine.

**Comment by mouse07410** [comment] 2015-10-27 02:19
> I don't thing the problem is in the driver, as the opensc-debug.log showed the card
> did the crypto operations as requested. 

I agree, and stated the same myself recently in a different thread. The problem seems to be in the way OpenSC.tokend communicates with the OS X and its applications, not with how OpenSC.tokend communicates with a card.

> But the NEO also has OpenPGP. You have to modify opensc.conf to only select the openpgp driver.

You meant - to only select the PIV driver, right? Because getting NEO to use OpenPGP keys and operations is a whole different story. Anyway, I have two config files: opensc.conf for PIV, and openpgp-opensc.conf for OpenPGP (which I now use rarely, but probably will use more once the PIV debugging dust settles).

> I have not tried openpgp on any system, so don't expect any help from me getting
> openpgp running.

I have successfully used NEO OpenPGP applet on OS X  with Thunderbird and Enigmail/GnuPG, and via NFC with Android smartphones (OpenKeychain, and K-9 email client). 

But I don't understand how OpenPGP subject got into this conversation. It is leading us astray from our discussion about why OpenSC.tokend seems unable to communicate to OS X that it successfully performed an operation on a PIV or a CAC card, and thus how it is pointless to install OpenSC.tokend if you need either CAC or PIV functionality. 

_I know there are other cards - presumably neither CAC nor PIV - and it might be that this tokend works fine with them. But I tend to doubt this, because the problem seems to be not in how this tokend talks to the card, but how it reports its results to the OS._

> I think the problem is in the multiple tokend packages you have on your machine.

I respectfully disagree. Because if those tokend packages are not residing in `/Library/Security/tokend` or in `/System/Library/Security/tokend` - then from the OS prospective they don't exist, like an application that is not installed. And I never put more than one tokend in one of those directories (where it would be found by the system and used).

**Comment by dengert** [comment] 2015-10-27 13:17
I brought up OpenPGP because...

There are very few developers on this list.

The problem is on MacOS Yosemite.

The problem only occurs with tokend.

The problem has only been demonstrated with PIV or NEO.

The intersection of all of the above: a developer, with MacOS Yosemite, who understands tokend, and has a PIV
maybe zero.

(I don't have MacOS or understand tokend. I have gone as far as I can looking at the debug output
using the PIV.)

To get this solved requires some interest from other developers who can do some testing.
Showing that it also fails with another driver such as OpenPGP could bring more interest to the problem.
You need to show how to reproduce the problem. The intersection above needs to be more then zero.

Terminology used in a problem report can also influence interest. For example,
the use of "unlock the card". An OpenSC developer would immediately start looking at the sc_unlock()
and PC/SC issues.  Referring to the card as CAC, turned off all the developers, including me at first, because
OpenSC does not support CAC, but does support PIV. They are not the same.

To get more interest will most likely require you to trace tokend, to show how it calls OpenSC
and that OpenSC part worked, but the tokend did not unlock the keyring (is that the correct MacOS terminology?)
If you can do this, the intersection of the above will be ONE, with YOU as the developer who understands tokend.


On 10/26/2015 9:19 PM, Mouse wrote:
>     I don't thing the problem is in the driver, as the opensc-debug.log showed the card
>     did the crypto operations as requested.
>
> I agree, and stated the same myself recently in a different thread. The problem seems to be in the way OpenSC.tokend communicates with the OS X and its applications, not with how OpenSC.tokend
> communicates with a card.
>
>     But the NEO also has OpenPGP. You have to modify opensc.conf to only select the openpgp driver.
>
> You meant - to only select the PIV driver, right? Because getting NEO to use OpenPGP keys and operations is a whole different story. Anyway, I have two config files: opensc.conf for PIV, and
> openpgp-opensc.conf for OpenPGP (which I now use rarely, but probably will use more once the PIV debugging dust settles).
>
>     I have not tried openpgp on any system, so don't expect any help from me getting
>     openpgp running.
>
> I have successfully used NEO OpenPGP applet on OS X with Thunderbird and Enigmail/GnuPG, and via NFC with Android smartphones (OpenKeychain, and K-9 email client).
>
> But I don't understand how OpenPGP subject got into this conversation. It is leading us astray from our discussion about why OpenSC.tokend seems unable to communicate to OS X that it successfully
> performed an operation on a PIV or a CAC card, and thus how it is pointless to install OpenSC.tokend if you need either CAC or PIV functionality.
>
> /I know there are other cards - presumably neither CAC nor PIV - and it might be that this tokend works fine with them. But I tend to doubt this, because the problem seems to be not in how this tokend
> talks to the card, but how it reports its results to the OS./
>
>     I think the problem is in the multiple tokend packages you have on your machine.
>
> I respectfully disagree. Because if those tokend packages are not residing in |/Library/Security/tokend| or in |/System/Library/Security/tokend| - then from the OS prospective they don't exist, like
> an application that is not installed. And I never put more than one tokend in one of those directories (where it would be found by the system and used).
>
> —
> Reply to this email directly or view it on GitHub <https://github.com/OpenSC/OpenSC/issues/588#issuecomment-151345281>.
>

-- 

  Douglas E. Engert  <DEEngert@gmail.com>

**Comment by mouse07410** [comment] 2015-10-27 17:39
> There are very few developers on this list.

:-(

> The problem is on MacOS Yosemite.

More precisely, the problem is on Mac OS X, first detected on Snow Leopard, persisting through the subsequent versions.

> The problem only occurs with tokend.

Yes.

> The problem has only been demonstrated with PIV or NEO.

This I don't understand. The problem doesn't seem to be specific to how the tokend talks to the card (which seems fine, based on the logs we both viewed), but with how the tokend communicates with calling applications - and that shouldn't differ based on the card type or driver?

Are you saying that others use `OpenSC.tokend` successfully on Mac OS X Yosemite (or close versions up or down), at least with cards other than PIV?

> To get more interest will most likely require you to trace tokend, to show how it calls OpenSC
> and that OpenSC part worked, but the tokend did not unlock the keyring (is that the correct
> MacOS terminology?)

Yes, the symptoms appear that the physical card is unlocked (it returned `90  00` to the PIN-unlock request), but somehow whatever application or component requested this unlock through tokend, did not get this info passed back to it.

I think that indeed we need to trace tokend, but in addition to how it calls OpenSC we need to see how it is called, and what it returns back.

Is there anybody who can help with this? **It is not a Yosemite-specific** (I think - because I've seen it on other OS X versions), **or PIV-specific task/problem. But it is very much tokend-specific** (because OpenSC appears to work fine, on Yosemite and on other OS X versions).

1. How do I isolate and track traffic between tokend and whatever uses its services?
2. How do I isolate and track tokend's invocations of OpenSC (library?) and what OpenSC returns to it?

> If you can do this, the intersection of the above will be ONE, with YOU as the developer
> who understands tokend.

:-(

If I knew how tokend worked, and knew how to trace it - I'd have (probably) already fixed this (or reported a bug to Apple, with those traces as evidence and a pointer at a problem location if it appears outside of tokend), rather than waiting on others like @martinpaljak to help...

**Comment by frankmorgner** [comment] 2015-10-28 20:42
@mouse07410 I tested my setup from above https://github.com/OpenSC/OpenSC/issues/588#issuecomment-151098560 with client authentication in Safari.

I think we should continue the more specific discussion regarding PIV in https://github.com/OpenSC/OpenSC/issues/570

**Comment by mouse07410** [comment] 2015-10-28 20:51
@frankmorgner, thank you for this info - but I'd appreciate a bit more.

What we know form you:
* OpenSC.tokend worked on OS X.
* OpenSC.tokend managed to communicate to Safari.

What we (wel, I :) _do not_ know yet:
* What hardware token was used?
* How (and why) is OpenSC.tokend treating this working token differently from a PIV token?

As I said, my confusion stems from the fact that the logs show successful interaction of OpenSC.tokend with the PIV token itself, so I don't know if I can possibly blame the PIV driver...

If you think it would be better - I'd be happy to move this discussion to #570.

**Comment by frankmorgner** [comment] 2015-10-28 21:12
As detailed above I used a smartcard with CardOS 4.3.

I don't know what the difference to your setup or token is exactly. To be honest, I don't even have much insights about tokend's workflows. I just fixed what hindered my card from working, that's all. I stopped investigating when it worked as expected.

Yes, I think the general tokend part is solved. We should continue the rest in #570.

**Comment by dengert** [comment] 2015-10-28 21:32
https://github.com/mouse07410 

A way around deciding if this is a PIV specific issue is to use your NEO  with OpenPGP. If the OpenPGP driver does not work it would point to your setup. If OpenPGP  does work, the problem could by with some other tokend getting in the way of a PIV card 

Or your setup could have a certificate issue or verify issue. What is in the key chain? I thought you have to do some mapping between the card (or certificates on the card) and the MacOS account. 
Are there issues with the OpenSC tokend and mapping? 

I still thing it is a setup issue,or interference with some other tokend.

**Comment by mouse07410** [comment] 2015-10-29 04:23
> the problem could by with some other tokend getting in the way of a PIV card

@dengert there is no other tokend. And if it were - why it doesn't get in the way of pretty much every other tokend that work correctly? Like PIV.tokend, PKCS11.tokend, PKard.tokend? I tried each of those (removing everything else and rebooting, just to be sure), and they worked. OpenSC.tokend is the only one that doesn't, at this time.

If I kill tokend, I can use GnuPG to access OpenPGP applet and perform relevant operations.

> Or your setup could have a certificate issue or verify issue. 

Such as...? And why would this issue not impact any other tokend? Why would Keychain Access and MS Outlook have no problem doing what they're supposed to when any other tokend is installed and running, but refuse to work with the token when OpenSC.tokend is the one there?

> What is in the key chain? 

Which one? The smart card keychain shows 4 certificates and 4 private keys (like it should).

The login keychain holds a bunch of other certs, including CA certs.

> I thought you have to do some mapping between the card (or certificates on the card) and the MacOS account. 

None to the best of my knowledge, except that email address in the cert should match the email address of the account that's sending signed email (SAN attribute). I'm trying to also keep CN matching.

> Are there issues with the OpenSC tokend and mapping?

I'm not aware of any. So far OpenSC.tokend cannot even properly unlock the token, let alone actually use the certificates on it.

Let's do as @frankmorgner suggests and move to #570 .

**Comment by frankmorgner** [comment] 2015-11-26 20:28
OpenSC and OpenSC.tokend now support 10.11

**Closed by frankmorgner** 2015-11-26 20:28 UTC
