### ISSUE TITLE
Cardos5 not working in 0.20.0

### ISSUE THREAD

**Issue by bigon** [OpenSC/OpenSC#1941] opened 2020-02-11 13:05 UTC
Hello,

With 0.20.0 I cannot use my cardos5 (5.3v2 according to the label on it) to login on websites

After some investigations it seems that the patch used to fix #1864 is the cause. If I revert the patch everything is working fine again. Surprisingly I'm not impacted by that bug.

**Comment by bigon** [comment] 2020-02-11 13:09
If I'm trying to sign something with the `RSA-X-509` mechanism with 642a3ee73411761c03a5480484be4d51b087f304:

$ ./src/tools/pkcs11-tool --module ./src/pkcs11/.libs/onepin-opensc-pkcs11.so  --login -s -m RSA-X-509
Using slot 0 with a present token (0x0)
Logging in to "Atos PKI + OTP Card  V5.3(016)".
Please enter User PIN: 
Using signature algorithm RSA-X-509
dsqfds
error: PKCS11 function C_SignInit failed: rv = CKR_MECHANISM_INVALID (0x70)
Aborting.
```

**Comment by bigon** [comment] 2020-02-11 13:13
ATR of my card is: `3b:d2:18:00:81:31:fe:58:c9:02:17`

**Comment by frankmorgner** [comment] 2020-02-11 17:04
duplicate of #1918

**Comment by frankmorgner** [comment] 2020-02-11 17:04
tracked in #1916

**Closed by frankmorgner** 2020-02-11 17:04 UTC
