### ISSUE TITLE
Ignore a key's mechanism specification (PKCS#15 PRKDF) to make the key functional in OpenSC

### ISSUE THREAD

**Issue by lmiguelmh** [OpenSC/OpenSC#1194] opened 2017-11-09 22:53 UTC
### Problem Description

Hello again. I am _trying_ to solve the issues https://github.com/OpenSC/OpenSC/issues/1031 and https://github.com/OpenSC/OpenSC/issues/1147 so any help would be greatly appreciated.

As @dengert suggested the problem *does* occur in the method `pkcs15_prkey_can_do` which fails to find the given algorithm (or mechanism). At first I thought the problem was because this card supports 11 mechanisms and _OpenSC only supports 8_. I changed the constant `SC_MAX_SUPPORTED_ALGORITHMS` to 16 and made the respective changes to files: `pkcs15.c`, `pkcs15-skey.c` and `pkcs15-prkey.c`. The problem persists:

```
2017-11-09 10:49:43.641 [opensc-pkcs11] mechanism.c:250:sc_pkcs11_sign_init: called
2017-11-09 10:49:43.642 mechanism 0x6, key-type 0x0
2017-11-09 10:49:43.643 [opensc-pkcs11] misc.c:258:session_start_operation: called
2017-11-09 10:49:43.643 Session 0xbdf18290, type 1
2017-11-09 10:49:43.644 [opensc-pkcs11] mechanism.c:367:sc_pkcs11_signature_init: called
2017-11-09 10:49:43.645 [opensc-pkcs11] mechanism.c:386:sc_pkcs11_signature_init: returning with: 112
2017-11-09 10:49:43.646 [opensc-pkcs11] mechanism.c:274:sc_pkcs11_sign_init: returning with: 112
2017-11-09 10:49:43.647 C_SignInit() = CKR_MECHANISM_INVALID
```
The weird thing is that this same mechanism is registered with a call to the method `sc_pkcs11_register_mechanism` in https://github.com/OpenSC/OpenSC/blob/e2fe24d56ac4a90bf140c670ebea02dee6a599d6/src/pkcs11/mechanism.c#L50 (I added these logs):
```
2017-11-09 14:06:13.199 Registering CKM_SHA1_RSA_PKCS mechanisms:
2017-11-09 14:06:13.201 Registering new mechanism (mech=0x6, key_type=0x0, mech_info.flags=0x2800)
```

### Proposed Resolution

The problem is in the method `pkcs15_prkey_can_do` in https://github.com/OpenSC/OpenSC/blob/4d5b73d8690775212e1c9df1bf09a058b245c058/src/pkcs11/framework-pkcs15.c#L3923
And it looks like only one mechanisms is supported because `!pkinfo->algo_refs[ii]` passes
https://github.com/OpenSC/OpenSC/blob/4d5b73d8690775212e1c9df1bf09a058b245c058/src/pkcs11/framework-pkcs15.c#L3964-L3965

This method is called from method `sc_pkcs11_signature_init` in https://github.com/OpenSC/OpenSC/blob/e2fe24d56ac4a90bf140c670ebea02dee6a599d6/src/pkcs11/mechanism.c#L374

The last time `key` is updated is in the method `C_SignInit` in https://github.com/OpenSC/OpenSC/blob/428b134776aaeeecd84a15f6b89000b695babc0b/src/pkcs11/pkcs11-object.c#L627

Maybe there is a problem with the way the key is retrieved, notice the casting from `sc_pkcs11_object` to `pkcs15_prkey_object`?

### Steps to reproduce

1. Execute the next command:

```
C:\Program Files\OpenSC Project\OpenSC\tools>pkcs11-tool.exe --module "C:\Program Files\OpenSC Project\OpenSC\pkcs11\opensc-pkcs11.dll" -v -s -m SHA1-RSA-PKCS --id 02 --slot 1 --pin 112233 -i test.txt -o test.signed.txt
Using slot with ID 0x1
Using signature algorithm SHA1-RSA-PKCS
error: PKCS11 function C_SignInit failed: rv = CKR_MECHANISM_INVALID (0x70)
Aborting.
```

### Logs

I can generate logs.

**Comment by frankmorgner** [comment] 2017-11-10 12:13
In you PKCS#15 profile it seems that some mechanisms are specified for your key (read: the card menufacturer did this for you). Otherwise you would have hit a different return code.
https://github.com/OpenSC/OpenSC/blob/4d5b73d8690775212e1c9df1bf09a058b245c058/src/pkcs11/framework-pkcs15.c#L3938-L3939
Could you check your debug output, if it contains a parsed `algorithmReference`?

**Comment by frankmorgner** [comment] 2017-11-10 12:27
Indeed, your previous log from #1031 [shows the following](https://gist.github.com/lmiguelmh/1845c59b145db3e7d8bf0c5f977acf11#file-gistfile1-txt-L1294-L1302):
```
2017-04-19 11:19:09.170 Looking for 'keyReference', tag 0x2, OPTIONAL
2017-04-19 11:19:09.172   decoding 'keyReference'
2017-04-19 11:19:09.175   decoding 'keyReference' returned 129
2017-04-19 11:19:09.177 Looking for 'algReference', tag 0x21000001, OPTIONAL
2017-04-19 11:19:09.180   decoding 'algReference'
2017-04-19 11:19:09.182    called, left=3, depth 3
2017-04-19 11:19:09.185 Looking for 'algorithmReference', tag 0x2, OPTIONAL
2017-04-19 11:19:09.188    decoding 'algorithmReference'
2017-04-19 11:19:09.190 decoding 'algorithmReference' returned 5
```
This means that *your card's profile* limits the possible mechanisms to one specific algorithm. Please check which mechanism is specified in the profile. If you don't know how to do that, dump EF.TokenInfo (path `3f0050155032`) with opensc-explorer and post the dump here.

**Comment by lmiguelmh** [comment] 2017-11-10 16:02
@frankmorgner thanks for your response!
I put the result of the commands.
```
C:\Program Files\OpenSC Project\OpenSC\tools>opensc-explorer.exe -v -m 3F00
OpenSC Explorer version 0.17.0
Using reader with a card: Gemplus USB Smart Card Reader 0
OpenSC [3F00]> cd 5015
OpenSC [3F00/5015]> cat 7005
00000000: 30 5A 30 46 0C 1E 52 45 4E 49 45 43 20 43 65 72 0Z0F..RENIEC Cer
00000010: 74 69 66 69 63 61 74 69 6F 6E 20 41 75 74 68 6F tification Autho
00000020: 72 69 74 79 03 02 06 40 30 20 30 06 03 02 07 80 rity...@0 0.....
00000030: 05 00 30 0A 03 02 06 40 30 04 03 02 05 20 30 0A ..0....@0.... 0.
00000040: 03 02 04 10 30 04 03 02 05 20 30 06 04 01 55 01 ....0.... 0...U.
00000050: 01 FF A1 08 30 06 30 04 04 02 34 07 30 4E 30 3A ....0.0...4.0N0:
00000060: 0C 12 52 45 4E 49 45 43 20 43 6C 61 73 73 20 49 ..RENIEC Class I
00000070: 49 20 43 41 03 02 06 40 30 20 30 06 03 02 07 80 I CA...@0 0.....
00000080: 05 00 30 0A 03 02 06 40 30 04 03 02 05 20 30 0A ..0....@0.... 0.
00000090: 03 02 04 10 30 04 03 02 05 20 30 06 04 01 56 01 ....0.... 0...V.
000000A0: 01 FF A1 08 30 06 30 04 04 02 34 08 30 61 30 50 ....0.0...4.0a0P
000000B0: 0C 28 4D 41 4D 41 4E 49 20 48 55 4D 50 49 52 49 .(MAMANI HUMPIRI
000000C0: 20 4C 75 69 73 20 4D 69 67 75 65 6C 20 28 41 55  Luis Miguel (AU
000000D0: 54 34 33 38 37 33 32 32 33 29 03 02 06 40 30 20 T43873223)...@0
000000E0: 30 06 03 02 07 80 05 00 30 0A 03 02 06 40 30 04 0.......0....@0.
000000F0: 03 02 05 20 30 0A 03 02 04 10 30 04 03 02 05 20 ... 0.....0....
00000100: 30 03 04 01 01 A1 08 30 06 30 04 04 02 34 01 30 0......0.0...4.0
00000110: 61 30 50 0C 28 4D 41 4D 41 4E 49 20 48 55 4D 50 a0P.(MAMANI HUMP
00000120: 49 52 49 20 4C 75 69 73 20 4D 69 67 75 65 6C 20 IRI Luis Miguel
00000130: 28 46 49 52 34 33 38 37 33 32 32 33 29 03 02 06 (FIR43873223)...
00000140: 40 30 20 30 06 03 02 07 80 05 00 30 0A 03 02 06 @0 0.......0....
00000150: 40 30 04 03 02 05 20 30 0A 03 02 04 10 30 04 03 @0.... 0.....0..
00000160: 02 05 20 30 03 04 01 02 A1 08 30 06 30 04 04 02 .. 0......0.0...
00000170: 34 02                                           4.
OpenSC [3F00/5015]> exit
```
It is important to say that I struggled a little bit with `opensc-explorer`. You have to write the *exact commands*, if you put something like `help` or other `command`, `cd` wont work (but that is a thing for another talk).

**Comment by lmiguelmh** [comment] 2017-11-10 16:40
Using lapo's ASN decoder https://goo.gl/N7bAHj I think this is the content for the algorithm with id=6:

```
SEQUENCE(6 elem)
  INTEGER 6
  INTEGER 6
  NULL
  BIT STRING (2 bit) 01
  OBJECT IDENTIFIER 1.2.840.113549.1.1.5 sha1WithRSAEncryption (PKCS #1)
  INTEGER 18
```

**Comment by lmiguelmh** [comment] 2017-11-10 17:38
I didn't notice until now but `opensc-explorer` tool *has* an ASN.1 decoder, this are the contents. I put the contents for the algorithm with id = 6.

```
    30 Univ: tag 0x10, length  26: SEQUENCE
      02 Univ: tag 0x02, length   1: INTEGER [6]
      02 Univ: tag 0x02, length   1: INTEGER [6]
      05 Univ: tag 0x05, length   0: NULL []
      03 Univ: tag 0x03, length   2: BIT STRING [10]
      06 Univ: tag 0x06, length   9: OBJECT [1.2.840.113549.1.1.5]
      02 Univ: tag 0x02, length   1: INTEGER [18]
```

The full dump is here: https://gist.github.com/lmiguelmh/f60acc8da8e26e8d3eff78dc67f93525#file-gistfile1-txt

**Comment by frankmorgner** [comment] 2017-11-13 21:31
your log says that the application wants to do `RSA_PKCS` (mechanism 1):
```
2017-04-19 11:19:41.841 [opensc-pkcs11] mechanism.c:236:sc_pkcs11_sign_init: called
2017-04-19 11:19:41.843 mechanism 0x1, key-type 0x0
2017-04-19 11:19:41.845 [opensc-pkcs11] misc.c:254:session_start_operation: called
2017-04-19 11:19:41.848 Session 0xdad0e40, type 1
2017-04-19 11:19:41.850 [opensc-pkcs11] mechanism.c:352:sc_pkcs11_signature_init: called
2017-04-19 11:19:41.853 [opensc-pkcs11] mechanism.c:371:sc_pkcs11_signature_init: returning with: 112
2017-04-19 11:19:41.855 [opensc-pkcs11] mechanism.c:259:sc_pkcs11_sign_init: returning with: 112
2017-04-19 11:19:41.858 C_SignInit() = CKR_MECHANISM_INVALID
```
So you need to look at `1.2.840.113549.1.1.1`; for the signature (`BIT STRING [10]`), which leaves a single entry:
```
...
    30 Univ: tag 0x10, length  26: SEQUENCE
      02 Univ: tag 0x02, length   1: INTEGER [8]
      02 Univ: tag 0x02, length   1: INTEGER [1]
      05 Univ: tag 0x05, length   0: NULL []
      03 Univ: tag 0x03, length   2: BIT STRING [10]
      06 Univ: tag 0x06, length   9: OBJECT [1.2.840.113549.1.1.1]
      02 Univ: tag 0x02, length   1: INTEGER [2]
...
```
Now, you need to match the card's algorithm reference (`INTEGER [8]`) against the key's algorithmReference from `3f0050157002`. Could it be that you have multiple keys and the one the application wants to use simply isn't meant for signing?

**Comment by lmiguelmh** [comment] 2017-11-14 16:04
@frankmorgner thanks for taking the time.

I decided to disable temporarily the verification of the mechanism commenting this code:
https://github.com/OpenSC/OpenSC/blob/4d5b73d8690775212e1c9df1bf09a058b245c058/src/pkcs11/mechanism.c#L373-L388

And all worked as expected (I suppose).

I [uploaded the full log](https://gist.github.com/lmiguelmh/17a59e0ec4490122c182cf841cdf382f) for `pkcs11-tool.exe --module "C:\Program Files\OpenSC Project\OpenSC\pkcs11\opensc-pkcs11.dll" -s -m SHA256-RSA-PKCS --id 02 --slot 1 --pin 112233 -i test.txt -o test.signed.txt` here. The log show operations for: (_test.txt has the text "lmiguelmh"_)
1. Verification of the PIN.
2. Setting the security environment:
```
Outgoing APDU (11 bytes):
00 22 41 B6 06 80 01 11 83 01 02 ."A........
Incoming APDU (2 bytes):
90 00 ..
```
3. Performing the security operation:
```
Outgoing APDU (38 bytes):
00 2A 9E 9A 20 22 80 AA 89 0A 5B 0E 6E 06 CE DB .*.. "....[.n...
39 0A 86 5D CA 38 92 B2 53 A7 92 E3 2C 58 F6 54 9..].8..S...,X.T
2A BD C4 DD 39 00                               *...9.
Incoming APDU (258 bytes):
A4 B6 FF 2D DC E2 DE 8A 08 2A 5F 2A A9 A0 CB 6C ...-.....*_*...l
11 8C 31 DC F6 59 25 B3 39 64 8D 17 0C 42 22 24 ..1..Y%.9d...B"$
24 7B 7F DE 1A 43 87 47 DC 6F F0 67 EF 6F C6 CA ${...C.G.o.g.o..
B6 78 AC C3 D1 AD 67 9D C8 31 83 07 23 88 53 45 .x....g..1..#.SE
E2 94 53 E7 65 21 89 4E 1F AB 61 92 BC 76 FC 46 ..S.e!.N..a..v.F
F8 5F 15 CA 08 9C A6 27 DF 67 E4 B1 A1 FD 33 12 ._.....'.g....3.
F7 0C 89 08 24 EC 94 99 25 93 4B B0 76 F6 B9 96 ....$...%.K.v...
F3 EA 88 7E 18 BE 7B 21 8B AC A7 A3 D5 35 87 EC ...~..{!.....5..
BD 39 02 18 92 DC B6 99 FF 7D 4A B0 D4 A6 BF 61 .9.......}J....a
CE 74 50 D8 A2 44 76 88 47 B2 4C 9F 92 CC 15 FE .tP..Dv.G.L.....
9A A6 7D FB DF C1 9D 9E 5B 3B F7 49 EF 7D 66 49 ..}.....[;.I.}fI
D5 01 4C 57 5E 02 0F 1D CD 1B 00 21 C5 B0 04 60 ..LW^......!...`
59 3D E7 B4 95 7B 32 BC 42 98 02 34 9D 74 E6 9D Y=...{2.B..4.t..
7C 75 1D 17 F7 9C DD 36 D2 D1 0E 78 02 24 B4 48 |u.....6...x.$.H
E3 2F F0 42 61 79 C1 30 B4 70 6A B4 B0 9D A2 09 ./.Bay.0.pj.....
E2 8D E8 54 CD 0D 3D 73 02 C6 8E 7E B1 F3 BD 73 ...T..=s...~...s
90 00
```
There are other things like sending the HASH as is (without any header). I saw that in other systems they are using a [PKCS1 Digest Info header](https://tools.ietf.org/html/rfc8017#section-9.2):

```
002A9E9A 
33 3031300D0609608648016503040201050004
20 2280AA890A5B0E6E06CEDB390A865DCA3892B253A792E32C58F6542ABDC4DD3900
```
The **weird** thing is that the results are different when using PKCS1 digest info header than doing without it (like OpenSC).

Going back to the initial problem: Could it be a problem in the verification of the mechanism? Or is this related to the smartcard?

**Comment by frankmorgner** [comment] 2017-11-14 20:33
If possible, please dump `3f0050157002`. The thing is that your card manufacturer seems to be forcing some type of mechanism for this key (which OpenSC is respecting). Only by ignoring your manufacturer's metadata you're making your token functional. This may be good since, hey, *it works*, but there may have been a good reason for limiting the use of the card. For example, your manufacturer may want to enforce a secure signature scheme...

Anyway, since you don't seem to be the only one with that problem, we could add a configuration option to disable the default behavior of respecting the key's mechanism specification...

**Comment by lmiguelmh** [comment] 2017-11-14 21:37
It is **really weird**, but both give different results:


**SHA256-RSA-PKCS - OpenSC mode** _(without PKCS1 Digest Info Header)_
```
pkcs11-tool.exe --module "C:\Program Files\OpenSC Project\OpenSC\pkcs11\opensc-pkcs11.dll" -s -m SHA256-RSA-PKCS --id 02 --slot 1 --pin 112233 -i test.txt -o test.signed.txt

Outgoing APDU (38 bytes):
00 2A 9E 9A 20 22 80 AA 89 0A 5B 0E 6E 06 CE DB .*.. "....[.n...
39 0A 86 5D CA 38 92 B2 53 A7 92 E3 2C 58 F6 54 9..].8..S...,X.T
2A BD C4 DD 39 00                               *...9.

Incoming APDU (258 bytes):
A4 B6 FF 2D DC E2 DE 8A 08 2A 5F 2A A9 A0 CB 6C ...-.....*_*...l
...
```

**SHA256-RSA-PKCS with PKCS1 Digest Info Header**
```
Outgoing APDU:
002A9E9A
33 3031300D0609608648016503040201050004
20 2280AA890A5B0E6E06CEDB390A865DCA3892B253A792E32C58F6542ABDC4DD3900

Incoming APDU:
A4428185D90ED7CC3C267835E62614A0...
```
As you can see both signatures are different!

The same happens when using SHA1-RSA-PKCS (`pkcs11-tool.exe --module "C:\Program Files\OpenSC Project\OpenSC\pkcs11\opensc-pkcs11.dll" -s -m SHA1-RSA-PKCS --id 02 --slot 1 --pin 112233 -i test.txt -o test.signed.txt`). 

The thing get weirder when using RSA-PKCS:
```
pkcs11-tool.exe --module "C:\Program Files\OpenSC Project\OpenSC\pkcs11\opensc-pkcs11.dll" -s -m RSA-PKCS --id 02 --slot 1 --pin 112233 -i test.txt -o test.signed.txt
Outgoing APDU (15 bytes):
00 2A 9E 9A 09 6C 6D 69 67 75 65 6C 6D 68 00 .*...lmiguelmh.
```
I suppose the given text is plain because we don't specified a hashing algorithm.

**Comment by lmiguelmh** [comment] 2017-11-14 21:57
@frankmorgner Thanks again! 
This are the [contents of the EF located in `3f0050157002`](https://gist.github.com/lmiguelmh/77a6b8c51dafa42bdeab8e1c98bc7c15). I was using the key with the label "Clave Privada de Firma Digital" (in English: _Digital Signature Private Key_).
```
OpenSC [3F00/5015]> asn1 7002
Printing tags for buffer of length 234
30 Univ: tag 0x10, length 115: SEQUENCE
  30 Univ: tag 0x10, length  75: SEQUENCE
    0C Univ: tag 0x0C, length  30: UTF8STRING [Clave Privada de Autenticacion]
    03 Univ: tag 0x03, length   2: BIT STRING [11]
    04 Univ: tag 0x04, length   1: OCTET STRING [01]
    30 Univ: tag 0x10, length  34: SEQUENCE
      30 Univ: tag 0x10, length  10: SEQUENCE
        03 Univ: tag 0x03, length   2: BIT STRING [10]
        30 Univ: tag 0x10, length   4: SEQUENCE
          03 Univ: tag 0x03, length   2: BIT STRING [100]
      30 Univ: tag 0x10, length  10: SEQUENCE
        03 Univ: tag 0x03, length   2: BIT STRING [1000]
        30 Univ: tag 0x10, length   4: SEQUENCE
          03 Univ: tag 0x03, length   2: BIT STRING [100]
      30 Univ: tag 0x10, length   8: SEQUENCE
        03 Univ: tag 0x03, length   3: BIT STRING [1000000000]
        04 Univ: tag 0x04, length   1: OCTET STRING [01]
  30 Univ: tag 0x10, length  24: SEQUENCE
    04 Univ: tag 0x04, length   1: OCTET STRING [01]
    03 Univ: tag 0x03, length   3: BIT STRING [1001110111]
    01 Univ: tag 0x01, length   1: BOOLEAN [true]
    03 Univ: tag 0x03, length   2: BIT STRING [1101]
    02 Univ: tag 0x02, length   2: INTEGER [129]
    A1 Cntx: tag 0x01, length   3:
      02 Univ: tag 0x02, length   1: INTEGER [5]
  A1 Cntx: tag 0x01, length  10:
    30 Univ: tag 0x10, length   8: SEQUENCE
      30 Univ: tag 0x10, length   2: SEQUENCE
        04 Univ: tag 0x04, length   0: OCTET STRING []
      02 Univ: tag 0x02, length   2: INTEGER [2048]
30 Univ: tag 0x10, length 115: SEQUENCE
  30 Univ: tag 0x10, length  75: SEQUENCE
    0C Univ: tag 0x0C, length  30: UTF8STRING [Clave Privada de Firma Digital]
    03 Univ: tag 0x03, length   2: BIT STRING [11]
    04 Univ: tag 0x04, length   1: OCTET STRING [04]
    30 Univ: tag 0x10, length  34: SEQUENCE
      30 Univ: tag 0x10, length  10: SEQUENCE
        03 Univ: tag 0x03, length   2: BIT STRING [10]
        30 Univ: tag 0x10, length   4: SEQUENCE
          03 Univ: tag 0x03, length   2: BIT STRING [100]
      30 Univ: tag 0x10, length  10: SEQUENCE
        03 Univ: tag 0x03, length   2: BIT STRING [1000]
        30 Univ: tag 0x10, length   4: SEQUENCE
          03 Univ: tag 0x03, length   2: BIT STRING [100]
      30 Univ: tag 0x10, length   8: SEQUENCE
        03 Univ: tag 0x03, length   3: BIT STRING [1000000000]
        04 Univ: tag 0x04, length   1: OCTET STRING [04]
  30 Univ: tag 0x10, length  24: SEQUENCE
    04 Univ: tag 0x04, length   1: OCTET STRING [02]
    03 Univ: tag 0x03, length   3: BIT STRING [1001110111]
    01 Univ: tag 0x01, length   1: BOOLEAN [true]
    03 Univ: tag 0x03, length   2: BIT STRING [1101]
    02 Univ: tag 0x02, length   2: INTEGER [130]
    A1 Cntx: tag 0x01, length   3:
      02 Univ: tag 0x02, length   1: INTEGER [5]
  A1 Cntx: tag 0x01, length  10:
    30 Univ: tag 0x10, length   8: SEQUENCE
      30 Univ: tag 0x10, length   2: SEQUENCE
        04 Univ: tag 0x04, length   0: OCTET STRING []
      02 Univ: tag 0x02, length   2: INTEGER [2048]
```

**Comment by frankmorgner** [comment] 2017-11-14 23:34
`Clave Privada de Autenticacion` shall be used with `INTEGER [5]`, `Clave Privada de Firma Digital` shall be used with `INTEGER [5]`, which references the following mechanism from EF.TokenInfo, I think:
```
    30 Univ: tag 0x10, length  27: SEQUENCE
      02 Univ: tag 0x02, length   1: INTEGER [5]
      02 Univ: tag 0x02, length   2: INTEGER [597]
      05 Univ: tag 0x05, length   0: NULL []
      03 Univ: tag 0x03, length   2: BIT STRING [1000000]
      06 Univ: tag 0x06, length   9: OBJECT [2.16.840.1.101.3.4.2.3]
      02 Univ: tag 0x02, length   1: INTEGER [5]
```
The above AlgorithmInfo specifies SHA-224 in terms of PKCS#11 (`INTEGER [597]`, which is causing `CKR_MECHANISM_INVALID` on `C_SignInit`) *and* SHA-512 with regard to `OBJECT [2.16.840.1.101.3.4.2.3]`, which is inconsistent and both can *not* be calculated from an RSA key. Either it's too late and I'm completely off, but I think your card manufacturer failed in many ways to personalize your card.

Even ignoring the metadata, there may be more things that are not correctly initialized. I don't think its worth investigating any further. You should talk to your card manufacturer.

**Comment by lmiguelmh** [comment] 2017-11-20 15:34
Thanks again!
For future reference I will try to explain what I _think_ is happening here please feel free to correct me if I am wrong: This are the contents from the EF located in `3F0050157002` which is a _PrKD_ file (a file which contains metadata for private keys) and is a kind of CIO (Cryptographic Information Object).  CIOs are composed of various things: common attributes, class attributes and type attributes.

```
# cio, in this case the key
30 Univ: tag 0x10, length 115: SEQUENCE
  # attributes for the object
  30 Univ: tag 0x10, length  75: SEQUENCE
    # label for key
    0C Univ: tag 0x0C, length  30: UTF8STRING [Clave Privada de Firma Digital]
    # some flags
    03 Univ: tag 0x03, length   2: BIT STRING [11]
    # a reference to the auth object used to protect this key (a PIN in this case)
    04 Univ: tag 0x04, length   1: OCTET STRING [04]
    # sequence of access control rules
    30 Univ: tag 0x10, length  34: SEQUENCE
      ...

  # attributes for the key - This is what I THINK is wrong
  30 Univ: tag 0x10, length  24: SEQUENCE
    # identifier
    04 Univ: tag 0x04, length   1: OCTET STRING [02]
    # usage flags
    03 Univ: tag 0x03, length   3: BIT STRING [1001110111]
    # native
    01 Univ: tag 0x01, length   1: BOOLEAN [true]
    # access flags
    03 Univ: tag 0x03, length   2: BIT STRING [1101]
    # key reference
    02 Univ: tag 0x02, length   2: INTEGER [130]
    # sequence of algorithm references
    A1 Cntx: tag 0x01, length   3:
      # a reference to the algorithm specified in the CIAInfo file (which is wrong!)
      02 Univ: tag 0x02, length   1: INTEGER [5]
  
  # attributes for the type
  A1 Cntx: tag 0x01, length  10:
    30 Univ: tag 0x10, length   8: SEQUENCE
      30 Univ: tag 0x10, length   2: SEQUENCE
        # the path of the file containing the key - empty
        04 Univ: tag 0x04, length   0: OCTET STRING []
      # length of the key
      02 Univ: tag 0x02, length   2: INTEGER [2048]
```
So according the attributes for the key sequence the algorithm referenced is the one with the ID=5 which is wrong because _I suppose_ it should be 6, 7, 8 and/or 9 (RSA encryption). See the contents for the EF `3f0050155032` (CIAInfo file):

```
SEQUENCE (6 elem)
INTEGER 5  # id
INTEGER 597
NULL
BIT STRING (7 bit) 0000001
OBJECT IDENTIFIER 2.16.840.1.101.3.4.2.3 sha-512 (NIST Algorithm) 
INTEGER 5

SEQUENCE (6 elem)
INTEGER 6
INTEGER 6
NULL
BIT STRING (2 bit) 01
OBJECT IDENTIFIER 1.2.840.113549.1.1.5 sha1WithRSAEncryption (PKCS #1)
INTEGER 18

SEQUENCE (6 elem)
INTEGER 7
INTEGER 64
NULL
BIT STRING (2 bit) 01
OBJECT IDENTIFIER 1.2.840.113549.1.1.11 sha256WithRSAEncryption (PKCS #1)
INTEGER 66

SEQUENCE (6 elem)
INTEGER 8
INTEGER 1
NULL
BIT STRING (2 bit) 01
OBJECT IDENTIFIER 1.2.840.113549.1.1.1 rsaEncryption (PKCS #1)
INTEGER 2

SEQUENCE (6 elem)
INTEGER 9
INTEGER 1
NULL
BIT STRING (6 bit) 000001
OBJECT IDENTIFIER 1.2.840.113549.1.1.1 rsaEncryption (PKCS #1)
INTEGER 26
```

@frankmorgner Could you tell me if there are other things wrong please apart from this?

**Comment by frankmorgner** [comment] 2017-11-20 20:18
See above, the OID doesn't match the PKCS#11 mechanism.

The issue is fixed by correcting the card's metadata. There is no need to change OpenSC.

**Closed by frankmorgner** 2017-11-20 20:18 UTC
Labels: Enhancement, help wanted

**Comment by lmiguelmh** [comment] 2019-03-26 21:59
Only to confirm that the problem is fixed.
Thank you Frank for your help!
