### ISSUE TITLE
Build failed OpenSC-0.17.0-rc2

### ISSUE THREAD

**Issue by hamano** [OpenSC/OpenSC#1098] opened 2017-07-14 01:32 UTC
### Expected behaviour

configure must fail if help2man doesn't installed and generate npa-tool.1 at build time.
I propose to include the npa-tool.1 in the source archive.

### Actual behaviour

Passed configure and failed at make.

### Steps to reproduce

~~~
$ cat /etc/debian_version
9.0
$ dpkg -l help2man
dpkg-query: no packages found matching help2man
$ wget https://github.com/OpenSC/OpenSC/releases/download/0.17.0-rc2/opensc-0.17.0.tar.gz
$ tar xf opensc-0.17.0.tar.gz
$ cd opensc-0.17.0
$ ./configure
(snip)
checking for help2man... not found
(snip)
$ make
(snip)
make[4]: Entering directory '/home/hamano/opensc-0.17.0/src/tools'
make[4]: 'npa-tool' is up to date.
make[4]: Leaving directory '/home/hamano/opensc-0.17.0/src/tools'
not found \
        --output=npa-tool.1 \
        --no-info \
        --source='OpenSC 0.17.0' \
        ./npa-tool
/bin/bash: not: command not found
Makefile:1189: recipe for target 'npa-tool.1' failed
make[3]: *** [npa-tool.1] Error 127
(snip)
~~~

**Comment by frankmorgner** [comment] 2017-07-14 05:19
duplicate of https://github.com/OpenSC/OpenSC/issues/1093

**Closed by frankmorgner** 2017-07-14 05:19 UTC
