### ISSUE TITLE
Cannot sign message with ECC P384 using OpenPGP v3.3

### ISSUE THREAD

**Issue by szszszsz** [OpenSC/OpenSC#1982] opened 2020-03-14 16:15 UTC
### Problem Description
It is not possible to sign a message with ECC P384 key using OpenPGP v3.3 card. `CKR_FUNCTION_NOT_SUPPORTED` error message is shown on an attempt.

A customer wanted to use `pkcs11-tool` to make a simple ECDSA signature over a challenge, using an OpenPGP v3.3 based device. In case it is possible to realize it in another way please let me know.

Details: 
- https://support.nitrokey.com/t/sign-message-using-nitrokey-storage-2/2285

Possibly connected:
- #1960
- https://github.com/OpenSC/OpenSC/issues/1854

### Proposed Resolution
To add required implementation for P384 or P256.

### Steps to reproduce
- OpenSC version: https://github.com/OpenSC/OpenSC/commit/dc29b0fe18108f34cac5f2f7d5e5006b189f193c / current master (v0.20+);
- Tested against PR #1960 / 7422aa792870835eba31f80e6414f65d87c09056 as well;
- Nitrokey Pro 2 with OpenPGP v3.3;

1. Create keys on smart card with GnuPG, P384 (creating ECC keys with `pkcs11-tool` is not supported, as the tool reports).
2. Try to sign some data with `pkcs11-tool`:
```bash
$ pkcs11-tool --sign --id 01 -m ECDSA  --signature-format rs  --pin 123456 --input-file test.input --output-file pkcstest --slot 1
Using signature algorithm ECDSA
error: PKCS11 function C_SignFinal failed: rv = CKR_FUNCTION_NOT_SUPPORTED (0x54)
Aborting.

```

### Logs
- [sign-debug3.log](https://github.com/OpenSC/OpenSC/files/4332955/sign-debug3.log)
- [sign-debug9.log](https://github.com/OpenSC/OpenSC/files/4332956/sign-debug9.log)

PR1960:
- [debug-pr1960-9.log](https://github.com/OpenSC/OpenSC/files/4332983/debug-pr1960.log)
- [debug-pr1960-3.log](https://github.com/OpenSC/OpenSC/files/4332984/debug-pr1960-3.log)

```
error: PKCS11 function C_SignFinal failed: rv = CKR_FUNCTION_NOT_SUPPORTED (0x54)
```

### Other

> Please read about [reporting bugs](https://github.com/OpenSC/OpenSC/wiki/How-to-report-bugs-so-that-they-can-be-fixed) before opening an issue.

The link from the bug reporting template seems to not work currently.

**Comment by dengert** [comment] 2020-03-14 23:14
#1960 looks like it gets a lot further. But in `pkcs15-openpgp.c` It does not set  `prkey_info.field_length` for SC_OPENPGP_KEYALGO_ECDH or SC_OPENPGP_KEYALGO_ECDSA accept for `curve25519_binary_oid` in line 331. 

The comments `/* TODO Store the OID from cxdata + 1 ?? */`  need to take the OID  from cxdata + 1 and find the OID in `ec_curves`,  and set field_length = size. 

The debug logs show:
`pkcs15-sec.c:219:format_senv: Card does not support EC with field_size 0`  line 217 
` *alg_info_out = sc_card_find_ec_alg(p15card->card, prkey->field_length, NULL);` fails because prkey->field_length is zero.

**Comment by szszszsz** [comment] 2020-03-18 15:50
cc: @alex-nitrokey @jans23

**Comment by dengert** [comment] 2020-03-18 18:03
I am working on this today with mods to pkcs15-openpgp.c based on @Jakuje eddsa branch #1960  using the Nitrokey Pro Alex sent me.

**Comment by Jakuje** [comment] 2020-03-18 19:25
@dengert Thanks. After the previous openpgp ecc related changes were merged, I believe it will not be too complicated to figure out the issue. The #1960 adds also a lot of debugging messages so I hope you will find them useful. The Nitrokey start has Gnuk, which does not support these curves so I can not help more than checking logs.

From my quick review, it looks like the object are properly created with all the needed attributes, but it looks like the size is getting lost somewhere in the process for this key type.

**Comment by dengert** [comment] 2020-03-18 19:40
I have a fix for size.

**Comment by dengert** [comment] 2020-03-19 02:36
I have pushed a commit: https://github.com/OpenSC/OpenSC/pull/1960/commits/baa9f0021d3fccda1938f7b51e01ffc46fc34d7d onto Jakuje:eddsa     PR #1960  

Using a Nitrokey Pro with nistp384 Sign key with:
`pkcs11-tool --sign --id 01 -m ECDSA  --signature-format rs  --pin 123456  --input-file test.input --output-file pkcstest --slot 1`
works, and produces a 96 byte file. 

Please give it a try.

**Comment by alex-nitrokey** [comment] 2020-03-31 13:09
I tested it myself and I can confirm that this seems to work. Though, I did not check the correctness of the signature. The user did not respond. I would see this issue as fixed until he states otherwise.

I used nistp384 created via GnuPG and the above command. I realized that it did not work with a large (126844 bytes) file, it gave CKR_DATA_LEN_RANGE (0x21), but I assume this is a known limitation?

**Comment by Jakuje** [comment] 2020-03-31 13:18
Did you test with the baa9f00 or top of Jakuje:eddsa?

It depends on what mechanism you are using.  CKM_ECDSA does allow max 1024 bit input (with possible truncation of given hash) according to PKCS#11 [1], but CKM_ECDSA_SHA1 should support unlimited input length (as it does the hashing).

[1] http://docs.oasis-open.org/pkcs11/pkcs11-curr/v2.40/cs01/pkcs11-curr-v2.40-cs01.html#_Toc399398884

**Comment by alex-nitrokey** [comment] 2020-04-02 12:27
> Did you test with the baa9f00 or top of Jakuje:eddsa?

I tested with baa9f00

I used `pkcs11-tool --sign --id 01 -m ECDSA --signature-format rs --pin 123456 --input-file test.input --output-file pkcstest --slot 1` with nistp384 keys.

**Closed** 2022-09-29 13:36 UTC
