### ISSUE TITLE
In pkcs11-tool CKA_DERIVE is not set for write-object and keygen

### ISSUE THREAD

**Issue by hosseinpro** [OpenSC/OpenSC#3068] opened 2024-03-13 17:34 UTC
### Problem Description

In pkcs11-tool CKA_DERIVE is not set for write-object and keygen

### Steps to reproduce

these commands do not return any error but do not set CKA_DERIVE for testkey.

pkcs11-tool --write-object /tmp/testkey --type secrkey --key-type aes:32 --label testkey --private --sensitive --usage-derive ...

Created secret key:
Secret Key Object; AES length 32
warning: PKCS11 function C_GetAttributeValue(VALUE) failed: rv = CKR_ATTRIBUTE_SENSITIVE (0x11)

  label:      testkey
  Usage:      encrypt, decrypt, verify, wrap, unwrap
  Access:     sensitive

pkcs11-tool --keygen --key-type aes:32 --label testkey --private --sensitive --usage-derive ...

Key generated:
Secret Key Object; AES length 32
warning: PKCS11 function C_GetAttributeValue(VALUE) failed: rv = CKR_ATTRIBUTE_SENSITIVE (0x11)

  label:      testkey
  Usage:      encrypt, decrypt, verify, wrap, unwrap
  Access:     sensitive, always sensitive, never extractable, local

**Comment by frankmorgner** [comment] 2024-03-13 23:43
I read PKCS#11 so that CKA_DERIVE is only possible for private key objects. CKA_DERIVE is not listed as possible attribute for secret key objects: https://docs.oasis-open.org/pkcs11/pkcs11-base/v3.0/csprd01/pkcs11-base-v3.0-csprd01.html#_Toc10472611

**Comment by Jakuje** [comment] 2024-03-27 09:12
Closing as this is intended behavior. If you will have some follow-up questions or some other reasoning why the derive should be there, please open a follow-up issue/discussion. 

Indeed, it would be good if the pkcs11-tool would report unsupported combination of CLI flags, but there is dozens of them and I do not think we can check all the valid/invalid combinations.

**Closed by Jakuje** 2024-03-27 09:12 UTC
