### ISSUE TITLE
pkcs15-crypt creates trucated RSA signature file in case the resulting number happens to have a leading 0 byte

### ISSUE THREAD

**Issue by MSoegtrop** [OpenSC/OpenSC#1283] opened 2018-03-12 19:43 UTC
### Problem Description

I use pkcs15-crypt with an OpenPGP 2.1 card with a 4096 bit RSA key as follows:

openssl dgst -sha512 -binary $1  > $1.dgst
pkcs15-crypt --sign --input $1.dgst --output $1.sig --signature-format openssl --sha-512 --pkcs1 --key 1

where $1 points to some file. The problem is that this occasionally results in signature files which have only 511 bytes, not 512 as it should be for a 4096 bit RSA key. I guess this happens if the resulting number computed by RSA happens to have a leading 0 byte.

openssl dgst -sha512 -verify key1.asc -signature $1.sig $1

Fails to verify such signature files. If I prepend (not append!) a 0 byte to the signature, openssl can verify the signature.

### Proposed Resolution

pad signatures to the proper length by prepending 0s.

I use this workaround:

SIZE=$( stat --printf="%s" $1.sig )
PAD=$(( 512 - SIZE ))
head -c $PAD /dev/zero | cat - $1.sig > $1.sig.tmp
rm $1.sig
mv $1.sig.tmp $1.sig

### Steps to reproduce

See above, but this depends on the specific key, which is in the card and I can't get it out of the card. I guess that this should happen randomly in at least one out of 256 cases (if the modulus doesn't fill the 4096 bit range well it should happens more frequently). With the same private key I usually get 512 byte signatures, only sometimes I get 511 byte signatures. But I guess the problem should be easy to see in the code.

## Version:

I use the version comming with Debian 9, 0.16.0-3

**Comment by frankmorgner** [comment] 2018-03-16 11:33
please run pkcs15-crypt with `-vvv`. I'm assuming that it's the card that returns 511 bytes...

**Comment by MSoegtrop** [comment] 2018-03-17 10:31
Dear Frank,

I created a test card and did a quick search for a test case. The resulting log of the failing case is below (starting after PIN verification). The data coming from the card indeed seems to lack the leading 0 byte - the correct signature starts with 00 36. The length is 513 bytes, but I guess there is some checksum or so appended.

If it helps I can supply a script which tries to sign random hashes until a too short signature is created.

Best regards,

Michael

PIN code correct.
0x7f1187a1f700 11:23:53.052 [pkcs15-crypt] pkcs15-sec.c:314:sc_pkcs15_compute_signature: called
0x7f1187a1f700 11:23:53.052 [pkcs15-crypt] pkcs15-sec.c:362:sc_pkcs15_compute_signature: supported algorithm flags 0x80000013, private key usage 0x20C
0x7f1187a1f700 11:23:53.052 [pkcs15-crypt] padding.c:283:sc_get_encoding_flags: called
0x7f1187a1f700 11:23:53.052 [pkcs15-crypt] padding.c:287:sc_get_encoding_flags: iFlags 0x802, card capabilities 0x80000013
0x7f1187a1f700 11:23:53.052 [pkcs15-crypt] padding.c:316:sc_get_encoding_flags: pad flags 0x800, secure algorithm flags 0x2
0x7f1187a1f700 11:23:53.052 [pkcs15-crypt] padding.c:317:sc_get_encoding_flags: returning with: 0 (Success)
0x7f1187a1f700 11:23:53.052 [pkcs15-crypt] pkcs15-sec.c:413:sc_pkcs15_compute_signature: DEE flags:0x00000802 alg_info->flags:0x80000013 pad:0x00000800 sec:0x00000002
0x7f1187a1f700 11:23:53.052 [pkcs15-crypt] padding.c:242:sc_pkcs1_encode: called
0x7f1187a1f700 11:23:53.052 [pkcs15-crypt] padding.c:246:sc_pkcs1_encode: hash algorithm 0x800, pad algorithm 0x0
0x7f1187a1f700 11:23:53.052 [pkcs15-crypt] padding.c:265:sc_pkcs1_encode: returning with: 0 (Success)
0x7f1187a1f700 11:23:53.052 [pkcs15-crypt] card.c:394:sc_lock: called
0x7f1187a1f700 11:23:53.052 [pkcs15-crypt] sec.c:68:sc_set_security_env: called
0x7f1187a1f700 11:23:53.052 [pkcs15-crypt] card-openpgp.c:1563:pgp_set_security_env: called
0x7f1187a1f700 11:23:53.052 [pkcs15-crypt] card-openpgp.c:1577:pgp_set_security_env: Key ref 0
0x7f1187a1f700 11:23:53.052 [pkcs15-crypt] card-openpgp.c:1580:pgp_set_security_env: Operation: Sign.
0x7f1187a1f700 11:23:53.052 [pkcs15-crypt] card-openpgp.c:1603:pgp_set_security_env: returning with: 0 (Success)
0x7f1187a1f700 11:23:53.052 [pkcs15-crypt] sec.c:72:sc_set_security_env: returning with: 0 (Success)
0x7f1187a1f700 11:23:53.052 [pkcs15-crypt] sec.c:54:sc_compute_signature: called
0x7f1187a1f700 11:23:53.052 [pkcs15-crypt] card-openpgp.c:1621:pgp_compute_signature: called
0x7f1187a1f700 11:23:53.053 [pkcs15-crypt] apdu.c:550:sc_transmit_apdu: called
0x7f1187a1f700 11:23:53.053 [pkcs15-crypt] card.c:394:sc_lock: called
0x7f1187a1f700 11:23:53.053 [pkcs15-crypt] apdu.c:517:sc_transmit: called
0x7f1187a1f700 11:23:53.053 [pkcs15-crypt] apdu.c:371:sc_single_transmit: called
0x7f1187a1f700 11:23:53.053 [pkcs15-crypt] apdu.c:376:sc_single_transmit: CLA:0, INS:2A, P1:9E, P2:9A, data(83) 0x7ffe285546f0
0x7f1187a1f700 11:23:53.053 [pkcs15-crypt] reader-pcsc.c:269:pcsc_transmit: reader 'Gemalto Ezio Shield (S14C0138574828) 00 00'
0x7f1187a1f700 11:23:53.053 [pkcs15-crypt] reader-pcsc.c:270:pcsc_transmit: 
Outgoing APDU (92 bytes):
00 2A 9E 9A 00 00 53 30 51 30 0D 06 09 60 86 48 .*....S0Q0...`.H
01 65 03 04 02 03 05 00 04 40 98 D5 23 AD CC 79 .e.......@..#..y
10 C7 9D 99 E5 B7 5D C8 F4 77 17 78 81 89 70 CB ......]..w.x..p.
A8 39 B9 58 90 49 FD 0E 29 F1 E5 43 24 42 43 F7 .9.X.I..)..C$BC.
35 F1 62 A6 39 60 10 62 8A 3A 13 5C 25 C3 05 FD 5.b.9`.b.:.\%...
6B 58 E7 62 BF 8C 8C 3C 3E 46 04 00             kX.b...<>F..
0x7f1187a1f700 11:23:53.053 [pkcs15-crypt] reader-pcsc.c:199:pcsc_internal_transmit: called
0x7f1187a1f700 11:23:55.905 [pkcs15-crypt] reader-pcsc.c:279:pcsc_transmit: 
Incoming APDU (513 bytes):
36 45 EB EC AD 01 EB EE CE 84 0A 3F F9 43 DC 09 6E.........?.C..
1F ED 0C 18 3E 2D 11 BF 9B 57 A8 8E B1 35 B9 C3 ....>-...W...5..
6C 41 4F 65 A7 6B A4 31 04 AA A3 A4 C2 CA 8B D9 lAOe.k.1........
C7 9E 2C 61 2F 02 F1 F7 14 B4 54 D9 48 FF 17 39 ..,a/.....T.H..9
05 24 DC 45 B0 9D 3F 4F BC 22 63 46 EF 24 CA 7A .$.E..?O."cF.$.z
68 E7 DF A0 64 C9 94 A9 6D AD F1 BB 7B EF 74 D8 h...d...m...{.t.
A1 ED 6C 7E 2B 03 C5 D6 10 C9 DC 2A 56 4A BE C3 ..l~+......*VJ..
03 0B D3 4E F0 83 8B F1 81 5D 5B FF C8 07 65 C8 ...N.....][...e.
E7 87 AC CB 81 86 E7 0E D1 81 C6 7A A9 6E E9 DB ...........z.n..
1A 8C 38 6E CA E0 63 78 C9 E8 FB 33 69 7E 5F 2C ..8n..cx...3i~_,
66 3B 94 3E E3 CB 73 5F 1A E4 6C B8 60 DF B6 05 f;.>..s_..l.`...
2E BC E1 41 E4 7E 9C 27 9D 59 D7 36 DC 74 CA 41 ...A.~.'.Y.6.t.A
21 E7 08 31 95 3D AB CA B2 2B D5 A0 A7 4E CA 6D !..1.=...+...N.m
BE 66 C1 0B 38 D2 35 2E A4 77 9E 17 BE 90 26 83 .f..8.5..w....&.
59 06 E4 D7 A9 19 C5 55 5A 38 1F A5 95 70 7C 83 Y......UZ8...p|.
CF 53 6B BC EC 9C 81 C7 A1 49 D5 40 EE 00 EE FB .Sk......I.@....
65 9A 81 4C A4 10 0D C1 61 3C 8F 4E F1 03 01 CA e..L....a<.N....
C3 F8 B8 05 F2 F1 FA 82 76 59 5B 01 EF 79 33 4B ........vY[..y3K
32 1F 24 A1 8C B1 7D F9 8D B3 71 27 D1 A9 F3 0F 2.$...}...q'....
3B 07 08 60 12 CE A1 02 AE FC 75 A9 80 66 5B 81 ;..`......u..f[.
4C B7 B4 D9 E6 14 E6 30 A2 BC 33 9B 95 1E 28 1F L......0..3...(.
33 6A 5A FF 39 22 36 46 DE D8 2E 86 C1 BA C9 C6 3jZ.9"6F........
C2 EE 76 8C C4 CB 77 98 7E BC BC A3 E5 FD A0 2C ..v...w.~......,
21 86 A1 F6 42 2E 90 1C AB 2D 3E 03 DD 47 BD 86 !...B....->..G..
5C B5 D5 09 38 BF F2 A3 1F 3C 6D B6 DE B6 EF B2 \...8....<m.....
83 D4 41 9E A5 CD D9 F5 38 ED 68 C9 A9 29 79 4F ..A.....8.h..)yO
92 1A 2C 68 37 70 B5 6E CC B6 FB 93 40 F2 05 56 ..,h7p.n....@..V
BB EB 3E EF 6E C6 41 DD F3 01 1D 93 66 DA DF 1D ..>.n.A.....f...
46 2D E2 5F 76 B0 B7 8D 8C BB D3 8E 8E 35 15 53 F-._v........5.S
20 03 73 45 E3 42 7D D9 3C C4 DA 72 21 08 21 44  .sE.B}.<..r!.!D
BF A7 0D D0 C7 BB 33 1E 7D DC 4D 44 39 ED 71 B0 ......3.}.MD9.q.
74 7A FE 7D E4 7B 98 26 D7 2A 9D 33 7C A1 08 90 tz.}.{.&.*.3|...
00                                              .
0x7f1187a1f700 11:23:55.906 [pkcs15-crypt] apdu.c:386:sc_single_transmit: returning with: 0 (Success)
0x7f1187a1f700 11:23:55.906 [pkcs15-crypt] apdu.c:539:sc_transmit: returning with: 0 (Success)
0x7f1187a1f700 11:23:55.906 [pkcs15-crypt] card.c:434:sc_unlock: called
0x7f1187a1f700 11:23:55.906 [pkcs15-crypt] card-openpgp.c:1659:pgp_compute_signature: returning with: 511
0x7f1187a1f700 11:23:55.906 [pkcs15-crypt] sec.c:58:sc_compute_signature: returning with: 511
0x7f1187a1f700 11:23:55.906 [pkcs15-crypt] card.c:434:sc_unlock: called
0x7f1187a1f700 11:23:55.906 [pkcs15-crypt] pkcs15-sec.c:441:sc_pkcs15_compute_signature: returning with: 511
0x7f1187a1f700 11:23:55.906 [pkcs15-crypt] pkcs15.c:1264:sc_pkcs15_unbind: called
0x7f1187a1f700 11:23:55.906 [pkcs15-crypt] pkcs15-pin.c:690:sc_pkcs15_pincache_clear: called
0x7f1187a1f700 11:23:55.906 [pkcs15-crypt] card.c:434:sc_unlock: called
0x7f1187a1f700 11:23:55.906 [pkcs15-crypt] reader-pcsc.c:587:pcsc_unlock: called
0x7f1187a1f700 11:23:55.911 [pkcs15-crypt] card.c:336:sc_disconnect_card: called
0x7f1187a1f700 11:23:55.912 [pkcs15-crypt] reader-pcsc.c:533:pcsc_disconnect: called
0x7f1187a1f700 11:23:55.979 [pkcs15-crypt] card.c:357:sc_disconnect_card: returning with: 0 (Success)
0x7f1187a1f700 11:23:55.979 [pkcs15-crypt] ctx.c:842:sc_release_context: called
0x7f1187a1f700 11:23:55.979 [pkcs15-crypt] reader-pcsc.c:794:pcsc_finish: called

**Comment by MSoegtrop** [comment] 2018-03-17 10:40
P.S.: I report a bug towards the OpenPGP team.

The specs of the OpenPGP card (section 7.2.8 PSO: COMPUTE DIGITAL SIGNATURE) say a lot about the format of the input to the command, but not much about the output (except that 90 00 is appended). One can argue that the output is a variable length integer and only as long as required. But at least this should be documented.

Best regards,

Michael

**Comment by dengert** [comment] 2018-03-17 17:58
It is strange no one else reported this as a problem. But as you point out
the OpenPGP does not say how to return the result. But this appears to be
some new card. This maybe the cards problem and mag fail with other
middleware too.

(The 9000 are the status bytes from the APDU command. 9000 is OK return.)

The card-openpgp.c could be changed to handle the situation and add leading
zero bytes so the result matches the RSA key size.

**Comment by MSoegtrop** [comment] 2018-03-17 18:42
Indeed strange. Maybe I was just lucky to spot the difference in file size for the failing signatures. Possibly others had issues before but just haven't been able to nail it down.

The card is (as far as I can tell) a standard OpenPGP V2.1 card from manufacturer ID 0x0005 which is ZeitControl. It shouldn't be any different from other OpenPGP V2.1 cards.

If your or someone else want's to test it with other cards, I can prepare a script which tries a few 100 random signatures until it fails.

Best regards,

Michael

**Comment by mouse07410** [comment] 2018-03-17 23:28
> The `card-openpgp.c` could be changed to handle the situation and add leading
zero bytes so the result matches the RSA key size.

Do you see any downside to this? If not - let's make this change.

**Comment by dengert** [comment] 2018-03-17 23:54
Go ahead. Note the pkcs15-crypt gets a big buffer and big buflen. So you
have to determine the size from the key size.

**Comment by frankmorgner** [comment] 2018-03-19 09:24
I'm not sure about the correct fix to this behavior. If I'm not mistaken, DER encoding should require to strip the leading byte if zero. I think that only a raw value (i.e. what you're creating with pkcs15-crypt) should contain the leading zero. So maybe the leading zero should be added in the upper layer where the encoding is also given.

**Comment by Jakuje** [comment] 2018-03-19 15:53
I ran the same test with the master and with my openpgp applet on yubikey and I am getting systematically correct number of bytes (256 for my 2048 b keys), so it sounds probably like a new issue of the new card. Even though I believe most of the other people are using PKCS#11 interface, which might be already taking care of that (strictly definining the output length of `C_Sign()`).

**Comment by MSoegtrop** [comment] 2018-03-23 08:45
A note: gpg seems to creates correct (in the sense of compatible) signatures with my card - or at least I haven't seen truncated signatures with it. Just pkcs15-crypt has this truncation problem. So I guess gpg does the padding internally.

@Jakuje: do you say that pkcs11-tool does work?

**Comment by Jakuje** [comment] 2018-03-23 10:52
I can not reproduce this issue with any of my cards so I can not confirm that. But since it is pretty deterministic for you, you can try it: https://github.com/OpenSC/OpenSC/wiki/Using-pkcs11-tool-and-OpenSSL

**Comment by frankmorgner** [comment] 2018-04-05 14:13
I found [the relevant piece of code in gnupg that adds the null-byte](https://github.com/gpg/gnupg/blob/master/agent/pksign.c#L371-L380):
```
if (*buf & 0x80)
            {
              len++;
              buf = xtryrealloc (buf, len);
              if (!buf)
                goto leave;


              memmove (buf + 1, buf, len - 1);
              *buf = 0;
            }
```
gnupg does this on top of creating a signature with any of their supported smart cards. So maybe it's a good idea to add this to `sc_pkcs15_compute_signature()` as well.

**Comment by MSoegtrop** [comment] 2018-04-07 09:06
Thanks. I would appreciate this change!
I am in discussion with the the GnuPG team to document that this is intended behavior of the card.
Best regards,
Michael

**Comment by dengert** [comment] 2018-04-07 17:39
[the relevant piece of code in gnupg that adds the null-byte](https://github.com/gpg/gnupg/blob/master/agent/pksign.c#L371-L380)  appears to be an attempt to make sure the signature is not interpreted as a negative number by preceding it with a zero byte. so it does not start with the high order bit set to 1. 

In the trace above, the card returned 513 bytes, including the SW1 and SW2 bytes. So it appears the card has stripped a leading zero byte and  returned the remaining 511 bytes.  The RSA `(modulus_length + 7) / 8` key size defines the size of the signature. The card might stripped multiple zero bytes. Any fix should handle too.

**Comment by dengert** [comment] 2018-04-07 18:33
pkcs15-crypt.c passes in a 1024 byte buffer when calling sc_pkcs15_compute_signature which returns the actual length. 

sc_pkcs15_compute_signature checks the size of the outlen to make sure it is big enough;
```
344         /* Probably never happens, but better make sure */
345         if (inlen > sizeof(buf) || outlen < modlen)
346                 LOG_FUNC_RETURN(ctx, SC_ERROR_BUFFER_TOO_SMALL);
```
sc_compute_signature leaves it up to the card to return the correct length:
```
62         r = card->ops->compute_signature(card, data, datalen, out, outlen);
```

If this was a general problem, I would have expected to see it years ago with other cards too. 
This looks like a card problem the card vendor of the card driver needs to solve.

**Comment by dengert** [comment] 2018-04-08 13:30
Looking at a number of sources, PKCS\#11 says the results of an RSA signature is of length "k". RFC 8017 says the signature operations:

Output:

      S        signature, an octet string of length k, where k is the
               length in octets of the RSA modulus n

Mathematically the result of an RSA operation is an integer. 

PKCS\#15 does not appear to says anything about the size.

So you may have something here. What should a card return, octet string of length k, on integer?
Should the card remove the leading zero bytes or not?

If it does, and the output is to be PKCS\#1 the leading bytes should be restored.  

In your example, you specified -pkcs1 so the output should match RFC 8017, the latest version of PKCS\#1. 

So we could look at having `sc_compute_signature` enforce the length k. 

 (You also specified  --signature-format openssl which is for EC only)

**Comment by MSoegtrop** [comment] 2018-04-08 21:30
I would say one can't derive from this (and other specs I have seen) that the card does not behave as specified. Since it doesn't seem to be terribly complicated to fix it, I would suggest to add the leading zeros back in the software.

**Comment by dengert** [comment] 2018-04-09 01:24
#1391 needs to be tested with your test cases and the card in question.

**Comment by frankmorgner** [comment] 2018-04-09 10:34
https://tools.ietf.org/html/rfc3447#section-5.2.1:
```
5.2.1 RSASP1

   RSASP1 (K, m)

   Input:
   K        RSA private key, where K has one of the following forms:
            - a pair (n, d)
            - a quintuple (p, q, dP, dQ, qInv) and a (possibly empty)
              sequence of triplets (r_i, d_i, t_i), i = 3, ..., u
   m        message representative, an integer between 0 and n - 1

   Output:
   s        signature representative, an integer between 0 and n - 1

   Error: "message representative out of range"

   Assumption: RSA private key K is valid
```
https://tools.ietf.org/html/rfc3447#section-8.2.1:
```
8.2.1 Signature generation operation

   RSASSA-PKCS1-V1_5-SIGN (K, M)

   Input:
   K        signer's RSA private key
   M        message to be signed, an octet string

   Output:
   S        signature, an octet string of length k, where k is the
            length in octets of the RSA modulus n

   Errors: "message too long"; "RSA modulus too short"

Steps:

   1. EMSA-PKCS1-v1_5 encoding: Apply the EMSA-PKCS1-v1_5 encoding
      operation (Section 9.2) to the message M to produce an encoded
      message EM of length k octets:

         EM = EMSA-PKCS1-V1_5-ENCODE (M, k).

      If the encoding operation outputs "message too long," output
      "message too long" and stop.  If the encoding operation outputs
      "intended encoded message length too short," output "RSA modulus
      too short" and stop.

   2. RSA signature:

      a. Convert the encoded message EM to an integer message
         representative m (see Section 4.2):

            m = OS2IP (EM).

      b. Apply the RSASP1 signature primitive (Section 5.2.1) to the RSA
         private key K and the message representative m to produce an
         integer signature representative s:

            s = RSASP1 (K, m).

      c. Convert the signature representative s to a signature S of
         length k octets (see Section 4.1):

            S = I2OSP (s, k).

   3. Output the signature S.
```
So RSASSA-PKCS1-V1_5-SIGN employs the signature mechanism RSASP1. With the OpenPGP card we're missing the step `2.c  S = I2OSP (s, k)`.

My read of the OpenPGP specification is that the card should support RSASSA-PKCS1-V1_5-SIGN (it's not made explicit, because they're only talking about some of the steps of the above process; specifically *not* mentioning 2.c.). So returning less bytes would be an error on the card's side.

In terms of fixing this issue, I'd like to see the null bytes added in `card-openpgp.c`, because the driver sets `SC_ALGORITHM_RSA_PAD_PKCS1`, so I'd expect the card (or the driver) to return a correctly formatted signature (simply move https://github.com/OpenSC/OpenSC/pull/1319 to the OpenPGP driver!). Note, that if the PKCS#1.5 padding is emulated by OpenSC, [the missing null bytes are automatically added if needed](https://github.com/OpenSC/OpenSC/blob/428b134776aaeeecd84a15f6b89000b695babc0b/src/libopensc/pkcs15-sec.c#L432-L437), which should be the reason why we did *not* see this issue earlier with other cards.

**Comment by dengert** [comment] 2018-04-09 14:10
[the missing null bytes are automatically added if needed](https://github.com/OpenSC/OpenSC/blob/428b134776aaeeecd84a15f6b89000b695babc0b/src/libopensc/pkcs15-sec.c#L432-L437) are fixing the input, not the output. 

We may not have seen this on other cards because:
- They do not remove leading zeros. 
- There is a 1/256 chance it could happen and no one reported it, because it is not easy to reproduce.
- The card internally is removing leading zeros based on a new card architecture or bad code.


The card is reported as OpenPGP 2.1 card with a 4096 bit RSA key from ZeitControl. 



[g10code](https://g10code.com/p-card.html) says:
Sample code for the OpenPGP application of the ZeitControl based card can be downloaded [here](https://g10code.com/docs/openpgp-card-v21-free-source.zip) but be aware that this version is not identical to the code on the sold cards. For further questions please contact the author of that software (see the source code).

The openpgp-card-v21-free-source.zip does:
`Call RsaExDecryptRaw(dat$, SigK$)` then later `ResponseLength = Len(dat$)`  

So is this a card with the g10code free driver or the ZeitControl  version. MaybeZeitcontrol has solved this issue.

What is the modulus of the RSA key? Could the first 8 bits of the 4096 bits be all zero complicating the code?

**Comment by dengert** [comment] 2018-04-09 14:57
P.S. I am not talking about a leading zero in the ASN1 in a certificate that is there to make sure the number does not appear to be a negative number. I am asking if the key really has only 4088 bits or less, which might cause an issue.  

Googling for: RSA key generation leading zero byte
shows a lot of issues with not following the standards.

**Comment by MSoegtrop** [comment] 2018-04-09 17:28
I will test it this weekend - sorry no time before.

**Comment by dengert** [comment] 2018-04-09 18:30
Questions for all:
Does anyone have the "Development Kits for BasicCard" at http://www.basiccard.com/index.html 
If they do, could they look at the `RsaExDecryptRaw` function and if there is a PGP smartcard driver code does it do more. 

Does anyone have a "ZietControl" card from [Flop-Shop](https://www.floss-shop.de/de/security-privacy/smartcards)? From the [G10code](http://www.g10code.de/p-card.htm) it appears g10code help write the OpenPGP applet for Floss-Shop. The lastest cards Flop-Shop sell says OpenPGP V3.3, but the comments next to the picture say it is still V2.1.

It starting to look like this is applet issue in the OpenPGP applet. And it looks like  Floss-Shop is the maintaining their own version of the OpenPGP applet. And we (i.e. someone who has one of these cards or wants it supported) should contact Floss-Shop to get this bug fixed in the applet

Some questions for @MSoegtrop 

Where did you get the card? Was it Floss-Shop? 
 
When you run the command using the same input data, do you always get the same signature? (This would show if padding is PKCS1 (block type 0x01 with all PS characters 0xFF) or  PKCS1.5 (block type 02 with PS being random non zero bytes) which will produce a different signature using the same input data. 

Do you have more then one card? Does the failure only happen on the one card? This might show it has something to do with the key properties.

What is the ATR of the card?

**Comment by dengert** [comment] 2018-04-09 18:37
As a side note, trying to support a "standard" applet on multiple types of cards each with its own version of an applet written by different vendors or individuals is getting very complicated. The "PIV" has add this problem, with non NIST approved PIV cards/tokens each having their own compliance issues. It looks like OpenPGP applets are starting to show up each with their own compliance issues.

**Comment by MSoegtrop** [comment] 2018-04-09 21:03
@dengert: I bought the card here:

http://www.cryptoshop.com/open-pgp-smartcard-v2.html

The manufacturer ID is 0005 = Zeitcontrol. The Version is 2.1. I have 5 of these cards. I have seen the effect with two cards (I think, might also have been one card with two different keys). The card seems to work fine. The effect is 100% reproducible - I always get the same signature with the same input. Also the signature with the missing 0 byte works fine if the 0 byte is prepended (see my initial post with the work around). It doesn't look like a reliability issue of the individual card.

As I said, I can provide a script to test inputs until a failing signature is created (will take until the weekend), so that other cards can be tested.

Not sure what an ATR is (sorry, I am just a user of this). On the card is printed the text:

V2.1 0005 <serial number>

**Comment by dengert** [comment] 2018-04-09 22:04
Thanks for the info. So http://www.cryptoshop.com/open-pgp-smartcard-v2.html is using the Zeitcontrol card, but it is not clear what applet they are using. It may be one they wrote, or they may have started from the open source example at the G10code site. That code combined with the use of the Zeitcontrol RsaExDecryptRaw could lead to the problem. 

That also means any other applets (not just OpenPGP) that use the Zeitcontrol card and use the open source example at the G10code site could have the same problem. 

`opensc-tool -a`  would show the ATR of the card.  [Parse ATR](https://smartcard-atr.appspot.com/) can have used to parse it. 

The [G10code](https://g10code.com/p-card.html)  example applets sets the ATR using:

`#Pragma ATR(T=1, FI=1, DI=8, HB=Chr$(0)+Chr$(&H31)+Chr$(&HC5)+Chr$(&H73)+Chr$(&HC0)+Chr$(&H01)+Chr$(&H40)+Chr$(0)+Chr$(&H90)+Chr$(0)`

The HB are the historic bytes of the ATR, and it would be interesting if your card's ATR matches this. 

I am in the US and don't have any access to any of these cards. Someone who has a bad card needs to track down the source of the applet on the card.

As Frank suggested, we could add #1319 like code  to the OpenSC card-openpgp.c. But the more general solution is #1319 as it could catch other applet if they use the Zeitcontrol  card too.

**Comment by mouse07410** [comment] 2018-04-13 12:36
I am waiting for #1319 to be merged.

**Closed** 2018-07-11 20:30 UTC
Labels: bug
