### ISSUE TITLE
PCSCD daemon sporadically fails to connect USB reader between execution loops due to libusb timeout

### ISSUE THREAD

**Issue by alfonsrv** [OpenSC/OpenSC#2413] opened 2021-09-19 08:43 UTC
### Problem Description

I'm currently working on a PIV-based door reader and noticed `opensc-tool` sometimes gets stuck on `Waiting for reader...` between execution loops, despite a reader being connected. Now this could be quite inconvenient for a physical access control. The issue seems to happen more frequently when letting it run with `pcscd --auto-exit` and waiting between executions. (1 `Failed adding USB device`)

I also found that when sending an APDU command that needs longer execution (e.g. beeping reader 7 times), causes a similar issue, but from what I can tell due to `Duplicate frame`s. (2 `Error communicating to`)

The only thing that helps at those points is to power-cycle the USB hub using [uhubctl](https://github.com/mvp/uhubctl). I hope this can provide some value – since the first issue is not straight forward to reproduce, I hope I can at least bring it up 

### Steps to reproduce

1. `Failed adding USB device`
    1. Connect favorite USB reader with e.g. PIV-certificate
    2. Run `opensc-tool` and read your card – maybe even add `pkcs15-tool` (can use [this code](https://github.com/alfonsrv/SimpleCardAuth/blob/master/simple-card-auth.sh) as a reference)
    3. Wait for the automatically spawned `pcscd` to exit
    4. Re-execute until you cannot read your smart-card anymore
2. `Error communicating to`
    1. Connect favorite USB reader with e.g. PIV-certificate
    2. Run `opensc-tool` with long executing APDU command (e.g. `opensc-tool --send-apdu FF:00:40:5D:04:01:04:07:02 --send-apdu FF:00:52:00:00 >> /dev/null 2>&1` beeps reader 7 times for ~one second each)

### Logs

[opensc.conf](https://github.com/alfonsrv/SimpleCardAuth/blob/master/opensc.conf)

<details>
  <summary>pcscd log (1)</summary>

```bash
root@raspberrypi:/home/pi/xo# sudo pcscd -a -f -d
00000000 debuglog.c:299:DebugLogSetLevel() debug level=debug
00001478 utils.c:82:GetDaemonPid() Can't open /var/run/pcscd/pcscd.pid: No such file or directory
00001405 configfile.l:284:DBGetReaderListDir() Parsing conf directory: /etc/reader.conf.d
00000948 configfile.l:321:DBGetReaderListDir() Skipping non regular file: ..
00000814 configfile.l:321:DBGetReaderListDir() Skipping non regular file: .
00000460 configfile.l:360:DBGetReaderList() Parsing conf file: /etc/reader.conf.d/libccidtwin
00001334 pcscdaemon.c:662:main() pcsc-lite 1.8.24 daemon ready.
00024395 hotplug_libudev.c:297:get_driver() Looking for a driver for VID: 0x1D6B, PID: 0x0002, path: /dev/bus/usb/001/001
00002568 hotplug_libudev.c:297:get_driver() Looking for a driver for VID: 0x1D6B, PID: 0x0002, path: /dev/bus/usb/001/001
00002395 hotplug_libudev.c:297:get_driver() Looking for a driver for VID: 0x2109, PID: 0x3431, path: /dev/bus/usb/001/002
00002967 hotplug_libudev.c:297:get_driver() Looking for a driver for VID: 0x072F, PID: 0x2200, path: /dev/bus/usb/001/005
00001025 hotplug_libudev.c:436:HPAddDevice() Adding USB device: ACS ACR122U PICC Interface
00001012 readerfactory.c:1075:RFInitializeReader() Attempting startup of ACS ACR122U PICC Interface 00 00 using /usr/lib/pcsc/drivers/ifd-ccid.bundle/Contents/Linux/libccid.so                                                                                                                               
00002621 readerfactory.c:950:RFBindFunctions() Loading IFD Handler 3.0
00001265 ifdhandler.c:1961:init_driver() Driver version: 1.4.30
00005038 ifdhandler.c:1978:init_driver() LogLevel: 0x0003
00000121 ifdhandler.c:1989:init_driver() DriverOptions: 0x0000
00001494 ifdhandler.c:110:CreateChannelByNameOrChannel() Lun: 0, device: usb:072f/2200:libudev:0:/dev/bus/usb/001/005
00000134 ccid_usb.c:302:OpenUSBByName() Using: /usr/lib/pcsc/drivers/ifd-ccid.bundle/Contents/Info.plist
00004082 ccid_usb.c:320:OpenUSBByName() ifdManufacturerString: Ludovic Rousseau (ludovic.rousseau@free.fr)
00000049 ccid_usb.c:321:OpenUSBByName() ifdProductString: Generic CCID driver
00000040 ccid_usb.c:322:OpenUSBByName() Copyright: This driver is protected by terms of the GNU Lesser General Public License version 2.1, or (at your option) any later version.                                                                                                                             
00246289 ccid_usb.c:660:OpenUSBByName() Found Vendor/Product: 072F/2200 (ACS ACR122U PICC Interface)
00000052 ccid_usb.c:662:OpenUSBByName() Using USB bus/device: 1/5
00000038 ccid_usb.c:722:OpenUSBByName() bNumDataRatesSupported is 0
00159237 ccid_usb.c:898:ReadUSB() read failed (1/5): -7 LIBUSB_ERROR_TIMEOUT
00058316 ccid_usb.c:920:ReadUSB() Duplicate frame detected
00100296 ccid_usb.c:898:ReadUSB() read failed (1/5): -7 LIBUSB_ERROR_TIMEOUT
00000046 ifdhandler.c:194:CreateChannelByNameOrChannel() failed
00000109 ccid_usb.c:189:close_libusb_if_needed() libusb_exit
00000579 readerfactory.c:1106:RFInitializeReader() Open Port 0x200000 Failed (usb:072f/2200:libudev:0:/dev/bus/usb/001/005)
00000046 readerfactory.c:376:RFAddReader() ACS ACR122U PICC Interface init failed.
00000039 readerfactory.c:610:RFRemoveReader() UnrefReader() count was: 1
00000036 readerfactory.c:1126:RFUnInitializeReader() Attempting shutdown of ACS ACR122U PICC Interface 00 00.
00000037 readerfactory.c:987:RFUnloadReader() Unloading reader driver.
00000273 hotplug_libudev.c:523:HPAddDevice() Failed adding USB device: ACS ACR122U PICC Interface
00000844 hotplug_libudev.c:297:get_driver() Looking for a driver for VID: 0x2109, PID: 0x3431, path: /dev/bus/usb/001/002
00001533 hotplug_libudev.c:297:get_driver() Looking for a driver for VID: 0x1D6B, PID: 0x0003, path: /dev/bus/usb/002/001
```
</details>

<details>
  <summary>pcscd log (2)</summary>

```bash
root@raspberrypi:/home/pi/xo# opensc-tool --send-apdu FF:00:40:5D:04:01:04:07:02 
│  Port 1: 0100 power
Using reader with a card: ACS ACR122U PICC Interface 00 00 │  Port 2: 0100 power
Sending: FF 00 40 5D 04 01 04 07 02 │  Port 3: 0100 power
APDU transmit failed: Transmit failed 

----

root@raspberrypi:/home/pi/xo# sudo pcscd --foreground --info
00000000 debuglog.c:295:DebugLogSetLevel() debug level=info
00001364 pcscdaemon.c:662:main() pcsc-lite 1.8.24 daemon ready.
00020523 hotplug_libudev.c:436:HPAddDevice() Adding USB device: ACS ACR122U PICC Interface
00000275 readerfactory.c:1075:RFInitializeReader() Attempting startup of ACS ACR122U PICC Interface 00 00 using /usr/lib/pcsc/drivers/ifd-ccid.bundle/Contents/Linux/libccid.so
00001318 readerfactory.c:950:RFBindFunctions() Loading IFD Handler 3.0
00000156 ifdhandler.c:1961:init_driver() Driver version: 1.4.30
00003200 ifdhandler.c:1978:init_driver() LogLevel: 0x0003
00000079 ifdhandler.c:1989:init_driver() DriverOptions: 0x0000
00000874 ifdhandler.c:110:CreateChannelByNameOrChannel() Lun: 0, device: usb:072f/2200:libudev:0:/dev/bus/usb/001/009
00000087 ccid_usb.c:302:OpenUSBByName() Using: /usr/lib/pcsc/drivers/ifd-ccid.bundle/Contents/Info.plist
00003327 ccid_usb.c:320:OpenUSBByName() ifdManufacturerString: Ludovic Rousseau (ludovic.rousseau@free.fr)
00000079 ccid_usb.c:321:OpenUSBByName() ifdProductString: Generic CCID driver
00000065 ccid_usb.c:322:OpenUSBByName() Copyright: This driver is protected by terms of the GNU Lesser General Public License version 2.1, or (at your option) any later version.
00247843 ccid_usb.c:660:OpenUSBByName() Found Vendor/Product: 072F/2200 (ACS ACR122U PICC Interface)
00000125 ccid_usb.c:662:OpenUSBByName() Using USB bus/device: 1/9
00000092 ccid_usb.c:722:OpenUSBByName() bNumDataRatesSupported is 0
00745341 ifdhandler.c:381:IFDHGetCapabilities() tag: 0xFB3, usb:072f/2200:libudev:0:/dev/bus/usb/001/009 (lun: 0)
00000122 readerfactory.c:396:RFAddReader() Using the reader polling thread
00000659 ifdhandler.c:381:IFDHGetCapabilities() tag: 0xFAE, usb:072f/2200:libudev:0:/dev/bus/usb/001/009 (lun: 0)
00000114 ifdhandler.c:476:IFDHGetCapabilities() Reader supports 1 slot(s)
09698928 ifdhandler.c:1411:IFDHControl() ControlCode: 0x42000D48, usb:072f/2200:libudev:0:/dev/bus/usb/001/009 (lun: 0)
00000050 Control TxBuffer:
00000062 Control RxBuffer: 12 04 42 33 00 12
00000189 ifdhandler.c:1411:IFDHControl() ControlCode: 0x42330012, usb:072f/2200:libudev:0:/dev/bus/usb/001/009 (lun: 0)
00000037 Control TxBuffer:
00000041 Control RxBuffer: 01 02 00 00 03 01 00 09 01 00 0B 02 2F 07 0C 02 00 22 0A 04 00 00 00 00
00000182 ifdhandler.c:1411:IFDHControl() ControlCode: 0x42330012, usb:072f/2200:libudev:0:/dev/bus/usb/001/009 (lun: 0)
00000040 Control TxBuffer:
00000041 Control RxBuffer: 01 02 00 00 03 01 00 09 01 00 0B 02 2F 07 0C 02 00 22 0A 04 00 00 00 00
00000193 ifdhandler.c:381:IFDHGetCapabilities() tag: 0x10100, usb:072f/2200:libudev:0:/dev/bus/usb/001/009 (lun: 0)
00000220 ifdhandler.c:381:IFDHGetCapabilities() tag: 0x10102, usb:072f/2200:libudev:0:/dev/bus/usb/001/009 (lun: 0)
00000206 ifdhandler.c:381:IFDHGetCapabilities() tag: 0xFB2, usb:072f/2200:libudev:0:/dev/bus/usb/001/009 (lun: 0)
00000033 winscard.c:1033:SCardDisconnect() Stopping polling thread
00000029 ifdhandler.c:346:IFDHStopPolling() usb:072f/2200:libudev:0:/dev/bus/usb/001/009 (lun: 0)
00548859 ifdhandler.c:1154:IFDHPowerICC() action: PowerUp, usb:072f/2200:libudev:0:/dev/bus/usb/001/009 (lun: 0)
00000817 eventhandler.c:423:EHStatusHandlerThread() Card inserted into ACS ACR122U PICC Interface 00 00
00000069 Card ATR: 3B 8D 80 01 80 73 C0 21 C0 57 59 75 62 69 4B 65 FF 7F
02182396 prothandler.c:108:PHSetProtocol() Attempting PTS to T=1
00000070 ifdhandler.c:695:IFDHSetProtocolParameters() protocol T=1, usb:072f/2200:libudev:0:/dev/bus/usb/001/009 (lun: 0)
00000213 ifdhandler.c:1411:IFDHControl() ControlCode: 0x42000D48, usb:072f/2200:libudev:0:/dev/bus/usb/001/009 (lun: 0)
00000042 Control TxBuffer:
00000063 Control RxBuffer: 12 04 42 33 00 12
00000215 ifdhandler.c:1411:IFDHControl() ControlCode: 0x42330012, usb:072f/2200:libudev:0:/dev/bus/usb/001/009 (lun: 0)
00000041 Control TxBuffer:
00000047 Control RxBuffer: 01 02 00 00 03 01 00 09 01 00 0B 02 2F 07 0C 02 00 22 0A 04 00 00 00 00
00000210 ifdhandler.c:1411:IFDHControl() ControlCode: 0x42330012, usb:072f/2200:libudev:0:/dev/bus/usb/001/009 (lun: 0)
00000042 Control TxBuffer:
00000047 Control RxBuffer: 01 02 00 00 03 01 00 09 01 00 0B 02 2F 07 0C 02 00 22 0A 04 00 00 00 00
00000250 ifdhandler.c:381:IFDHGetCapabilities() tag: 0x10100, usb:072f/2200:libudev:0:/dev/bus/usb/001/009 (lun: 0)
00000253 ifdhandler.c:381:IFDHGetCapabilities() tag: 0x10102, usb:072f/2200:libudev:0:/dev/bus/usb/001/009 (lun: 0)
00000234 ifdhandler.c:381:IFDHGetCapabilities() tag: 0xFB2, usb:072f/2200:libudev:0:/dev/bus/usb/001/009 (lun: 0)
00000038 winscard.c:1033:SCardDisconnect() Stopping polling thread
00000031 ifdhandler.c:346:IFDHStopPolling() usb:072f/2200:libudev:0:/dev/bus/usb/001/009 (lun: 0)
00003396 ifdhandler.c:1303:IFDHTransmitToICC() usb:072f/2200:libudev:0:/dev/bus/usb/001/009 (lun: 0)
00024731 ifdhandler.c:1303:IFDHTransmitToICC() usb:072f/2200:libudev:0:/dev/bus/usb/001/009 (lun: 0)
00019555 ifdhandler.c:1303:IFDHTransmitToICC() usb:072f/2200:libudev:0:/dev/bus/usb/001/009 (lun: 0)
00025065 ifdhandler.c:1303:IFDHTransmitToICC() usb:072f/2200:libudev:0:/dev/bus/usb/001/009 (lun: 0)
00026144 ifdhandler.c:1303:IFDHTransmitToICC() usb:072f/2200:libudev:0:/dev/bus/usb/001/009 (lun: 0)
00021852 ifdhandler.c:1303:IFDHTransmitToICC() usb:072f/2200:libudev:0:/dev/bus/usb/001/009 (lun: 0)
00013363 ifdhandler.c:1303:IFDHTransmitToICC() usb:072f/2200:libudev:0:/dev/bus/usb/001/009 (lun: 0)
00022986 ifdhandler.c:1303:IFDHTransmitToICC() usb:072f/2200:libudev:0:/dev/bus/usb/001/009 (lun: 0)
00016677 ifdhandler.c:1303:IFDHTransmitToICC() usb:072f/2200:libudev:0:/dev/bus/usb/001/009 (lun: 0)
00016680 ifdhandler.c:1303:IFDHTransmitToICC() usb:072f/2200:libudev:0:/dev/bus/usb/001/009 (lun: 0)
00025209 ifdhandler.c:1303:IFDHTransmitToICC() usb:072f/2200:libudev:0:/dev/bus/usb/001/009 (lun: 0)
00016659 ifdhandler.c:1303:IFDHTransmitToICC() usb:072f/2200:libudev:0:/dev/bus/usb/001/009 (lun: 0)
00016666 ifdhandler.c:1303:IFDHTransmitToICC() usb:072f/2200:libudev:0:/dev/bus/usb/001/009 (lun: 0)
00021987 ifdhandler.c:1303:IFDHTransmitToICC() usb:072f/2200:libudev:0:/dev/bus/usb/001/009 (lun: 0)
00021985 ifdhandler.c:1303:IFDHTransmitToICC() usb:072f/2200:libudev:0:/dev/bus/usb/001/009 (lun: 0)
00013465 ifdhandler.c:1303:IFDHTransmitToICC() usb:072f/2200:libudev:0:/dev/bus/usb/001/009 (lun: 0)
00019522 ifdhandler.c:1303:IFDHTransmitToICC() usb:072f/2200:libudev:0:/dev/bus/usb/001/009 (lun: 0)
00022134 ifdhandler.c:1303:IFDHTransmitToICC() usb:072f/2200:libudev:0:/dev/bus/usb/001/009 (lun: 0)
03000930 ccid_usb.c:898:ReadUSB() read failed (1/9): -7 LIBUSB_ERROR_TIMEOUT
00000077 ifdwrapper.c:543:IFDTransmit() Card not transacted: 612
00000034 winscard.c:1626:SCardTransmit() Card not transacted: 0x80100016
03001211 ccid_usb.c:898:ReadUSB() read failed (1/9): -7 LIBUSB_ERROR_TIMEOUT
00000072 ifdwrapper.c:364:IFDStatusICC() Card not transacted: 612
00000038 eventhandler.c:336:EHStatusHandlerThread() Error communicating to: ACS ACR122U PICC Interface 00 00
00000033 ifdhandler.c:381:IFDHGetCapabilities() tag: 0xFB2, usb:072f/2200:libudev:0:/dev/bus/usb/001/009 (lun: 0)
00000046 winscard.c:1033:SCardDisconnect() Stopping polling thread
00000035 ifdhandler.c:346:IFDHStopPolling() usb:072f/2200:libudev:0:/dev/bus/usb/001/009 (lun: 0)
00401418 ccid_usb.c:898:ReadUSB() read failed (1/9): -8 LIBUSB_ERROR_OVERFLOW
00000052 ifdwrapper.c:364:IFDStatusICC() Card not transacted: 612
00000035 eventhandler.c:336:EHStatusHandlerThread() Error communicating to: ACS ACR122U PICC Interface 00 00
05000913 ccid_usb.c:920:ReadUSB() Duplicate frame detected
03000593 ccid_usb.c:898:ReadUSB() read failed (1/9): -7 LIBUSB_ERROR_TIMEOUT
00000057 ifdwrapper.c:364:IFDStatusICC() Card not transacted: 612
00000424 ccid_usb.c:920:ReadUSB() Duplicate frame detected
```
</details>

**Comment by Jakuje** [comment] 2021-09-19 11:04
That sounds more like an issue of pcsc-lite: https://github.com/LudovicRousseau/PCSC/issues
opensc does not do anything with usb directly. But it might be also how the pcsc is handled in opensc.

I recently recently merged a modification to pcsc code to check for plugging in both reader and card at the same time (for example yubikey), but that might not be related. But it would be worth mentioning if you used some master commit or some released version.

The `--auto-exit` functionality of pcscd is problematic for long-running applications, but I am really not sure how the systemd socket invocation works in these case. Certainly when it is expected to be the only application running on the system to check the access, it does not make sense to keep it exiting.

The opensc can call some reconnects, but on the first sight, I do not see this in the `pcsc_wait_for_event` functions, which are invoked to wait for new cards or readers. So it might be needed to plug them somewhere.

(did not yet look into the logs -- I will try to do that tomorrow)

**Comment by dengert** [comment] 2021-09-19 16:46
I agree with @Jakuje on the reader timeout issues. 

Could it also be the USB powers off?

**Comment by alfonsrv** [comment] 2021-09-19 17:34
@Jakuje 
Ah didn't know they're two *somewhat* separate repos – thanks for the pointer. Even though 

I'm currently on commit 7a6032d39e4373c24cb813b6140a0a0b4d9baea3

```bash
root@raspberrypi:~# opensc-tool --version
OpenSC-0.22.0-rc1-161-g7a6032d3, rev: 7a6032d3, commit-time: 2021-09-15 09:57:54 +0200

root@raspberrypi:~# pcscd --version
pcsc-lite version 1.8.24.
```

@dengert 
The power cycle workaround was only introduced after the timeouts.

**Comment by LudovicRousseau** [comment] 2021-09-19 21:38
@alfonsrv I am not sure if the problem is with pcscd, the CCID driver or something at the USB layer.
libusb errors like LIBUSB_ERROR_TIMEOUT or LIBUSB_ERROR_OVERFLOW at NOT a good sign.

Also the USB layer on the Raspberry Pi had some issues. See https://ludovicrousseau.blogspot.com/2014/04/usb-issues-with-raspberry-pi.html
Can you reproduce the problem on a "real" computer?

**Comment by dengert** [comment] 2021-09-19 23:57
Is this a power issue?

What Raspberry Pi model are you using?

What version of the OS?

You said you needed to: "power-cycle the USB hub using uhubctl." Is this the builtin hub, or do you have an external hub?  Does it have its own power supply?

What other USB devices do you have?

I have a ACR112U-A9 and uses 200mA.

@LudovicRousseau 's blog is from 2014, and the http://www.yoctopuce.com/EN/article/cook-and-hold-with-raspberry-pi-video is from 2012 which says: "Edit: The "dwc_otg.speed" option is no more needed on Raspberry Pi B+ and later models." 

I have a ACR112U-A9 which uses 200mA and have used it with PIV cards in Windows and Ubuntu. 

I also have an original Rassberry Pi from 2011, a Pi 3 , a Pi Zero W and a Pi 4 64 bit running Ubuntu 64 bit 20.10 with, opensc 0.20.0 and pcscd 1.9.0.1. Also have many PIV devices. 

 So if you don't get anywhere, let me know and I can look at this problem during the week.

**Comment by alfonsrv** [comment] 2021-09-20 14:39
@LudovicRousseau interesting. I tried sending the same APDU command `opensc-tool -w --send-apdu FF:00:40:5D:04:01:04:07:02 -v` (beeping reader 7 times as per the [reader documentation](https://github.com/alfonsrv/SimpleCardAuth/blob/master/misc/API-ACR122U-2.04.pdf)) trying to reproduce 2 `Error communicating to` from my Mac (MBP M1, Big Sur) and the error is *similar*.

The reader works initially and reads the card, but then `opensc-tool` gets stuck on `Waiting for a card to be inserted...` for subsequent executions. Unfortunately I don't really know how to get `pcscd` debug output to work on macOS w/ M1, but I'll try on my Linux laptop tonight.

---

@dengert the Pi is not running in undervoltage. Also it seems like me specifying uhubctl was misleading. Simply plugging the card reader out and back in also works. I'm using uhubctl as a means to emulate plugging the reader out and back in to allow for continuous operation when one of the mentioned errors is detected. Sorry for not specifying that part more thoroughly.  

Here's a spec overview:

* **Hardware**: Raspberry Pi 4B 4GB
* **OS**: Raspbian GNU/Linux 10 32bit
* **USB**: Raspberry On-Board USB hub. Problem equally exists with USB 2 and USB 3 port. No other USB devices are attached

**Comment by LudovicRousseau** [comment] 2021-09-20 15:08
Good idea to test with a Mac.
Pcscd does not exist on macOS. Apple has something completely different. But the CCID driver is the same.
It is not easy to get logs on macOS. You can try with https://ludovicrousseau.blogspot.com/2017/11/debug-smart-card-application-on-sierra.html

I am now suspecting a firmware or hardware problem with the reader.

**Comment by dengert** [comment] 2021-09-20 17:03
A test that hangs:
- Ubuntu 20.04 as VM with Windows 10 host
- OpenSC built from master yesterday
- pcscd from Ubuntu 1.8.26-3
- ACR122 reader attached to Ubuntu VM,
- NIST demo PIV card on the reader
- Reader light is green
- Made sure OS pcscd was canceled
- $ sudo pcscd -a -f -d 2>&1 | tee /tmp/pcsc.log (in the pcscd log it reads the ATR)
- $./opensc-tool -w --send-apdu "00 CB 3F FF 03 5C 01 7E 00" ( The apdu can be any, it is never sent.)
- opensc-tool  just waits. "Waiting for a card to be inserted..."  (at 10:48:42 in log)
- cancel pcscd at 1(1:13:46 in log.) 
- opensc-tool "Error while waiting for a card: Unknown error" "Failed to connect to reader: Unknown error"


[ACR122-pcsc.log.txt](https://github.com/OpenSC/OpenSC/files/7197176/ACR122-pcsc.log.txt)
[ACR122-opensc-tool.log.txt](https://github.com/OpenSC/OpenSC/files/7197178/ACR122-opensc-tool.log.txt)

It looks like this is a logic error to me. opensc-tool is trying to wait for a reader and a card. It calls util_connect_reader to connect to reader that writes "Waiting for a reader to be attached...\n"
then calls pcsc_wait_for_event, which does not return until pcscd was cancelled. 

Logic error is opensc-tool wants reader and card in reader. But pcsc_wait_for_event is called to request a change in events. In log
https://github.com/OpenSC/OpenSC/blob/master/src/libopensc/reader-pcsc.c#L1693 says:
 "'ACS ACR122U PICC Interface 00 00' before=0x00000022 now=0x00000020" 

So this may not be the only problem for this issue, but opensc-tool -w is not doing what it should do.

**Comment by dengert** [comment] 2021-09-21 17:48
My previous comment https://github.com/OpenSC/OpenSC/issues/2413#issuecomment-923111165 may be only occur when running in a VM.  When attaching or detaching a reader from a VM. It does not appear to be reset or power removed, thus the reader with the the card my not be reporting any events when attached to the guest. 

I tested my ACR122U  with Pi 3 with Raspian 10 (buster) and kernel 5.4.72 from 2020 without any problems using a NIST demo card and a Yubikey 5 NFC. This has pcscd 1.8.24 and opensc-0.19.0

I also used a Pi 4 with Ubuntu-20.10  and had to blacklist in /etc/modprobe.d/   nfc, pn533 and pn533_lib as these caused problems with pcscd. (I also did that with the VM and forgot about it). 

@alfonsrv  So it looks like I am running the same OS and pcscd as you are. But check to see it your system has  nfc, pn533 and pn533_lib. Also look for any other packages that might try and use the usb device, thus interfering with pcscd. 

I now agree with @LudovicRousseau  that this could be firmware or hardware related. 

Windows reports my ACR122U-A9  as "USB\VID_072F&PID_2200\6&203499ab&0&7"
The back of the reader has: 
ACR122
P/N:ACR122U-A9
Power: 5VDC, 200mA
S/N: RR171-152669

 http://downloads.acs.com.hk/drivers/en/API-ACR122U-2.02.pdf says to get firmware. With card on the reader I get:
```
$ opensc-tool -c default -s"FF 00 48 00 00"
Using reader with a card: ACS ACR122U PICC Interface 00 00
Sending: FF 00 48 00 00 
Received (SW1=0x31, SW2=0x34):
41 43 52 31 32 32 55 32 ACR122U2
```
The SW1 and SW2 may be part of the version i.e.  ACR122U214

**Comment by alfonsrv** [comment] 2021-09-21 18:47
Sorry for the delay – I'm currently waiting for my other reader (same version, but other revision) to return to me tomorrow, so I can test in a more differentiated manner. Will update.

**Comment by frankmorgner** [comment] 2023-01-19 08:28
Closing this issue due to inactivity. Please re-open the ticket if more input is available.

**Closed by frankmorgner** 2023-01-19 08:28 UTC
Labels: Input needed

**Comment by rubygoldbergmachineinc** [comment] 2023-11-24 00:39
@alfonsrv were you able to figure out the resolution. I am facing a similar random libusb (-7) timeout of close to 170 seconds with Identiv reader.

**Comment by alfonsrv** [comment] 2023-11-25 17:51
@rubygoldbergmachineinc I was not able to reproduce this issue, taking a clean OS. Admittedly my first OS had a lot of different packages from prototyping, but when installing just the required ones, the error did not occur. So it is likely either something with the hardware or – which I think is more likely – an incompatibility with another service/package I installed, causing a race condition or deadlock of some kind. Just a supposition though

**Comment by rubygoldbergmachineinc** [comment] 2023-12-12 03:24
Thanks @alfonsrv. Can you please share versions for pcsc-lite, ccid, libusb which seem to work in combination correctly.
