### ISSUE TITLE
Certificates no longer visible in Keychain in macOS Catalina after update

### ISSUE THREAD

**Issue by onno182** [OpenSC/OpenSC#1851] opened 2019-11-07 08:03 UTC
### Problem Description
After the last Catalina update, it seems like it is no longer possible to activate the older TokenD with the command  `sudo defaults write /Library/Preferences/com.apple.security.smartcard Legacy -bool true`.  

Running this command previously made the certificates visible in keychain, and also usable in apps.

Any other ideas how to make the certificates usable again by apps?.

**Comment by mouse07410** [comment] 2019-11-07 08:16
There’sa way to re-enable support for tokend, but is not recommended. With the next update it would probably be gone altogether. 

It is safe to assume that unless Apple changes I’d current plans and policies, there’s no way to view certs on a token via Keychain Access app. I must add that CLI for viewing this certs sucks big. 

The two options I’m aware of are:
- System Information (I don’t remember exactly how, and won’t have access to my computer to check it for a week or more);
- Free utility “Smartcard Utility” (again, don’t remember its exact name) in the App Store.

**Comment by onno182** [comment] 2019-11-11 08:31
Although the keys and certs are visible in the CLI under CryptoKit, they don't appear in keychain (which is expected), however, they also are not accessible to applications.  For instance, the Apple Mail app and Outlook are unable to see them.

Workaround was to enable TokenD, which made the certificates appear in Keychain, and also made hem accessible to other applications. Unfortunately, it seems that Apple may have removed TokenD support with the last update.

**Comment by frankmorgner** [comment] 2019-11-12 04:10
duplicate of #1798 #1767 

Please open a bug at Apple's support.

**Closed by frankmorgner** 2019-11-12 04:10 UTC

**Comment by mouse07410** [comment] 2019-11-16 18:56
The older Outlook (prior to 16.31) doesn’t support CTK, and won’t be able to access certs on a token (without Tokend).

Apple Mail should be able to access them, unless it picks other certs it considers usable from the Keychain. E.g., you have certs for joe@example.com both in your Keychain and on the token. Most likely, it would ignore what’s on the token in this case.

**Comment by onno182** [comment] 2019-11-18 07:30
Both problems occur with the latest outlook and Apple Mail version.  

Unfortunately both are unable to see any certificates on the token.

The command line tools show the certificates (and also the TokenD driver) without problems.  However, Outlook and Apple Mail are unable to access the certificates.

**Comment by frankmorgner** [comment] 2019-11-18 12:49
please cross check on Windows whether your card/certificates should work.

**Comment by onno182** [comment] 2019-11-18 14:36
Unfortunately I don't have access to windows, however, I have reset the PIV on the Yubikey and imported all the certificates again.  

The problem remains.

**Comment by onno182** [comment] 2019-11-26 14:57
Had some time again today to try to see if I could get it back working.

Smartcard gets identified and is usable within sc_auth.

However, within the security command, the smartcard is not visbile.  

`security smartcards token -l` 

Is empty.

Although list-smartcards yields a return, I do not believe this is a valid smartcard.

`security list-smartcards
com.apple.pivtoken:CC27E2E4029032B954C70E379133FCAC`

Is there anyway to reset com.apple.pivtoken?.

**Comment by joegoerlich** [comment] 2019-12-12 21:14
The legacy mode is working in 10.15.2 as expected. Certificates are listed in the keychain app again. Seems apple fixed the bug.
