### ISSUE TITLE
OpenSC 0.22 newly fails to initialize a Feitian ePass2003 Auto USB device

### ISSUE THREAD

**Issue by muks** [OpenSC/OpenSC#2397] opened 2021-08-26 23:02 UTC
### Problem Description

After upgrading from `opensc-0.21.0-4.fc34.x86_64` to `opensc-0.22.0-1.fc34` on Fedora 34, I am unable to initialize a Feitian ePass2003 Auto USB device using `pkcs15-init`. The error that I'm newly seeing is:

```
Failed to create PKCS #15 meta structure: EF offset too large
```

This used to work fine with `opensc-0.21.0-4.fc34.x86_64`, and reverting back to the older package version makes it work again. There were no other package changes on the machine.

### Proposed Resolution

None from my side (I'm just an end user). The `pkcs15-init` command should not error.

### Steps to reproduce

The commands used to initialize are:
```
# Erase the smartcard
pkcs15-init -E

# Initialize the smartcard (this prints an error now in opensc-0.22.0-1.fc34)
pkcs15-init --create-pkcs15 --profile pkcs15+onepin --use-default-transport-key --pin 1234 --puk 12345678 --label "Token Label"
```

The device is:
```
Bus 004 Device 015: ID 096e:080a Feitian Technologies, Inc. ePass2003Auto
```

I currently do not have an unused device to capture more information right now - we issued the devices we had. I should be receiving more devices tomorrow if any additional information is desired.

Thank you.

**Comment by dengert** [comment] 2021-08-30 02:59
I have been looking at this issue and #2398 this weekend using my old epass2003 from December 2014. (This was from Gooze.) 

(I suggest for now, uses a shorter label.)

At the start I found 0.21.0 as installed on Ubuntu-20.04 both 
 `OPENSC_DEBUG=7  OPENSC_DRIVER=epass2003 pkcs15-init -E` and
` pkcs15-init --create-pkcs15 --profile pkcs15+onepin --use-default-transport-key --pin 123456 --puk entersafe --label "1"` worked, and I was able to use `pkcs15-tool ---list-info`

But after some debugging and getting ready to run git bisect. things got worse. 

I believe this is related to: https://github.com/OpenSC/OpenSC/commit/5a369a8f3

I am getting the same "Failed to erase card: Security status not satisfied` message from 0.21.00 `pkcs15-init -E` that worked before. 

I even tried the FIX_tool from Feitian  as listed in the above commit. It appeared to work at least twice.
But nothing is working now. 

And my epass2003 appears to be bricked. I suspect erase card may be losing memory and not really erasing the card. 

I suggest that there is still a bug in the token and you should contact Feitian if there tool doesn't not work for you. 

@FeitianSmartcardReader  any comments?

P.S.
In all the debug logs ones that worked, and one that did not, I get:
```
 P:13356; T:0x140396055971904 08:11:44.480 [pkcs15-init] apdu.c:323:sc_check_apdu: Invalid Case 4 short APDU:
 cse=04 cla=0c ins=a4 p1=00 p2=00 lc=2 le=0
 resp=0x7ffc9b9db700 resplen=0 data=0x7ffc9b9db6f0 datalen=2
 P:13356; T:0x140396055971904 08:11:44.480 [pkcs15-init] card-epass2003.c:1322:epass2003_select_fid_: APDU transmit failed: -1300 (Invalid arguments)
 P:13356; T:0x140396055971904 08:11:44.480 [pkcs15-init] card-epass2003.c:1378:epass2003_select_fid: APDU transmit failed: -1300 (Invalid arguments)
 P:13356; T:0x140396055971904 08:11:44.480 [pkcs15-init] card-epass2003.c:1530:epass2003_select_path: SELECT FILE (DF-ID) failed: -1300 (Invalid arguments)
 P:13356; T:0x140396055971904 08:11:44.480 [pkcs15-init] card.c:839:sc_select_file: 'SELECT' error: -1300 (Invalid arguments)
```
This then means `epass2003_select_fid_` fails. This appears to be a problem in how their SM code is using extended  APDUs and  `sc_check_apdu` does not like it.

**Comment by muks** [comment] 2021-08-30 13:53
Attached is the output of:
```
$ OPENSC_DEBUG=7 pkcs15-init --create-pkcs15 --profile pkcs15+onepin --use-default-transport-key --pin 12345678 --puk 87654321 --no-so-pin --label "Test Token" > pkcs15-init.log 2>&1
```
Output of above, piped to file: [pkcs15-init.log](https://github.com/OpenSC/OpenSC/files/7077174/pkcs15-init.log)

**Comment by frankmorgner** [comment] 2021-09-01 09:51
@FeitianSmartcardReader ?

**Comment by dengert** [comment] 2021-09-04 01:56
commit: ce7fa4295896ad71d14fdd00a592217924c2fe6f is a one line change to  the parameters of sc_pkcs15init_authenticate`  which results in:

```
P:13199; T:0x140573691557952 07:38:30.940 [pkcs15-init] ../../../src/src/libopensc/card.c:879:sc_select_file: returning with: 0 (Success)
P:13199; T:0x140573691557952 07:38:30.941 [pkcs15-init] ../../../src/src/pkcs15init/pkcs15-lib.c:3850:sc_pkcs15init_authenticate: called
P:13199; T:0x140573691557952 07:38:30.941 [pkcs15-init] ../../../src/src/pkcs15init/pkcs15-lib.c:3852:sc_pkcs15init_authenticate: path '3f0050154401', op=23
P:13199; T:0x140573691557952 07:38:30.941 [pkcs15-init] ../../../src/src/pkcs15init/pkcs15-lib.c:3868:sc_pkcs15init_authenticate: acl (nil)
P:13199; T:0x140573691557952 07:38:30.941 [pkcs15-init] ../../../src/src/pkcs15init/pkcs15-lib.c:3888:sc_pkcs15init_authenticate: returning with: 0 (Success)
```
Note the  `sc_pkcs15init_authenticate: acl (nil)` line. 
  
In commit: ce7fa4295896ad71d14fdd00a592217924c2fe6f 
`r = sc_pkcs15init_authenticate(profile, p15card, file, SC_AC_OP_UPDATE);`
was changed to 
`r = sc_pkcs15init_authenticate(profile, p15card, selected_file, SC_AC_OP_UPDATE);`
file had the "acl" bytes, but "selected_file" does not. 

In a working version from 0.20.0 "acl" is not NULL:
```
P:12947; T:0x139928475113536 07:30:24.784 [pkcs15-init] pkcs15-lib.c:3863:sc_pkcs15init_authenticate: acl 0x561049d061c0
P:12947; T:0x139928475113536 07:30:24.784 [pkcs15-init] pkcs15-lib.c:3877:sc_pkcs15init_authenticate: verify acl(method:16,reference:2)
P:12947; T:0x139928475113536 07:30:24.784 [pkcs15-init] pkcs15-lib.c:3695:sc_pkcs15init_verify_secret: called
P:12947; T:0x139928475113536 07:30:24.784 [pkcs15-init] pkcs15-lib.c:3699:sc_pkcs15init_verify_secret: get and verify PIN('user PIN',type:0x10,reference:0x2)
```
The authenticate and  verify wor, and the operation continues to use the "userPIN" to allow updating the card. 

(Tested by using "file" in OpenSC  from master as of today, 2021-09-03. on my epass2003 that was not bricked.)

This may have effected other card drivers. There may be a fix for the epass2003.

@popovec  any comments?

This does not fix #2398 But may be related if update binary in involved to get the longer label. The label is applied to PINS as well as the token label. 

With all my testing, many  sw1, sw2 codes are mapped to different OpenSC error codes then mapped to PKCS11 CKR_ codes which can lead to confusing messages.

**Comment by popovec** [comment] 2021-09-04 07:59
@dengert Thanks for the analysis, I'm trying to identify where the problem is. 

ce7fa4295896ad71d14fdd00a592217924c2fe6f assumes, that `r = sc_select_file(p15card->card, &file->path, &selected_file);` returns correct information about the file in `selected_file` variable.  Function `sc_select_file()` depends on `r = card->ops->select_file(card, in_path, file);`. I have tested mentioned patch with MyEID driver, which is working as expected.  

The ce7fa4295896ad71d14fdd00a592217924c2fe6f also assumes that the only authority that presents valid ACLs is the card. 

There is already some art of workaround in `sc_pkcs15init_authenticate()` ..  Prior to applying  the ce7fa4295896ad71d14fdd00a592217924c2fe6f, this function - called from `sc_pkcs15init_update_file()` - is relying on the ACL info from the profile file respectively on what was pre-populated into the `file` variable. 

By default, the mechanism bypassed the authority of the card. Is it really appropriate - not to accept the card as an authority?  Ok,  this can be suppressed by the flag SC_CARD_CAP_USE_FCI_AC in card-> caps , but it's confusing.  

If there is a card that does not provide correct information about its ACLs, this needs to be addressed in the card driver. It is incorrect to replace wrong/missing  information from the card through the use of a profile file /fake ACLs. If this is not solvable in the card driver, and we really need to do the workaround in the function `sc_pkcs15init_authenticate ()` let's name the switch `SC_CARD_CAP_USE_FCI_AC` with the right name `SC_CARD_CAP_WORKAROUND_USE_FAKE_AC` .

I admit that it is possible to revert the ce7fa4295896ad71d14fdd00a592217924c2fe6f and set the flag SC_CARD_CAP_USE_FCI_AC in the MyEID driver (I haven't tested it yet). However, I do not consider this to be a good solution. 


But let's go back to the problems with epass2003. I believe that the ACLs of the respective file are unavailable because they are not filled in by the card driver.

I'm not very familiar with the epass2003 driver, but `epass2003_select_file()` depends on `epass2003_select_fid()`,`epass2003_select_aid()` and `epass2003_select_path()` functions. Some kind of "cache mechanism" is used in the mentioned functions. I have no idea if the given problem - `acl (nil)` is caused by this "cache" or this problem is in different part of `epass2003_select_file()`  code.

**Comment by dengert** [comment] 2021-09-04 12:44
Thanks for quick response. I too am not familiar with the epass2003, until looking at this issue and never looked close at pkcs15init. There may be other bugs too. I did not say to revert https://github.com/OpenSC/OpenSC/commit/ce7fa4295896ad71d14fdd00a592217924c2fe6f but this was where the regression appears to have started. 

card-epass2003.c does not set SC_CARD_CAP_USE_FCI_AC. The comment in in opensc.h  "Use the card's ACs in sc_pkcs15init_authenticate(), instead of relying on the ACL info in the profile files." may be a clue. epass2003.profile has not changes since 2012. pkcs15-epass2003.c:52 also writes in debug log: "ePass2003 doesn't support SO-PIN and SO-PUK. You can unblock key with PUK." But they appear to use the user pin as the so_pin if needed. 

I am going to look at the epass2003 cache and fci processing. They have their own `epass2003_process_fci`

**Comment by dengert** [comment] 2021-09-06 14:43
When epass2003 file is selected, the FCI is processed, and sc_file_set_sec_attr is called [here](https://github.com/OpenSC/OpenSC/blob/master/src/libopensc/card-epass2003.c#L1916-L1919)

Problem is `card-epass2003.c` in `epass2003_select_fid_` and `epass2003_select_fid` do not map the  `sc_files_t`   
`unsigned char *sec_attr;        /* security data in proprietary format. tag '86' */` which is 8 bytes. It is not documented other then in [epass2003_construct_fci](`https://github.com/OpenSC/OpenSC/blob/master/src/libopensc/card-epass2003.c#L2033-L2103) to be written as tag 86. 

When a file is selected the FCI is processed, and sc_file_set_sec_attr is called [here](https://github.com/OpenSC/OpenSC/blob/master/src/libopensc/card-epass2003.c#L1916-L1919)
   
`struct sc_acl_entry *acl[SC_MAX_AC_OPS]; /* Access Control List */` is not created that is used by the  sc_pkcs15init_authenticate` with `selected file`. 

But the only place where the `file` and `selected_file` are available are during  initialization  `pkcs15-epass2003.c because the of the cache. 

When used after initialization only the `selected file` is available. This may explain problems with long tag, and EC keys as well.  

I am looking at  how to do this reverse mapping, as `sc_pkcs15init_authenticate` is called in many places and needs the `struct sc_acl_entry *acl[SC_MAX_AC_OPS]` initialized.

**Comment by dengert** [comment] 2021-09-08 12:52
@muks, can you try https://github.com/OpenSC/OpenSC/pull/2403 to see if it fixes all your problems?

**Comment by muks** [comment] 2021-09-08 17:22
> @muks, can you try #2403 to see if it fixes all your problems?

Yes, I built your branch (from the PR) and it does not show the error in this ticket's description.

Also wrote a signed keypair to the device, and used it with Kerberos authentication with our company realm and it worked OK.

So good work, and thank you. Once a new release is made with it, I hope it trickles into Fedora as an update package soon.

**Closed** 2022-01-25 15:03 UTC
Labels: bug
