### ISSUE TITLE
Problem with label formatting in C_GetTokenInfo / opensc 0.20.0

### ISSUE THREAD

**Issue by pboguslawski** [OpenSC/OpenSC#1922] opened 2020-01-30 13:40 UTC
Hello,

There seems to be a problem with label formatting in C_GetTokenInfo in opensc 0.20.0 (compiled in debian 10 from sources https://github.com/OpenSC/OpenSC/releases):

```
$ PKCS11SPY=/usr/lib/x86_64-linux-gnu/opensc-pkcs11.so PKCS11SPY_OUTPUT=logfile pkcs11-tool -T --module /usr/lib/x86_64-linux-gnu/pkcs11-spy.so

$ cat logfile 
[...]
5: C_GetTokenInfo
2020-01-30 12:55:30.442
[in] slotID = 0x0
[out] pInfo: 
      label:                  '               IBHS001 (UserPIN)'
      manufacturerID:         'www.CardContact.de              '
[...]
```

original opensc 0.19.0-1 from dpkg in debian 10 returns:

```
$ PKCS11SPY=/usr/lib/x86_64-linux-gnu/opensc-pkcs11.so PKCS11SPY_OUTPUT=logfile pkcs11-tool -T --module /usr/lib/x86_64-linux-gnu/pkcs11-spy.so

user@d10:~/tmp$ cat logfile 
[...]
5: C_GetTokenInfo
2020-01-30 13:13:10.851
[in] slotID = 0x0
[out] pInfo: 
      label:                  'UserPIN (IBHS001)               '
      manufacturerID:         'www.CardContact.de              '
[...]
```

This breaks apps like

(*) https://github.com/miekg/pkcs11/blob/master/pkcs11.go#L866

that seems to expect label to be formatted according to 

http://docs.oasis-open.org/pkcs11/pkcs11-base/v2.40/os/pkcs11-base-v2.40-os.html

> label       application-defined label, assigned during token initialization.  MUST be padded with the blank character (‘ ‘).  MUST NOT be null-terminated.

Debug show, that app (*) reads label as "IBHS001 (UserPIN)<here 15x zero byte>"

Problems:

(1)

Seems that label returned by C_GetTokenInfo from opensc 0.20.0 does not contain padding with spaces - it just ends after last letter. No such problem in manufacturerID field.

(2)

Order of label/pin in final label returned by C_GetTokenInfo is different in 0.19.0 and 0.20.0:

`IBHS001 (UserPIN)  != UserPIN (IBHS001)`

Is it intentional (may require config changes after upgrade to 0.20.0 if one uses label as parameter).

Regards,
Paweł

**Comment by frankmorgner** [comment] 2020-01-30 20:44
Duplicate of https://github.com/OpenSC/OpenSC/issues/1901

Sorry for the inconvenience.

**Comment by frankmorgner** [comment] 2020-01-30 20:47
I may have closed this too quickly.

Do I read correctly, that your label is padded with spaces in the front?!

**Comment by pboguslawski** [comment] 2020-01-31 08:00
Thank you for checking https://github.com/OpenSC/OpenSC/issues/1901 - this explains (2) but (1) still needs attention.

> Do I read correctly, that your label is padded with spaces in the front?!

Seems spaces added in the front of "IBHS001 (UserPIN)" in pkcs11-tool -T output in 0.20.0 like above are caused by fprintf (%32.32s) used in pkcs11-tool for displaying label...

https://github.com/OpenSC/OpenSC/blob/master/src/pkcs11/pkcs11-display.c#L928

...and are not part of label - displaying label works here ok.

Label value returned by C_GetTokenInfo seems to be "IBHS001 (UserPIN)" but should be "IBHS001 (UserPIN)               " (see oasis info above) and final pkcs11-tool -T output should be like in opensc 0.19 above (which seems to be correct and its expected by app linked above).

**Comment by frankmorgner** [comment] 2020-01-31 11:17
please check if https://github.com/OpenSC/OpenSC/pull/1926 fixes the padding

**Comment by pboguslawski** [comment] 2020-01-31 15:56
Just compiled 0.20.0 with fix https://github.com/OpenSC/OpenSC/pull/1926 applied (Debian 10) and now label works ok. Thank you!

Regards,
Paweł

**Closed** 2020-02-01 21:20 UTC
