### ISSUE TITLE
Russian UEC card support

### ISSUE THREAD

**Issue by socketpair** [OpenSC/OpenSC#646] opened 2015-12-28 15:26 UTC
There are technical description and sources (!) available here: 

http://www.uecard.ru/organizations/capabilities/terms-of-service

at the end of page "Download button".

P.S.
As technician said:
This card does not support PKCS #15 (iso-7816 15), But this card implements  ISO7816 1-4

**Comment by frankmorgner** [comment] 2015-12-31 10:27
Currently nobody is working on integrating this in OpenSC. @RushOnline are you?

**Comment by RushOnline** [comment] 2015-12-31 11:15
No, I dont. I'm sorry but as a developer I feel OpenSC very unusable.

**Comment by socketpair** [comment] 2016-01-01 08:21
@RushOnline what you recommend instead of OpenSC ?

**Comment by RushOnline** [comment] 2016-01-05 20:25
@socketpair да хрен его знает. Я просто сделал либу с поддержкой ГОСТ, дальше её куда то интегрировали в такую же проприетарщину. К сожалению не могу опубликовать результаты - работодатель против.

**Comment by mouse07410** [comment] 2016-01-06 15:12
I for one find OpenSC extremely useful/usable. It enables my PIV token on Linux and Mac OS X, and when I found some necessary features not working properly - it got fixed. Now, some of the fixes may take (unjustifiably) long time to get merged (my experience with OpenSC.tokend) - but overall I see no acceptable alternative to OpenSC.

**Comment by RushOnline** [comment] 2016-01-09 21:09
@mouse07410 - God bless @frankmorgner for his projects! But I worked on specific part to support  closed source legacy project. It make me crazy, my code was crazy and I think result will be crazy shit because that was crazy shit from beginning and by design. OpenSC doesn't fit that crazy proprietary shitcode at all. I hope you understand me right.

**Comment by socketpair** [comment] 2016-01-09 21:37
@RushOnline I will copy your message here if you decide to erase it :)

@mouse07410 - God bless @frankmorgner for his projects! But I worked on specific part to support closed source legacy project. It make me crazy, my code was crazy and I think result will be crazy shit because that was crazy shit from beginning and by design. OpenSC doesn't fit that crazy proprietary shitcode at all. I hope you understand me right.

**Comment by RushOnline** [comment] 2016-01-09 22:21
@socketpair Why just make a copy - we r on Github! You can fork my message, make your own branch and pull request if you can make better translation of my feelings about russian indian proprietary  software coders :)

**Comment by mouse07410** [comment] 2016-01-11 18:10
As I already stated - in the Open Source world there currently is no competitor/alternative to OpenSC (IMHO :). 

Special needs and proprietary projects may or may not benefit from it - but that's life, what can one do (or say). :-)

Yes I know enough about "russian indian coders". :-)

**Comment by frankmorgner** [comment] 2016-01-15 09:37
@socketpair nobody is currently working on integrating this card in OpenSC. But we would love to see you make a pull request...

**Closed by frankmorgner** 2016-01-15 09:37 UTC

**Comment by socketpair** [comment] 2016-01-15 09:46
@frankmorgner could you reopen ? maybe someone (me?) will work on that issue in future.

**Comment by frankmorgner** [comment] 2016-01-15 10:04
I think you can reopen the issue yourself. I suggest you do so when some new activity (a pull request or request for feedback?) arises.
