### ISSUE TITLE
Installer Verification (Checksums, Signatures)

### ISSUE THREAD

**Issue by DerBunteBall** [OpenSC/OpenSC#1338] opened 2018-04-19 00:29 UTC
### Verification of provided Installers

Hey all,

eventually I'm really blind. But is it true that there are no checksum files and digital signatures provided to verify the downloaded installer files?

It could be that I oversaw something but I can't find checksum files, PGP/GPG signature files or digital signatures in the file properties of Windows.

I think that's at least a bit problematic.

Could someone help me with this? I would like to verify the Installers before installing OpenSC.

Best Regards

**Comment by frankmorgner** [comment] 2018-04-19 07:59
duplicate of #1129

**Closed by frankmorgner** 2018-04-19 07:59 UTC
