### ISSUE TITLE
OpenSCToken from OpenSC-0.20.0.dmg fails to install on Mojave

### ISSUE THREAD

**Issue by mouse07410** [OpenSC/OpenSC#1934] opened 2020-02-05 20:35 UTC
### Problem Description

On macOS Mojave. Installing OpenSC from its binary distribution (regardless whether downloaded from https://github.com/OpenSC/OpenSC/releases/download/0.20.0/OpenSC-0.20.0.dmg or built from the source), OpenSCToken does not get installed regardless of whether you check the "Install" box for it in the "Customize" popup or not.

### Proposed Resolution

No idea. Make it work???

A workaround is to install `OpenSCToken.pkg`, which you get if you build OpenSC from the source, or if you build OpenSCToken separately (standalone).

### Steps to reproduce

Attempt to install, and observe the results.

**Comment by frankmorgner** [comment] 2020-02-12 01:00
I'm not entirely sure if your workaround is actually working. I've tried and failed. The installer runs successfully, but the app is not present in /Applications...

Currently, I suspect this is to the new notarization in Catalina:
>Upcoming Requirements
>
>When users on macOS Mojave 10.14 or later first open a notarized app, installer package, or disk image, they’ll see a more streamlined Gatekeeper dialog and have confidence that it is not known malware.
>
>Mac apps, installer packages, and kernel extensions that are signed with Developer ID must also be notarized by Apple in order to run on macOS Catalina.

Note the last paragraph... "OpenSC Notify", however, *does* get installed although I'm not aware of any notarization. This may be done automatically when using osacompile to create the app, I'm not sure.

**Comment by mouse07410** [comment] 2020-02-12 01:48
> I'm not entirely sure if your workaround is actually working. I've tried and failed...

I hate to admit it, but you're right - I tried it again now, and it did not install. 

But: I *can* start it from where it is, in `target_token/Applications/OpenSCTokenApp.app`. So...?

> Currently, I suspect this is to the new notarization in Catalina...

Don't know. I'm building binaries and running them all the time - except that those are now in .app format...

> Note the last paragraph... "OpenSC Notify", however, does get installed although I'm not aware of any notarization. This may be done automatically when using osacompile to create the app, I'm not sure.

Ha... I never used `osacompile` - it's either a compiler invocation (directly, or through `make`), or `xcodebuild` (or from within the `Xcode.app`).

What's the best way to test this hypothesis? Would you have a ready-example of how to build, e.g., OpenSCToken with it?

**Comment by frankmorgner** [comment] 2020-06-02 12:00
I believe this is the same problem as experienced in https://github.com/OpenSC/OpenSC/issues/1986. I've written my analysis here (https://github.com/OpenSC/OpenSC/issues/1986#issuecomment-637458281). I think the difference between the pkg and the app is that the pkg needs to be "installer" signed, while the app only requires normal code signing. I am only capable of doing the latter. We need all of this to get to notarization, which should be the main goal to get an acceptable user experiance.

However, I'm currently looking for support on this issue from someone with the correct signing capabilities.

**Comment by frankmorgner** [comment] 2020-06-02 12:04
I took some time to analyze this in detail. The problem is complex and most likely caused by the security changes made since High Sierra, which can't easily be ignored anymore.

The App runs fine when locally build, but inside the pkg it doesn't even install to /Applications properly. The Logs in konsole or when running

```
sudo installer -pkg OpenSCToken.pkg  -target / -verbose
```

aren't really helpful. (OpenSCToken.pkg is included as part of OpenSC 0.20.0.pkg) My last guess would be that the installation is prevented by Gatekeeper because the signing on the installer isn't correct (there currently is none). There's a good summary (https://wiki.freepascal.org/Code_Signing_for_macOS) which points out, that the App needs to be code signed (☑️), the pkg needs to be installer signed (I can't) and the dmg needs to be codesigned and submitted for notarization (never got to this step).

So, I don't have any ideas and you are my last resort! If you run#

```
git clone https://github.com/OpenSC/OpenSC
cd OpenSC
git clone https://github.com/frankmorgner/OpenSCToken
export OTHER_CODE_SIGN_FLAGS='--timestamp --options=runtime' CODE_SIGN_INJECT_BASE_ENTITLEMENTS=NO CODE_SIGN_STYLE=Manual
export CODE_SIGN_IDENTITY="your identity string"
MacOSX/build
```

Then everything gets built including the OpenSCTokenApp. (The same is done in CI with the code signing credentials).

I have also tried packaging the plain app into an dmg, but Gatekeeper prevents running this app (from the image) when downloaded from the web.

The missing bits seem to be the installer signing and the notarization (and stapling). We're looking for someone with an macOs installer certificate (99$ a year) who can help debugging this and maybe create a working bundle again...

**Comment by TWilb** [comment] 2020-06-17 20:59
I do have a paid Apple Developer Account but never used it for macOS apps - so a lot of new stuff to learn :-) I followed the instructions from the link to freepascal.org and I think I managed to create a signed and notarized dmg that is ok. After running the installer the applications are available under /Applications of the Mac.
For now I did it completely manually but it should not be too hard to integrate it into the build process.
If you want to try it out:

https://drive.google.com/file/d/1Do55z1jFVpYNhZWZi4xii-XWR5ZAoQRv/view?usp=sharing

**Comment by frankmorgner** [comment] 2020-06-23 09:15
@TWilb could we use your developer account in the CI pipeline to automatically create the bundle? If so, please contact me at frankmorgner at gmail.com

**Comment by TWilb** [comment] 2020-07-15 04:07
@frankmorgner I wrote an email a while ago. Did you receive it? Maybe it got flagged as spam.

**Comment by frankmorgner** [comment] 2020-07-22 21:36
Indeed, it was. I've just answered.

**Comment by Jakuje** [comment] 2022-09-29 12:47
What is the status of this issue? My understanding is that the MacOS signing was solved so we can close this issue.

**Comment by mouse07410** [comment] 2022-09-29 13:46
Since on my machines OpenSCToken seems to cause more harm than good, and with the recent versions of MacOS became unnecessary (as they include working pivtoken), I explicitly avoid installing OpenSCToken now. 

Please feel free to close this issue.

**Closed** 2022-09-29 13:52 UTC
