### ISSUE TITLE
Support for OAEP padding

### ISSUE THREAD

**Issue by mouse07410** [OpenSC/OpenSC#1026] opened 2017-04-14 18:05 UTC
### Expected behaviour

Should be able to specify RSA_PKCS1_OAEP_PADDING, and the software would add this padding before sending request to the token for RSA encryption, and remove this padding after receiving decrypted data from the token.

### Actual behaviour

Nothing :-)

**Comment by frankmorgner** [comment] 2017-04-16 20:20
If you're planning to make a contribution to the project, we'd love to add a new mechanism to OpenSC. We would be happy to get you going and to comment on your code. However, please have in mind that in lack of manpower, we can't do this on our own.

**Comment by frankmorgner** [comment] 2017-04-16 21:30
duplicate of https://github.com/OpenSC/OpenSC/issues/386

**Closed by frankmorgner** 2017-04-16 21:30 UTC
