### ISSUE TITLE
PIV II card emulation is too restrictive on usage types.

### ISSUE THREAD

**Issue by scottrix** [OpenSC/OpenSC#902] opened 2016-11-15 12:25 UTC
I have a PIV II card from my company and the KEY MAN key is used for email signing. Unfortunately the opensc emulation hardcodes the usage for the different keys and the KEY MAN is only setup for decrypt and unwrap.

If I patch and rebuild I can then get it working.

So either the implementation here is too restrictive or there is a spec out there somewhere that says the KEY MAN key pair should only be used for decrypt, unwrap.

Please assist.

**Comment by dengert** [comment] 2016-11-15 13:52
Yes there are "spec out there somewhere that says the KEY MAN key pair should only be used for decrypt, unwrap." The PIV driver was written to support the PIV standards as defined by NIST in a number of documents:

https://www.dhs.gov/homeland-security-presidential-directive-12
http://nvlpubs.nist.gov/nistpubs/FIPS/NIST.FIPS.201-2.pdf
http://nvlpubs.nist.gov/nistpubs/SpecialPublications/NIST.SP.800-73-4.pdf
In 800-73-4 See sections:
3.2.1 X.509 Certificate for Digital Signature 
3.2.2 X.509 Certificate for Key Management

HSPD-12 was first issued in August 2004. Various versions of FIPS-201 and NIST-800-73 have been issued since then. All of them define 4 certificates and keys including the 2 above and the restrictions on their use. 

The card can only enforce so much. With RSA the card can not tell what data is being signed/encrypted as the same card operation (RAW RSA) is being used. But with EC keys the card can, because ECDSA for signatures is not the same operation as ECDH for derivation.  With the signature key is used, the card requires the PIN to have been verified in the previous card operation, in an attempt to force the user to enter the pin for every signature. (Some cards may or may not enforce on the card the ECDSA vs ECDH.)

Over the years, others have implemented PIV card drivers, Microsoft Windows being the main one. This has then attracted other card vendors such as Yubico to produce PIV like devices that follow parts of the above standards. Note that a PKCS\#11 or CAPI interface are not defined in the the above standards. The OpenSC approach was to define a PKCS#11 driver that match the usage requirements as defined in the above specs. 

I would suggest that your company review the above standards especially if they are a federal agency or contractor who wants to, or is required to follow the above standards. If your cards are issued by a federal agency I would expect the certificates contain the key usage to match the above standards. 

On the other hand, the key usage is really enforced via the PKI infrastructure. i.e. certificates contain key usage, the certificate is signed by CA trusted by the recipient of the signature. Other requests to modify the PIV driver to not enforce the standards in the OpenSC software. 

ALso see: https://github.com/OpenSC/OpenSC/issues/847 and a possible solution in: 
https://github.com/dengert/OpenSC/commit/740a41b5a82d490ebc39ef22c128b413abede2ca  This is an untested patch to use the key usage from the certificate in place of the hard coded values. 
Line 948 starts at certificate 3, i.e. the first retired key. If it starred at 0, it would try the other 4 including the ones you want to use. But was never committed and may need modification as it depended on another pull request.  (It was designed for Yubico devices, and Yubico has its own PKCS\#11 module which may allow what you want.)

If your company still want to use the keys and has set the key usages in the certificates correctly, I could update  https://github.com/dengert/OpenSC/commit/740a41b5a82d490ebc39ef22c128b413abede2ca  
and maybve add an option to opensc.conf that this is optional and off be default.

**Comment by scottrix** [comment] 2016-11-15 14:42
Brilliant thanks for that, I'll get back to the team here that deal with it and hopefully get a response from our card manufacturer.

**Comment by dengert** [comment] 2016-11-15 15:33
As in most companies, most users are Windows users. With PIV cards most sites use the Microsoft PIV driver or other vendor's middleware. Google for  "PIV middleware for Windows" So any deviations from the standards may not work with the other middleware. The OpenSC code was designed for open source systems such as linux. But the OpenSC does have a minidriver to replace the Microsoft driver and also has PKCS\#11 usable via Thunderbird. I would suggest use the Microsoft driver for Microsoft CAPI applications and only use OpenSC for PKCS\#11 applications.   

Is not just the card manufacturer you need to talk to. Card Management is very important. 
The NIST standards do not define how cards are managed, and each card vendor may have additional card commands used when generating key and writing certificates and objects to the card. 

One such issue is the KEY MAN keys are designed for encryption and are intended to be held in escrow by the card management system, where as signature keys are generated on the card, and if the card is lost, stolen or broken a new signature key and certificate is generated on the replacement card. 

And if you are not part of the federal government you may also want to look at:
https://cio.gov/wp-content/uploads/downloads/2012/09/PIV_Interoperabillity_Non-Federal_Issuers_May-2009.pdf

**Comment by mouse07410** [comment] 2016-11-15 20:05
> hopefully get a response from our card manufacturer.

I'm probably missing something, but I don't see what you'd be discussing with your card manufacturer, or why. For signatures you have SIGN key. For encryption (or rather - *de*cryption) you have KEY MAN key. I can't see how a manufacturer would alter this, or why.

The card should be used appropriately (correct certificates should be put on it) - and that seems to be the responsibility of the department that issues/provisions/manages these cards in your organization.

**Comment by scottrix** [comment] 2016-11-15 23:15
Probably should have said card provider, not sure if it is in house or not.  The view of the person I'm speaking to about this, who isn't the card provider, but works with them, is that the spec doesn't say that the KEY MAN can't be used for other things, I don't agree, but don't have much say in it.

Since I'm basically a layman in this area.  The problem is that I'm trying to sign emails, to me it seems that the SIGN Key should be used for that and then I believe it can be used to decrypt a returned encrypted email too.  However, the card provider hasn't set up that cert for Email protection so the receiver of the email doesn't like it.  The KEY MAN cert is setup for Email protection but because it doesn't have the sign usage it can't be used.  I believe, having read the spec, that they might have used this one so that once it has expired and I get a new card, they can give me the cert so I can decrypt old emails, but I'm not sure.

**Comment by dengert** [comment] 2016-11-16 00:49
Pass the URL of this issue to your card provider, they need to read the specs.

**Comment by grep-ir** [comment] 2016-11-16 14:47
It looks like the answer resides in http://nvlpubs.nist.gov/nistpubs/FIPS/NIST.FIPS.201-2.pdf, section 5.2.1 X.509 Certificate Contents.  

This references: https://www.idmanagement.gov/IDM/servlet/fileField?entityId=ka0t0000000TNS1AAO&field=File__Body__s 

Worksheets 5, 6, 8, and 9 give the answer to key usage assignment for PIV compliant cards.

Given those facts, is OpenSC willing to support additional configurations which choose to not be PIV compliant (like Yubico)?  The most flexible solution to support this, as suggested, would be to honor the issued certificate key usages, enabled by a configuration file setting.

**Comment by dengert** [comment] 2016-11-16 15:05
dengert@740a41b in effect does this. It uses the certificate keyUsage to set the PKCS\#11 attributes.
Note that OpenSC piv driver already reads the certificate to find the public key to find the key type and size.

 I would like to prefer this as an option set in opensc.conf, because misuse of this feature has implications. The SIGN key requires the PIN each time enforced by the card.  The KEY MAN key does not and may be held in escrow and should not be used for signing. The CARD MAN key does not require a PIN at all. 
The responsibility of the use is on the card issuer to set keyUsage. 

Also when using a PIV card outside the guidelines, the CHUID must have a FASC-N with 9999, and should have a GUID. That could also be used to flag it is not a compliant PIV. 

I will look at   dengert@740a41b later this week it needs updating.

**Comment by grep-ir** [comment] 2016-11-16 15:25
Ok great.  Would you be lifting the PIN restrictions as well?  Keeping the PIN restrictions is preferred in my use case, but may not be in all others.  Do you think the ability to toggle both key usage assignment and pin enforcement would be useful to the community?

**Comment by dengert** [comment] 2016-11-16 21:43
The PIN enforcement is done on the card. Can't do anything about that other then cache the PIN in software.  (Personally, I do not like it, and don't cache the PIN.) When using a PIN PAD reader, the pin is transmitted between the reader and the card, so can not be cached (or sniffed either.) 

 OpenSC's PIV implementation is based on NIST 800-73-3 and has the same wording in 800-73-4:
3.2.1 X.509 Certificate for Digital Signature
"The PKI cryptographic function (see Table 4b) is protected with a “PIN Always” or “OCC Always” access rule. In other words, the PIN or OCC data must be submitted and verified every time immediately before a digital signature key operation."

3.2.2 X.509 Certificate for Key Management
"The PKI cryptographic function (see Table 4b) is protected with a “PIN” or “OCC” access rule. In other words, once the PIN or OCC data is submitted and verified, subsequent key management key operations can be performed without requiring the PIN or OCC data again."

3.1.3 X.509 Certificate for PIV Authentication
(same as 3.2.2)

3.1.4 X.509 Certificate for Card Authentication
"The PKI cryptographic function (see Table 4b) is under an “Always” access rule, and thus private key operations can performed without access control restrictions."

 With the Certificate and key for Card Authentication, the pin is not required. So the key can be used by anyone who possess the card. (consider lost or stolen card.)

In 800-4 they talk about OCC, which could be a fingerprint reader (as part of reader or card) and thus no PIN to cache.

**Closed** 2017-03-02 22:42 UTC
