### ISSUE TITLE
Support Opensc on iOS device.

### ISSUE THREAD

**Issue by xaqfan** [OpenSC/OpenSC#2640] opened 2022-11-09 06:31 UTC
Recently, there is a project based on the new features of iOS16 for smart cards. 
It needs to use opensc commands or interfaces on the iOS platform. 
The OpenSC structure is very complicated. 
I don’t know how to configure it. 
Is there a script to configure it in iOS? 
used on the platform.

thanks !!!

**Comment by frankmorgner** [comment] 2022-11-17 09:24
duplicate of https://github.com/OpenSC/OpenSC/issues/626
I'll add some comments there

**Closed by frankmorgner** 2022-11-17 09:24 UTC

**Comment by xaqfan** [comment] 2022-12-06 06:43
Sorry, I mean that how do I compile it? 
Use xcode or in terminal with command line?
I tried to compile it in terminal,but failed.

I will use the librarys of opensc on ios/ipados 16.x.
