### ISSUE TITLE
Smartcard not detected on macOS lock screen

### ISSUE THREAD

**Issue by jamesd09** [OpenSC/OpenSC#2351] opened 2021-06-07 13:59 UTC
Hi!
I'm trying to achieve the login into macOS Catalina (10.15.5) using the virtual smart card architecture.

This is the configuration that we are using:

- Virtual Smartcard for reader driver (https://github.com/frankmorgner/vsmartcard/tree/master/virtualsmartcard)
- PivApplet to emulate virtual smartcard (https://github.com/arekinath/PivApplet)
- OpenSCToken

I am using a custom Authorization Plugin on the login screen (```system.login.console```) & lock screen (```system.login.screensaver```) [_which appears when the user locks the system_] of macOS Catalina, which inserts a virtual smartcard on receiving a "trigger". 

Issue/Problem Description:

When the smartcard is inserted the view changes on the login screen and I can see the full name of the user that is on the smartcard. **However, when the user locks the system to go to the lock screen, & on receiving the "trigger" and subsequent smartcard insertion, the view does not change.** Also, my Authorization Plugin is displayed in old UI with black background when I am on the lock screen. I have verified that the trigger is received and the smartcard is successfully inserted through tailing the logs. Command used to verify that the card is inserted : ```system_profiler SPSmartCardsDataType```

Any help or hint would be really appreciated. Thanks!

**Comment by frankmorgner** [comment] 2021-09-01 10:22
PIVToken from Apple will be used, unless you've deactivated it. So your problem may not be related to OpenSC... If you verified OpenSCToken is used, how did you register the plugin? Its README.md suggests the following to make it available globally:
```
sudo -u _securityagent pluginkit -a /Applications/Utilities/OpenSCTokenApp.app/Contents/PlugIns/OpenSCToken.appex
```

**Comment by frankmorgner** [comment] 2023-06-16 07:19
Since the card you're using is not supported by OpenSC, I'm closing this issue

**Closed by frankmorgner** 2023-06-16 07:19 UTC

**Comment by frankmorgner** [comment] 2023-06-16 07:27
I just realized that this is a duplicate of https://github.com/OpenSC/OpenSC/issues/2297
